### ISSUE TITLE
Variant data type in recordset causes process to crash

### ISSUE THREAD

**Issue by patriksimek** [TimelordUK/node-sqlserver-v8#10]
```javascript
open(function(conn) {
    query(conn, "select cast(11 as sql_variant) as data;", [null], function(res) {
        console.log(res);
    });
});
```

Result:

![snimek obrazovky 2015-12-19 v 22 16 20](https://cloud.githubusercontent.com/assets/1000058/11915253/64c04852-a69e-11e5-8e26-cca72ee2f1fd.png)

**Comment by TimelordUK** [comment]
I have added this test to the params test suite and this now passes on my system.  May need some more work to this, currently the driver looks for variant type and reads the corresponding col type attribute and binds to that type.  Let me know if it fails other types.  Update to test.

**Comment by patriksimek** [comment]
Thanks, it's working now, but noticed this in my tests.

```sql
select cast(11.77 as sql_variant) as variant
```

Value is casted varchar, should be number.

**Comment by TimelordUK** [comment]
yes.  it looks like again the driver then will either have to guess or/and maybe a hint could be passed in similar to previous discussion.  i.e. 

  conn1.query("select cast(11 as sql_variant) as data;", [sql.Double()], function (err, res) {
          // driver will ask to bind variant to hint type ..... or it will have to guess
}

I will need to look to see if a declared type is given, this conversion would work OK.

**Comment by patriksimek** [comment]
According to [this docs](https://msdn.microsoft.com/en-us/library/dd303302.aspx), variant contains type information (basetype). Not sure how it is with ODBC.

**Comment by TimelordUK** [comment]
OK, I think I finally understand what is going on here ... I am testing a fix at the moment but do not want to release until i am confident.  It will fall back to char if it cannot read the variant header to a known type - however if it can read type it will automatically translate.

hopefully in a day or so I will release this.

**Comment by TimelordUK** [comment]
I have checked the fix into latest version ... it handles basic types OK I have added some tests, so example above should decode correctly to number.

**Comment by TimelordUK** [comment]
I will assume the issue now closed.  Thanks for bringing this and all other very good tests to my attention.  Any more issues with variant please raise a new issue.
