### ISSUE TITLE
Columns that are foreignKeys and at the same time primaryKeys are duplicated in bulk-queries

### ISSUE THREAD

**Issue by olsn** [TimelordUK/node-sqlserver-v8#100]
Original Error:
When using bulk-insert on a table that has the same column as foreign key and primary key, i get the following error:
```
RequestError: The column name 'someColNameThatIsForeignKeyAndPrimary' is specified more than once in the SET clause or column list of an INSERT. A column cannot be assigned more than one value in the same clause. Modify the clause to make sure that a column is updated only once. If this statement updates or inserts columns into a view, column aliasing can conceal the duplication in your code.
```

----

I've got this to work which adjusting the `recalculateAssignableColumns` in _table.js:68_ (https://github.com/TimelordUK/node-sqlserver-v8/blob/master/lib/table.js#L68)
With the following code:
```
    function Meta (tableName, cols) {
          // filter out duplicate columns with the same name
	  cols = cols.filter((item, pos) => {
		return cols.findIndex(col => col.name === item.name) == pos;
	  });
		
      function getFullName () {
```

Not sure if that is the correct way to fix this, it'd probably be better to fix in the C-code i suspect? However I'm not really familiar with that.

**Comment by TimelordUK** [comment]
thanks very much this looks fine to  me - I can add to release for hidden / generate bug release

**Comment by olsn** [comment]
Works with `0.7.3` thank you very much!
