### ISSUE TITLE
How to send user defined table as a parameter into the stored procedure call

### ISSUE THREAD

**Issue by xueenda** [TimelordUK/node-sqlserver-v8#104]

**Comment by xueenda** [comment]
What's the input should look like? Please document this in the read me thanks.

var tvp = sql.TvpFromTable(t)

procedure.call([], (err, results) => {
});

pm.callproc("US_BUYERS_ENTRY_UPLOAD", [t, "7071144", "exue"], function(err, result){
});

**Comment by TimelordUK** [comment]
Can you look in geography.js under unit tests look for test 

Use TVP to insert geography lines using pm

**Comment by TimelordUK** [comment]
closing this - please raise if still an issue
