### ISSUE TITLE
Dependency on Python

### ISSUE THREAD

**Issue by NoelAbrahams** [TimelordUK/node-sqlserver-v8#105]
Hi, @TimelordUK 

**Version** 0.8.0
**Windows Version** Windows 10.

Trying to upgrade to the latest (after a very long time). 

NPM is erroring out as reported below. I found [a possible solution](https://catalin.me/how-to-fix-node-js-gyp-err-cant-find-python-executable-python-on-windows/), but wanted to check if there is a way to avoid having to install Python? In the earlier version this dependency was not there.

Thanks.

```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd B:\og\service\module.storage\node_modules\msnodesqlv8
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by TimelordUK** [comment]
this is usually as a result of node-gyp trying to build the c++ where it first checks for dependencies.  node-gyp should not actually attempt a build unless the binding.gyp file is present, for npm release that file should not be present?

**Comment by NoelAbrahams** [comment]
I need some time to look into this. Will get back to you as soon as possible.

**Comment by NoelAbrahams** [comment]
This problem appears to have resolved itself after upgrading to Node 10. It initially cropped up when updating msnodesqlv8 to version 0.8.0 using Node 6.
