### ISSUE TITLE
Is it possible to use drivers other than SQL Native Client?

### ISSUE THREAD

**Issue by Durzo84** [TimelordUK/node-sqlserver-v8#108]
Hi,

I have an electron app and am running into an issue with the SQL server native client. Installing it on it's own (without installing SQL server on users machine) results in missing registry entries. I am logging the following error from my app.

> [2019-08-05 15:27:37.735] [error] Error authenticating user. Message: ConnectionError: Error: [Microsoft][SQL Server Native Client 11.0]Registry information is corrupt or missing. Make sure the provider is installed and registered correctly.,Error: [Microsoft][SQL Server Native Client 11.0]Client unable to establish connection,Error: [Microsoft][SQL Server Native Client 11.0]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

I know it will work if I install SQL server on the user's machine, but this is not feasible for all users, is there any way to get msnodesqlv8 to use the ODBC driver for sql server?

**Comment by TimelordUK** [comment]
msnodesqlv8 is using ODBC API to communicate with the server, the above error seems like client is not installed or is corrupted.  It definately should not be necessary to install SQL server itself to use this library - is ODBC definately installed?

if you launch ODBC data admin via start ODBC

i.e. in ODBC Data Source admin - say 32 bit, look under drivers and you should see SQL Server Native Client 11.0 SQLNLC11.DLL

even if this is present it may be worth re-installing, the registry is simply a key like 

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSSQLServer

which seems to be missing on your client

**Comment by Durzo84** [comment]
I tried reinstalling SQL native client, and even though it adds the driver to my ODBC drivers, it still does not create the necessary registry entries. Anyway that is an issue outside of msnodesqlv8.

I ended up copying the reg entries for MSSQLServer/Client/SNI11.0 from a working machine into the new client machine and it works now. Thanks for your help!
