### ISSUE TITLE
__webpack_require__(...).readdirSync is not a function

### ISSUE THREAD

**Issue by ghost** [TimelordUK/node-sqlserver-v8#111]
Version: 1.37.0 (user setup)
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

npm:
version: 6.9.0

Gulp:
CLI version: 2.2.0
Local version: 3.9.1

SharePoint 2016 On-Prem No JavaScript Library

package.json
{
  "name": "sqlwidget-webpart",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "browser": {
    "child-process": false
  },
  "dependencies": {
    "@microsoft/sp-core-library": "^1.8.2",
    "@microsoft/sp-lodash-subset": "^1.8.2",
    "@microsoft/sp-office-ui-fabric-core": "^1.8.2",
    "@microsoft/sp-webpart-base": "^1.8.2",
    "@pnp/common": "^1.3.4",
    "@pnp/logging": "^1.3.4",
    "@pnp/odata": "^1.3.4",
    "@pnp/sp": "^1.3.4",
    "@types/arcgis-js-api": "^4.12.0",
    "@types/es6-promise": "^3.3.0",
    "@types/gulp": "^4.0.6",
    "@types/react-dom": "^16.8.5",
    "@types/tedious": "^4.0.0",
    "@types/tedious-connection-pool": "^1.0.2",
    "@types/webpack-env": "^1.14.0",
    "dgram": "^1.0.1",
    "fs": "0.0.2",
    "loadash": "^1.0.0",
    "msnodesqlv8": "^0.8.3",
    "mssql": "^5.1.0",
    "net": "^1.0.2",
    "sp-pnp-js": "^3.0.10",
    "tedious": "^6.3.0",
    "tls": "0.0.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "^0.7.29",
    "@microsoft/sp-build-web": "^1.8.2",
    "@microsoft/sp-module-interfaces": "^1.8.2",
    "@microsoft/sp-tslint-rules": "^1.8.2",
    "@microsoft/sp-webpart-workbench": "^1.8.2",
    "@types/chai": "^4.2.0",
    "@types/jquery": "^3.3.31",
    "@types/mocha": "^5.2.7",
    "@types/mssql": "^4.0.16",
    "@types/node": "^12.7.1",
    "@types/webpack": "^4.32.1",
    "ajv": "^6.10.2",
    "gulp": "~3.9.1",
    "webpack": "^4.39.2"
  },
  "description": "This is where you include your WebPart documentation.",
  "directories": {
    "lib": "lib"
  },
  "author": "",
  "license": "ISC"
}

tsconfig.json
{
  "extends": "./node_modules/@microsoft/rush-stack-compiler-2.9/includes/tsconfig-web.json",
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "inlineSources": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "importHelpers": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@types/node",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env",
      "node"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection",
      "es6"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "lib"
  ]
}

Code:
import { SqlClient } from 'msnodesqlv8';

public ConnectionWizardDataSubmit(): any
  {
    var returnValue: any;
    var sqlConfig: any;
    var sqlStatement: string = "";
    var sql: SqlClient = require('msnodesqlv8');

    sqlConfig = this.BuildSqlServerConnectionString();
    sqlStatement = this.BuildSqlStatement("SELECT @@VERSION AS VersionInfo", "master");

    try
    {
      sql.query(sqlConfig, sqlStatement, (err, rows) =>
      {
        if (err)
        {
          console.log(err);
        }
        console.log(rows);
      });

      returnValue = true;

    } catch (error) {
      console.log("Error:" + error);
      returnValue = false;
    }

    return returnValue;
  }

Result:
* Error Name: TypeError
* Error Message: __webpack_require__(...).readdirSync is not a function
* Error Stack: TypeError: __webpack_require__(...).readdirSync is not a function
    at https://localhost:4321/dist/sqlwidget-webpart-web-part.js:15197:40
    at Object.<anonymous> (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:15246:3)
    at Object.<anonymous> (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:15251:30)
    at __webpack_require__ (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:20:30)
    at https://localhost:4321/dist/sqlwidget-webpart-web-part.js:14531:21
    at Object.<anonymous> (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:14966:3)
    at Object.<anonymous> (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:14970:30)
    at __webpack_require__ (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:20:30)
    at Object.<anonymous> (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:14432:12)
    at Object.<anonymous> (https://localhost:4321/dist/sqlwidget-webpart-web-part.js:14487:30)

I am unable to resolve this issue.
Please let me know if you can help.

thanks.

**Comment by mtriff** [comment]
Webpack support was added in v0.8.9.
