### ISSUE TITLE
MsNodeSqlV8 Executing Stored Procedure with Multiple Select Statements

### ISSUE THREAD

**Issue by siddiqicps** [TimelordUK/node-sqlserver-v8#113]
Dear Team,

I am using msnodesqlv8 library for calling stored procedures using Procedure Manager, which is working fine. Recently I found that the library is unable to handle the case where a procedure has multiple select statements. In callback result parameter its giving the result set for last select statement only. However I want result sets for all the select statements in procedure.
Please suggest a suitable solution of problem.

Thanks & Regards
Tahir Siddiqi

**Comment by TimelordUK** [comment]
Thanks I will try and reproduce issue over coming days. 

Will report back.

**Comment by siddiqicps** [comment]
Dear TimelordUK,

Did you get time to check this issue. I dug down the source code, the C++ library, where I got 
 "ReadNextResultOperation". But I am not sure how it's used to get next result set from inside procrdure. 
Kindly help me to resolve this issue.

**Comment by TimelordUK** [comment]
I will try to look at this issue over the weekend. If you have time it
would be worth setting breakpoints in reader.js which is really doing the
communication to the cpp. For example rather than using a store procedure
if a query is submitted with concatenated statements the driver should
return reach row set. This is not working in there case of a stored
procedure my guess is somewhere in this file.

It is unlikely the cpp driver is wrong as the JavaScript should ask the cpp
to move to next result

**Comment by siddiqicps** [comment]
Thanks a lot, I will check as suggested.
One more thing I wanted to know, what is the purpose of query polling, which is default set as false?

**Comment by TimelordUK** [comment]
This was added to cancel long standing queries as it was safer in cpp driver to use polling. Now the cleanest way to cancel a query is not to bother with polling and first pause the query and then cancel.   This functionality was added later before only way to cancel a query was using polling based mode but it’s much slower if you are doing lots of little selects.

**Comment by siddiqicps** [comment]
I debugged it and I am getting all the result sets inside end method in driver.js. But as an end result I am getting only the result set of last select statement. Don't know where the other result sets are going. I think there is some issue in the driver.js file.

**Comment by TimelordUK** [comment]
Ok thanks I’ll look at it. What type of way are you calling is it an event stream based approach or you call and get a callback.

**Comment by siddiqicps** [comment]
I am using callback approach.

**Comment by TimelordUK** [comment]
this is in 0.8.4

for the below example when using proc manager the call method will now call back with each result set and output will be null if another result set is due.   On last result output ill be non null and return the bound output parameters

```sql
create PROCEDURE multi_select AS
BEGIN
	select top 5 'syscolumns' as table_name, name, id, xtype, length from syscolumns
	select top 5 'sysobjects' as table_name, name, id, xtype, category from sysobjects
END

```

```javascript
const aggregate = []
proc.call([], (err, results, output) => {
    assert.ifError(err)
    aggregate.push(results)
     if (output) {
         assert.strictEqual(2, aggregate.length, 'results didn\'t match')
         assert.strictEqual(true, Array.isArray(aggregate[0]))
         assert.strictEqual(true, Array.isArray(aggregate[1]))
         asyncDone()
     }
})
```

**Comment by siddiqicps** [comment]
@TimelordUK 
Thanks a lot dear, this was the perfect solution. Actually I was using 0.8.3 and also not aggregating the results.

**Comment by TimelordUK** [comment]
closing this issue seems solved.  Thanks for raising.
