### ISSUE TITLE
Another None of the binaries loaded successfully error

### ISSUE THREAD

**Issue by moloni-pt** [TimelordUK/node-sqlserver-v8#114]
Hello, 

I created an electron app based on the create react app boilerplate, and everything is running well on x64, but when I try to run my portable on a x32 system, I get the error 

`Uncaught (in promise) Error: None of the binaries loaded successfully. Is your node version >= 10.15`

This portable was packaged on a x64 machine with node v12.10.0, and I have the  latest version of msnodesqlv8. 

Could you please help findout out what am I doing wrong? 
If I could  send you any info please let me know, thank you! :)

**Comment by moloni-pt** [comment]
If you don't mind, could you help with this issue? I tried already a lot of stuff but can't get the driver to run in x32 systems :(

**Comment by TimelordUK** [comment]
Are you able to run a x32 bit normal Node x32 application on the target host.  Is 32 bit ODBC driver installed on the target.  Are you running on a 64 bit OS?  

It is not necessarily easy to find these problems.  The driver will loop through each binary in turn to find one that loads.  If you are able to run in 32 bit Node it shows this is electron specific.  Have you tried to build the electron driver on this target host.

**Comment by TimelordUK** [comment]
http://www.dependencywalker.com/

Sometimes depends executable can help. If you for example load the 64 bit node electron binary and look at the dlls that’s been loaded then try 32 bit and see if any obvious ones are missing. 

Also sometimes 

https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

If you look at electron 64 whilst it’s running with process explorer there is a tab you can view to see all loaded dlls.  The problem may be the system cannot dynamically load a dll

These problems can be very hard to find it’s not same as a bug which can be reproduced and fixed.

**Comment by moloni-pt** [comment]
Hey, thanks for the replies :) 

Yesterday night I managed to make it work in both 64 and 32 bits.
Turned out it was a mismatch between versions, so here is what I did: 

First I had to re-install everything in order to have a _clean sheet_

Installed NODE 12, node-gyp, windows-build-tools. 

Then I noticed that my node-sqlserver-v8 was in a  older version. 
I then updated it to the latest version. 

Then I updated electron to a newer version (the latest of the v5) and fixed all the problems that I was getting. 

Then I ran the command you had in your wiki: 

```
"scripts": {
    "copybinding": "copy .\\node_modules\\msnodesqlv8\\bindingdotgyp.old .\\node_modules\\msnodesqlv8\\binding.gyp",
    "rebuild": "cd .\\node_modules\\.bin\\ && electron-rebuild -f -w msnodesqlv8 --module-dir ..\\..\\",
    "movenode": "move .\\node_modules\\msnodesqlv8\\bin\\win32-x64-69\\msnodesqlv8.node .\\node_modules\\msnodesqlv8\\lib\\bin\\msnodesqlv8.node",
    "postinstall": "npm run copybinding && npm run rebuild && npm run movenode",
    ...
},
```
Here I started getting something different than before. 
The first thing I got was that the `bindingdotgyp.old` was not in the folder, so I came to this rep, downloaded only the file `bindingdotgyp.old` and manually put it in the folder. 

Then the next error I got was in here: ` "move .\\node_modules\\msnodesqlv8\\bin\\win32-x64-69\\msnodesqlv8.node .\\node_modules\\msnodesqlv8\\lib\\bin\\msnodesqlv8.node"`

Again I went to the folder and there was nothing in the `win32-x64-69` folder. 
But in the bin folder there was a `win32-x64-70` folder. 

So I changed the `movenode`, ran `npm run postinstall`, `npm run package` and now I got a installer for each version and a portable for both versions **fully working** :) 

I'll just leave this here for anyone having this issue, if this could help :) 

Thanks again for the support and for creating node-sqlserver-v8! :)

**Comment by mtriff** [comment]
Note for others: As of v1.0.1, binaries are no longer loaded via this method and the steps above (renaming `bindingdotgyp.old`, renaming `msnodesqlv8.node`, etc. are no longer required. Running `node-gyp rebuild` and directly in the `node_modules\msnodesqlv8`, or `node_modules\.bin\electron-rebuild` is all that is required to run a build.
