### ISSUE TITLE
MSSQL TVP Error

### ISSUE THREAD

**Issue by siddiqicps** [TimelordUK/node-sqlserver-v8#116]
Dear Team,

I am calling a stored procedure with TVP as input parameter. When I am passing single data object it is working fine, however when I am passing TVP with multiple objects it's giving below error.

TypeError: Cannot convert 3942 to a BigInt
    at Object.begin (E:\API\node_modules\msnodesqlv8\lib\driver.js:270:74)
    at Promise (E:\API\node_modules\msnodesqlv8\lib\reader.js:90:24)
    at new Promise (<anonymous>)
    at beginQuery (E:\API\node_modules\msnodesqlv8\lib\reader.js:89:16)
    at Object.begin (E:\API\node_modules\msnodesqlv8\lib\reader.js:241:9)
    at Immediate.setImmediate (E:\API\node_modules\msnodesqlv8\lib\driver.js:296:15)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

My TVP looks like this

 table_value_param:
   [ { sql_type: -5, value: [Array] },
     { sql_type: -5, value: [Array] },
     { sql_type: 4, value: [Array] },
     { sql_type: -9, value: [Array] },
     { sql_type: -9, value: [Array] },
     { sql_type: -9, value: [Array] },
     { sql_type: -9, value: [Array] },
     { sql_type: 93, value: [Array] } ],
  row_count: 4,
  schema: 'dbo' }

**Comment by TimelordUK** [comment]
Have you looked at the geography data points example I believe it uses a
set of geography points and makes one call using tvp. Is that different to
this example ?

**Comment by siddiqicps** [comment]
My data is this
[ 
   { 
      "NodeDataID":null,
      "NodeID":3915,
      "MLevel":"3",
      "CurrentStats":"dsfvwertfwwefw",
      "ActionPlan":"ewfewfeww",
      "Comment":"ewrwefgvfv",
      "EvidenceComment":"vsfvfwefwdfds",
      "TargetDate":"2019-10-31",
      "Evidence":null
   },
   { 
      "NodeDataID":null,
      "NodeID":3916,
      "MLevel":"4",
      "CurrentStats":"sdfdscewre",
      "ActionPlan":"fcgvwrfwefd",
      "Comment":"erewfcdsfsd",
      "EvidenceComment":"rvcsdvgwfewfe",
      "TargetDate":"2019-10-31",
      "Evidence":null
   }
]

and I am using below code 

poolConnectionObject.connection.getUserTypeTable('ud_userTypeTable', function (err, t) {
    if(err){
        console.log(err);
    }
    var table = t
    console.log(table.columns)
    table.addRowsFromObjects(payload.dataObjects)
    console.log(table)
    var tp = node_mssql.TvpFromTable(table)
    console.log(tp);
    table.rows = [];
    // Getting Procedure Object from poolConnectionObject of application
        const aggregate = [];
        var pm = poolConnectionObject.connection.procedureMgr();
        pm.callproc('AddNodeAnswersDraftComplete',[tp],function(err, result, output) {
            console.log(err)
            console.log(result);
            console.log(output);
            if(result.length > 0){
                aggregate.push(result);
            }
            if(output){
                dbResponseObj.status            = 1;
                dbResponseObj.procedureSuccess  = !!output[1];
                dbResponseObj.procedureMessage  = output[2];
                dbResponseObj.recordset         = aggregate;
                callback(dbResponseObj);
            }
    })
})

**Comment by TimelordUK** [comment]
Can you provide the stored procedure and table type unless I have an example demonstrating problem it will be very difficult to help.  Just provide enough to reproduce the issue.

**Comment by TimelordUK** [comment]
Closing.  Check latest version and provide example to us showing issue.
