### ISSUE TITLE
done event not fired on cancelled queries

### ISSUE THREAD

**Issue by dhensby** [TimelordUK/node-sqlserver-v8#120]
It appears that the `done` event does not fire if the a query is cancelled (by calling `.cancel()`). Is this behaviour by design?

In the `mssql` library I'd like to be able to more clearly depend on the `done` event. If there are no plans to add `done` on cancelled queries I'll polyfill it in the `mssql` lib.

**Comment by dhensby** [comment]
Never mind, this seems to be working as expected 🤦‍♂

**Comment by dhensby** [comment]
OK - I've investigated this a bit further and the problem is specifically if a paused query is cancelled, then the done event is not fired, but if a query that is not paused is cancelled it does.

**Comment by TimelordUK** [comment]
shis should be fixed 0.8.5

**Comment by dhensby** [comment]
Thanks. I'll update my PR and let you know if it's all sorted :)

**Comment by dhensby** [comment]
This is fixed, thanks :)
