### ISSUE TITLE
Using drivers other than SQL Native client

### ISSUE THREAD

**Issue by MatejSkrbis** [TimelordUK/node-sqlserver-v8#128]
I've tried using ODBC 17 driver but couldn't get it working. Are other drivers than native client supported?
It throws "Data source name not found and no default driver specified"

> Driver={ODBC Driver 17 for SQL Server};Server={\*\*\*\*\*.database.windows.net,1433};Database=\*\*\*\*\*;Uid=\*\*\*\*\*;Pwd=\*\*\*\*\*;

After installing SQL Server Native Client 11.0 the connection string for ODBC 17 started working, but the problem is that anything specified in Driver string did. So I am not sure if ODBC 17 driver actually get used.

> Driver={Bla bla};Server={\*\*\*\*\*.database.windows.net,1433};Database=\*\*\*\*\*;Uid=\*\*\*\*\*;Pwd=\*\*\*\*\*;

This is working after installing SQL Native client.

I checked that driver is installed and working with this powershell script.
```
$conn = new-object system.data.odbc.odbcconnection 
$conn.connectionstring = 
"Driver={ODBC Driver 17 for SQL Server};Server={*****.database.windows.net,1433};Database=*****;Uid=*****;Pwd=*****;"

$conn.Open()
$conn.State
$conn.Close();
```

**Comment by MatejSkrbis** [comment]
It seems ODBC 17 driver is not used as we are getting error "Associated statement is not prepared" that should not be thrown in newer versions of ODBC driver. I would guess that SQL Server Native Client 11.0 driver is used no matter what's the connection string.

**Comment by TimelordUK** [comment]
OK so looking at sample streaming.js as an example

```javascript
const connectionString = 'Driver={ODBC Driver 17 for SQL Server};Server=(localdb)\\node;Database=scratch;Trusted_Connection=yes;'
```

```cmd
submitted SELECT * FROM syscomments elapsed 1 ms
done
24 rows returned elapsed 37
finished
free
```

however using 

```javascript
const connectionString = 'Driver={Blah Blah for SQL Server};Server=(localdb)\\node;Database=scratch;Trusted_Connection=yes;'
```

```cmd
[Error: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified] {
  sqlstate: 'IM002',
  code: 0
}
```
So i dont seem to be seeing this issue?  on my machine it can run on SQL Server Native Client 11.0 and ODBC Driver 17 for SQL Server but certainly not some random driver name,

**Comment by Shao-Eric** [comment]
@TimelordUK 
Hi, it also works for me when I use {ODBC Driver 17 for SQL Server}, no error or anything, however if I go into debug mode, I will see it gets defaulted back to {SQL Server Native Client 11.0}

**Comment by Shao-Eric** [comment]
Looks like the Driver is hard coded, check this out
![image](https://user-images.githubusercontent.com/20850250/91058846-f6969280-e5f6-11ea-8926-f9c86707aa6f.png)

**Comment by TimelordUK** [comment]
I do not recognise that code in our library is that a file from mssql?

**Comment by Shao-Eric** [comment]
My bad, you are right, thats from mssql. Let me reach out to them. Thanks for the prompt response.

**Comment by TimelordUK** [comment]
Ok thanks i am cloising this issue seems like not related to us.
