### ISSUE TITLE
Bulk insert call back function is called when the insert starts. Is there a way to know when all records are inserted into table.  I am using tablemgr insertrows

### ISSUE THREAD

**Issue by vikgar** [TimelordUK/node-sqlserver-v8#130]

**Comment by bsEmo** [comment]
I'm also facing this. It is causing application crashes due to memory issues when many inserts are running concurrently.

**Comment by TimelordUK** [comment]
sorry not responded earlier - i looked at code previously and did not think anything was wrong but having just writtena test you are quite right.

I am looking at it now should have a fix shortly.

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8/releases/tag/v1.1.6

this should be fixed now.

**Comment by TimelordUK** [comment]
i will close this - it is fixed in latest release please let me know if you still think there is a problem
