### ISSUE TITLE
 Electron: Loading non context-aware native modules in the renderer process is deprecated

### ISSUE THREAD

**Issue by mtriff** [TimelordUK/node-sqlserver-v8#132]
Creating this issue for visibility. Loading the module in Electron version 7 now outputs the following warning:

```
Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

This module will eventually need to be updated to be NAPI or context aware in order to work with future versions of Electron. 

For reference:
electron/electron#18397
https://nodejs.org/api/addons.html#addons_context_aware_addons

**Comment by mtriff** [comment]
@TimelordUK, I've been taking a look at this, but not getting very far. The issue is that this module will stop working with Electron in a couple of versions because it is not "context-aware".

There are two options to fix this:
1. Implement the context-aware initialization and handling as documented here: https://nodejs.org/api/addons.html#addons_context_aware_addons. I started following these instructions but Electron doesn't seem to detect it and still complains that the module is not context aware.
2. Switch msnodesqlv8 from the older/direct v8 API to [N-API](https://nodejs.org/api/n-api.html#n_api_n_api) (using the C++ wrapper [node-addon-api](https://github.com/nodejs/node-addon-api)). This would be a major change, but it would have the advantage of being more stable against future changes to Node. Once implemented, it would make the module context-aware without any further changes.

Unfortunately, these changes are a bit beyond my C++ abilities (and familiarity with this codebase). Would you be able to look into this?

**Comment by TimelordUK** [comment]
I started looking last night at usng the NAN api vs N-API.  I changed firstly the registration in Connection.cpp to use all NAN including the macro they say should solve this problem.  Its checked in on the linux branch I have not had much time to test it.

I did copy the local prebuild binary for 76 electron x64 into the bootstrap sample we have been testing with and i do not see the error reported anymore re. this module is not context aware and deprecated.   I still see the output on chrome console.

Any chance you could check out linux branch and confirm it looks OK?

A lot of rest of code is still unchanged, It will take quite some time to shift everything over to an abstract API but well worth doing as you say,

**Comment by mtriff** [comment]
Just gave it a try with both Electron v8 and v9. Looks like it's working great in both! No warning message from Electron and querying/stored procs are working without issue.

Migration to NAN isn't complete, but the issue with Electron seems to be resolved already. I'll close this issue. Thanks for the fix!
