### ISSUE TITLE
Reducing the file size of the package

### ISSUE THREAD

**Issue by NoelAbrahams** [TimelordUK/node-sqlserver-v8#134]
**Version** 0.8.4

The MSNodeSqlv8 folder under node_modules is 15MB. 

This is the largest package we have amongst all other installed packages.

About 13MB of this is in the `lib/bin` folder

![image](https://user-images.githubusercontent.com/1106823/73447973-ca17e200-4357-11ea-95f7-25715d8c633d.png)

Is there any way to reduce this during the installation? Is there a need for every consumer to have the electron binaries, for instance?

The package size is a problem because it is adding overhead to the time taken to deploy to the cloud.

Thanks for maintaining this repo. It's a great help.

**Comment by TimelordUK** [comment]
hello, sorry for delays

looks like https://github.com/TimelordUK/node-sqlserver-v8/issues/143

the suggestion being we remove the installed binaries and rely on tools to now build locally.  As you point out is has become increasingly impactical to try and ship all versions.

So we will probably proceed on that basis.
