### ISSUE TITLE
using TvpFromTable with strings over 4000/8000 in length throw an error

### ISSUE THREAD

**Issue by Jeff-14159** [TimelordUK/node-sqlserver-v8#135]
When using table.addRowsFromObjects(vec) and sql.TvpFromTable(table) to populate a table/TVP  you will get an error if: 

- if the tvp has a single row of data with a string over 8000 in length

- if the tvp has multiple rows of data with a string over 4000 in length

`[Error: [Microsoft][ODBC Driver 13 for SQL Server]Invalid precision value] sqlstate: 'HY104', code: 0`

`[Error: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Trying to pass a table-valued parameter with 1 column(s) where the corresponding user-defined table type requires 2 column(s).]  sqlstate: '42000', code: 500`

In our case the tvp has 2 columns a varchar(200) and a varchar(max) however after pushing data the ```tvp.table_value_param.sql_type``` it was set to ```12``` for both I believe it should be -10 for the varchar(max).

In attempting the following workaround I noticed I could set the sql_type to -10 when there was only one row a data present and that would let me get over the 8000 limit however when there are more that one rows data present the limit remains at 4000 and the -10 sql_type seems to be ignored
```
table.addRowsFromObjects(vec)
var tvp = sql.TvpFromTable(table);
for (let tvpData of tvp.table_value_param) {
     if (tvpData.sql_type === 12 && tvpData.value) {
          if (Array.isArray(tvpData.value)) {
               for (let v of tvpData.value) {
                    if (v.length > 8000) {
                         tvpData.sql_type = -10;
                        break;
                    }
                }
          } else if (tvpData.value.length > 8000) {
               tvpData.sql_type = -10;
          }
     }
}
// pass tvp to stored procedure input pram
```

Let me know if more info is needed to reproduce the issue.
using 0.8.6

Thanks,
Jeff

**Comment by Jeff-14159** [comment]
UPDATE:  so the above only works if you pass in a single row worth of data to the tvp, if move that one is supplied then you have to check each value within the "value" as it is an array. 
```
for (let tvpData of tvp.table_value_param) {
     if (tvpData.sql_type === 12 && tvpData.value) {
          if (Array.isArray(tvpData.value)) {
               for (let v of tvpData.value) {
                    if (v.length > 8000) {
                         tvpData.sql_type = -10;
                        break;
                    }
                }
          } else if (tvpData.value.length > 8000) {
               tvpData.sql_type = -10;
          }
     }
}
```
but then will get the error 

```{ [Error: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Trying to pass a table-valued parameter with 1 column(s) where the corresponding user-defined table type requires 2 column(s).] sqlstate: '42000', code: 500 }```

so this is not a viable workaround..... need another wat to get tables worth of data to a SP...

Help me Timelord you are my only hope!

Thanks,
Jeff

**Comment by Jeff-14159** [comment]
Update:  found a way to get some things working but not sure what bad things may happen as a result.....

BoundDatum.cpp

void BoundDatum::reserve_w_var_char_array(const size_t max_str_len, const size_t array_len) 
`sql_type = max_str_len > 2000 && max_str_len < 4000 ? SQL_WLONGVARCHAR : SQL_WVARCHAR;`
(why stop at 4000???) to
`sql_type = max_str_len > 2000 ? SQL_WLONGVARCHAR : SQL_WVARCHAR;`

and in

 void BoundDatum::reserve_var_char(const size_t precision)
`sql_type = SQL_VARCHAR;`
to
`sql_type = precision > 8000 ? SQL_WLONGVARCHAR : SQL_VARCHAR;`

**Comment by TimelordUK** [comment]
can you try the version of BoundDatum.cpp - the first change listed above breaks tests in params.js, I have written a new tvp test which binds long strings as below.  If the code still does not work please provide a test that reproduces the issue such as that below.

as checked in below now works it did not before.

Before I release I would appreciate if you could check this fixes issue you are seeing.


```javascript
  test('use tvp simple test type insert test long string 8 * 1024', testDone => {
    const tableName = 'TestTvp'
    let table
    const vec = getVec(8 * 1024)
    const fns = [

      asyncDone => {
        setupSimpleType(tableName, t => {
          table = t
          table.addRowsFromObjects(vec)
          asyncDone()
        })
      },

      asyncDone => {
        const tp = sql.TvpFromTable(table)
        table.rows = []
        theConnection.query('exec insertTestTvp @tvp = ?;', [tp], err => {
          assert.ifError(err)
          asyncDone()
        })
      },

      asyncDone => {
        theConnection.query(`select * from ${tableName}`, (err, res) => {
          assert.ifError(err)
          assert.deepStrictEqual(vec, res)
          asyncDone()
        })
      }
    ]

    async.series(fns, () => {
      testDone()
    })
  })
```

**Comment by Jeff-14159** [comment]
The latest code looks to have resolved all the issues we were having before.

Thanks for your continued support!
Jeff
