### ISSUE TITLE
bulkManager is null when table name contains a space

### ISSUE THREAD

**Issue by Jeff-14159** [TimelordUK/node-sqlserver-v8#136]
If the database name contains a space the bulkManager will return immediately with a null
 
`...Database={'test 123'}...`
`console.log(connection) // seem ok`
`const tableManager = connection.tableMgr();`
` ` ` ` ` tableManager.bind(tableName, (bulkManager, err) => {`
` ` ` ` ` console.log(bulkManager) // is null`
`});`

the connection appear to be ok but not the tableManager /bulkManager

note: other SQL functions (query and stored procedure) work ok with the space

**Comment by TimelordUK** [comment]
this is now fixed on build checked into trunk, it is not yet released.

**Comment by Jeff-14159** [comment]
got latest, built and tested, working good!

Thanks again for maintaining this library.
