### ISSUE TITLE
Unicode is Handled Differently With a Stored Procedure

### ISSUE THREAD

**Issue by Jeff-14159** [TimelordUK/node-sqlserver-v8#137]
Sorry to bother you again but found another bug,

Previously we were using the basic sql.query to insert/update data in a varchar(max) column notably containing Unicode ` \u2013 || \u2014 ` (ms word long - or ` – `) and is appears to be storing things ok and it is somehow maintaining the Unicode character in and out of the database.

We are now using stored procedures to do inserts/update and it is converting the data into 
` â€ `  while we realize that Unicode should probably not be going into the varchar type is there someway it can handle this data the same was regardless if it was passed into sql.query or proc.call also we have not tested the table manager yet...

Note: we are using user defined table types for all input into the SP

Thanks,
Jeff

**Comment by TimelordUK** [comment]
So a JavaScript sequence of Unicode sent to varchar column using query works but if we then use a tvp and stored procedure it does not work with same sequence ?

**Comment by Jeff-14159** [comment]
Yes that is correct with sql.query it goes in as Unicode and comes out as Unicode

While with proc.call it goes in as Unicode then is written to the database as "â€" or some other conversion of A's and e's

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TimelordUK** [comment]
I will have to look at it. When using a tvp one obvious difference is the meta data describing column is used to send to sever what type is being used.  When doing an ad box query the type is guessed by driver.   It may well be the guess is correct when using Unicode and it works as expected.  When told the column is a specific type the code probably just assumes that’s what it is. 

We may be able to add a check in bound datum to see if we do actually have Unicode or not

**Comment by Jeff-14159** [comment]
Update: so it is not Unicode but rather "extended" ASCII that keeps getting converted into Â,Ã,à ....

**Comment by Jeff-14159** [comment]
Update: some code to reproduce the issue let me know if you need anything else....

CREATE TYPE [dbo].[keyValuePairs] AS TABLE(
        [propName] [varchar](200) NULL,
        [value] [varchar](max) NULL
)

CREATE TABLE [dbo].[keyValueTable](
        [propName] [varchar](200) NOT NULL,
        [value] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

create PROCEDURE keyValueProc
         @inputData keyValuePairs readonly	
AS
BEGIN
        SET NOCOUNT ON;
        insert into keyValueTable select * from @inputData
        select * from keyValueTable where propName in (select propName from @inputData)  
END


    const asciiData = [
        {
            propName: 'test1',
            value: 'first time – '
        },
        {
            propName: 'test2',
            value: 'second time â€'
        },
        {
            propName: 'test3',
            value: 'can compound Ã¢â‚¬'
        },
        {
            propName: 'test4',
            value: 'sometimes ÃƒÂ¢\u0000'
        }
    ];
    sql.query(connStr.sqlTesting, 'delete from keyValueTable', [], function() {
        sql.query(connStr.sqlTesting, 'insert keyValueTable values( ? ,? )', ['test0', 'good – '], function(err) {
            sql.query(connStr.sqlTesting, 'select * from keyValueTable where propName = ?', ['test0'], function(err, data) {
                console.log('test basic ascii in and out working: ');
                console.log(data); // good
                sql.open(connStr.sqlTesting, function(err1, connection) {
                    connection.getUserTypeTable('keyValuePairs', function(err2, typeTable) {
                        typeTable.addRowsFromObjects(asciiData);
                        var tvp = sql.TvpFromTable(typeTable);
                        var procedureManager = connection.procedureMgr();
                        procedureManager.callproc('keyValueProc', [tvp], function(err3, results, output) {
                            console.log('test sp with ascii, bad encoding on the way in: ');
                            console.log(results); // bad 
                        });
                    });
                });
            });
        });
    });

**Comment by TimelordUK** [comment]
thanks - this should now be resolved with latest

**Comment by Jeff-14159** [comment]
Got latest release and is working good.

Thanks,
Jeff
