### ISSUE TITLE
Update with 0 rows affected leads to internal error

### ISSUE THREAD

**Issue by killerfurbel** [TimelordUK/node-sqlserver-v8#139]
When updating a table and the update affects 0 rows, the query throws an error.

I'm using a prepared Statement and call that via `.preparedQuery([ ... ], callback)` which will be rejected in reader.js in line 93. 

The error ( `e`) is like the following and procOutputOrMore is undefined.
![image](https://user-images.githubusercontent.com/8451067/76606771-26ebe800-6513-11ea-81b2-c5c1323d8edb.png)

I would expect no error here, since the query was successfully (no syntax error, etc...) and if I want to ensure that rows are affected, I would want to check the affectedRows myself and decide what to do in my code...

Any Ideas? Am I doing it wrong?

Edit: I'm on Version 0.8.10

**Comment by TimelordUK** [comment]
This looks like a bug. I’ll take a look at it and see what is going on.

**Comment by TimelordUK** [comment]
I was able to reproduce this issue and it is fixed on 0.8.11 the current latest release.

**Comment by killerfurbel** [comment]
Thanks for the fast fix 👍

**Comment by killerfurbel** [comment]
Just tested it in my project, works fine now. Thanks again, I will close this now...
