### ISSUE TITLE
Compatibility with the new ODBC Driver

### ISSUE THREAD

**Issue by meet-bhagdev** [TimelordUK/node-sqlserver-v8#14]
Hello @TimelordUK 
Hope you are doing well :) Thanks for all the great work you are doing on this driver. We recently released a new ODBC Driver. Will node-sqlserver-v8 work with Microsoft ODBC Driver 13 for SQL Server?

**Comment by TimelordUK** [comment]
my apologies, I have quite a high work load currently so have not been able to get back to the node JS driver, but thanks and I am enjoying looking after your code very much.  I see the driver is available for preview ?   can i download it and run against VS 2015 to check.

I will ensure the library is compatible.

**Comment by TimelordUK** [comment]
var conn_str = "Driver={ODBC Driver 13 for SQL Server};Server=np:\\\\.\\pipe\\LOCALDB#52B903B5\\tsql\\query;Database={scratch};Trusted_Connection=Yes;";


I have installed the latest ODBC 13 driver and all the tests pass against it - so I would say yes the driver works just fine.
