### ISSUE TITLE
Electron 8.* Binaries

### ISSUE THREAD

**Issue by mtriff** [TimelordUK/node-sqlserver-v8#143]
Electron version 8 was released last month. I've tested building these binaries locally and they appear to compile/run without any additional changes. Can these pre-built binaries be added to `lib\bin\`?

I'm not sure what your philosophy is on pull requests to add binaries. I can submit a pull request with them if you'd accept it.

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8/issues/138

I am trying to think of a way forward with the proliferation of versions. Of course we can add v8 but I’m wondering if we need to ship for example all x86 and x64 and all electron. Some sort of package mix in may be necessary as you see from issue above some are saying package is already too large. 

Not sure what to do I already spend a lot of time supporting this library. 

Any thoughts appreciated.

**Comment by mtriff** [comment]
Looking at the ecosystem of node binary packages, this package is a bit of an anomaly by providing all of the pre-compiled binaries directly in a single release. Most modules either force users to build their own binary using `node-gyp`, or use [prebuild](https://github.com/prebuild/prebuild)/[prebuild-install](https://github.com/prebuild/prebuild-install) or [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) in order to build all the required binaries and upload them separately to the GitHub release. Personally, I think `prebuild` has the more active community and is easier to use.

By using `prebuild`, adding support for a new version is as easy as adding a command-line option to the build tool (you don't need to maintain all the different versions/local build environments). The package is also smaller for individual users because `prebuild-install` only downloads the pre-built binary for their platform, or they can build it directly using `node-gyp` or [`electron-rebuild`](https://www.electronjs.org/docs/tutorial/using-native-node-modules). 

[node-keytar](https://github.com/atom/node-keytar) is an example of a library that uses `prebuild`. 

If you're looking for help in supporting this library, I'm interested in helping out -- whether to implement `prebuild`, address #132, or just to clean up old issues and add documentation. Let me know :)

**Comment by TimelordUK** [comment]
Any help would be hugely appreciated.  If you wish I can add you as a main contributor to check changes in.

I think suggestions are sensible. I added binaries years ago as at the time it was convinient but things have moved on and we should move to a more standard approach if that is what others are doing.

I rely heavily on test suite but even this is not comprehensive enough.  One thing we often trip up on is compatibility with mssql module as many use this driver through that abstraction.

Sounds like prebuild would be a good starting point. I do not know much about it myself but feel free to start on any area you feel can add value.

I appreciate any contributions

**Comment by mtriff** [comment]
Being added as a main contributor would be great. I'll still plan for you to review major (or all?) changes (like implementing prebuild), unless you would prefer not to. 

I have the test suite running cleanly on my machine, and I'll start with implementing prebuild. Looking forward to contributing more to this project!
