### ISSUE TITLE
None of the binaries loaded successfully. Is your node version >= 10.15 ?

### ISSUE THREAD

**Issue by orianachv** [TimelordUK/node-sqlserver-v8#144]
Hi! I have these problem, I update to the last version, and delete my package-lock and install again, but it didn't work! 
"errorMessage": "None of the binaries loaded successfully. Is your node version >= 10.15 ?",
  "trace": [
    "Error: None of the binaries loaded successfully. Is your node version >= 10.15 ?",
    "    at failIfNoBinaryExported (/var/task/node_modules/msnodesqlv8/lib/bootstrap.js:77:15)",
    "    at Object.liveLoad (/var/task/node_modules/msnodesqlv8/lib/bootstrap.js:73:5)",
    "    at Object.<anonymous> (/var/task/node_modules/msnodesqlv8/lib/bootstrap.js:97:12)",
    "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
    "    at Module.load (internal/modules/cjs/loader.js:811:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
    "    at Module.require (internal/modules/cjs/loader.js:848:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at /var/task/node_modules/msnodesqlv8/lib/connection.js:10:21"
  ]
}

**Comment by TimelordUK** [comment]
What version of node are you using.

**Comment by orianachv** [comment]
v12.13.1

**Comment by TimelordUK** [comment]
C:\dev\js\sql\node_modules\msnodesqlv8\samples\javascript
$ nvm use 12.13.1
Now using node v12.13.1 (64-bit)

C:\dev\js\sql\node_modules\msnodesqlv8\samples\javascript
$ node simple-demo.js
rows.length 3301 elapsed 206
rows.length 3301 elapsed 149

C:\dev\js\sql\node_modules\msnodesqlv8\samples\javascript
$ node --version
v12.13.1

**Comment by mtriff** [comment]
As of v1.0.1, binaries are no longer loaded via this method. Upon installing the latest version, `npm` will attempt to download the prebuilt binary for your specific version of `node` and `electron`. If a prebuilt version is not available, it will attempt to build the binary directly using `node-gyp`.

Please open a new issue if you are still having issues with the latest version of this package.
