### ISSUE TITLE
TypeError: p.callNotify is not a function when calling stored procedure

### ISSUE THREAD

**Issue by Jaja0624** [TimelordUK/node-sqlserver-v8#146]
Hi. I'm trying to execute a stored procedure and I am getting error. Could not point to where the source of the error is. Anyone mind providing some guidance?:

    (node:17676) UnhandledPromiseRejectionWarning: TypeError: p.callNotify is not a function
        at C:\Users\jackson.situ\desktop\derp\node_modules\msnodesqlv8\lib\procedure.js:332:11
       at C:\Users\jackson.situ\desktop\derp\node_modules\msnodesqlv8\lib\procedure.js:305:13
        at C:\Users\jackson.situ\desktop\derp\node_modules\msnodesqlv8\lib\procedure.js:194:9
        at runNextTicks (internal/process/task_queues.js:62:5)
        at processImmediate (internal/timers.js:429:9)

And here is my code:

        sql.open(connectionString, function(err, conn) {
            var pm = conn.procedureMgr();
            console.log(pm);
            pm.callproc('dbo.sp_verify', ['2222'], function(err, results, output) {
                if (err) console.log(err);
                console.log(results);
            });
        })

**Comment by frfancha** [comment]
pm.callproc gives that cryptic error message when the parameters are wrongly passed.
much easier to debug if you do:
```
      pm.describe('dbo.sp_verify', (p) => {
        try {
          if (!p.call) {
            return reject("invalid " + proc);
          }
          p.call(['2222'], (callprocError, res, out) => {
            try {
              if (callprocError) {
                return reject(callprocError);
              }
              return resolve({ res, out });
...
```

**Comment by TimelordUK** [comment]
@frfancha - thanks, thats great I will add it to the call itself.

**Comment by TimelordUK** [comment]
this is solved.
