### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by Sennevds** [TimelordUK/node-sqlserver-v8#15]
Hi,

I'm trying to make a standalone app with electron.
If use electron i get following error: A dynamic link library (DLL) initialization routine failed
Without electron everything works fine.
I've already used electron-rebuild but still the same error.
What do i have to do to get it working?

**Comment by Sennevds** [comment]
I've changed bindingdotgyp.old to binding.gyp and try to rebuild with following arguments:
node-gyp rebuild --target=0.37.8 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
but now i have 13 errors on the following:
cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Value>'
note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by Sennevds** [comment]
I've got it working with following arguments --target=0.30.8 --arch=ia32 --dist-url=https://atom.io/download/atom-shell

Is there a possibility to get it working for the latest electron version?

**Comment by TimelordUK** [comment]
sorry I have not reported back sooner.   I assume you mean electron module "A simple command-line interface framework" https://www.npmjs.com/package/electron?

Can you confirm the version of Node you are using?

**Comment by TimelordUK** [comment]
Note when trying to rebuild the cpp code if you want to compile for node 4 remove the underscore for the compile flag      'defines': [ '_NODE_GYP_V4'], in the binding gyp file.

**Comment by Sennevds** [comment]
Hi sorry for the late response i'm usign this: http://electron.atom.io/
Node js is packaged in electron i'm going to check if removing the underscore works

**Comment by TimelordUK** [comment]
hello, is this still an issue?   are there still problems building this package under electron shell?

**Comment by Sennevds** [comment]
Hi sorry for the late answer
Still haven't had time to test it going to test it tomorow.

Senne

Op wo 25 mei 2016 om 13:30 schreef TimelordUK <notifications@github.com>:

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8/issues/23

if you are still interested, the latest version of this driver now supports electron without any need to rebuild.

**Comment by TimelordUK** [comment]
closing this as electron should now work fine.
