### ISSUE TITLE
Crash on passing Decimal/Numeric in table value parameter to Stored Proc

### ISSUE THREAD

**Issue by milenkovyua** [TimelordUK/node-sqlserver-v8#154]
I am having issue on passing table value parameter having a Decimal/Numeric column.

Here is the code I am using to call stored procedure having a TVP param:

```
    function callProcedureSimpleWithDecimalTVPFail(pool) {
        const tvpParam = tableTypes.get('testschema.withDecimalTypeTT');
        tvpParam.rows.add(30.1); // percentage
        tvpParam.rows.add(27.2); // percentage
        const request = pool.request();
        request.input('tvpParam', /*sql.TVP,*/ tvpParam);
        return request.execute('[testschema].[simple.withDecimalTVP]');
    },
```
After calling `request.execute` the driver crash, causing to stop the running node.js instance.

This is the repo I have prepared to reproduce the bug:
https://github.com/milenkovyua/msnodesqlv8test
After setting the correct environment variables, this will run a few test queries to the database. Before and after every test it will console.log the test name and the status (start/success/fail). Pay attention the function `callProcedureSimpleWithDecimalTVPFail` is logged with start, but never get it to either success or fail. The driver crash and node.js process instance is stopped immediately.

**Comment by TimelordUK** [comment]
thanks for raising issue and providing a sample - I am looking at this and will report back shortly.

**Comment by TimelordUK** [comment]
This should be fixed in latest version.

**Comment by milenkovyua** [comment]
Thanks for the quick response @TimelordUK . I tested it and it's working now. There is one more bug I just noticed, which occurs when passing DateTime values in tvp param, but I will rise separate issue for that.

Marking this one as closed.
