### ISSUE TITLE
Error on passing DateTime2 in table value parameter to Stored Proc

### ISSUE THREAD

**Issue by milenkovyua** [TimelordUK/node-sqlserver-v8#155]
I am having issue on passing table value parameter having a DateTime2 column.

Here is the code I am using to call stored procedure having a TVP param:
```
    function callProcedureSimpleWithDateTimeTVPFail(pool) {
        const tvpParam = tableTypes.get('testschema.withDateTimeTypeTT');
        tvpParam.rows.add(new Date('2020-05-07')); // date
        tvpParam.rows.add(new Date('2020-05-08')); // date
        const request = pool.request();
        request.input('tvpParam', /*sql.TVP,*/ tvpParam);
        return request.execute('[testschema].[simple.withDateTimeTVP]');
    }
```
After a little bit of debugging, I managed to get to the function `DateTime2 (p, scale, fraction)`, inside lib/user.js file, which is throwing the error. It turned out that the parameter p is actually array, when we have more than one row in the passed tvp param. Here is the modification I used to do, in order to solve that localy:
```
    function DateTime2 (p, scale, fraction) {
      if (!fraction && p) {
        if (Array.isArray(p)) {
          if(p.length > 0) {
            fraction = p[0].getUTCMilliseconds()
          } else {
            fraction = 0
          }
        } else {
          fraction = p.getUTCMilliseconds()
        }
      }
      return {
        sql_type: SQL_TYPE_TIMESTAMP,
        value: p,
        fraction: fraction,
        scale: scale > 0
          ? scale
          : 0
      }
    }
```

This is the repo I have prepared to reproduce the bug:
https://github.com/milenkovyua/msnodesqlv8test

After setting the correct environment variables, this will run a few test queries to the database. Before and after every test it will console.log the test name and the status (start/success/fail). Pay attention to the function callProcedureSimpleWithDateTimeTVPFail, which is logged with `fail`.

**Comment by TimelordUK** [comment]
thanks for the fix - I have merged that and released in latest version.

**Comment by milenkovyua** [comment]
Thanks for the quick response, @TimelordUK . I tested it and everything is working fine now. Closing the issue now.
