### ISSUE TITLE
Only executes first half of my stored procedure

### ISSUE THREAD

**Issue by sydneyvert** [TimelordUK/node-sqlserver-v8#157]
Hi,

When I run my stored procedure in SSMS it executes correctly. My procedure contains an insert, update and delete. When I use the package to execute my proc it only executes the insert and update and then finishes.

To investigate this I took out the update and the insert and delete would execute correctly. Therefore to see if it was the update that was a problem I did an insert and delete, then another insert and update and it only executed the insert and delete. 

To check it wasn't a timeout issue I have added delays in between each part of the proc and the same thing happens. It still only executes the first two parts of my procedure at any point.

I have tried executing both with sql.quary and sql.open with pm.callproc and both only execute 2 things. I have also tried with a seperate dummy table and only two things will be executed then also.

Is this an issue anyone has faced before? And is there any settings I can change in order to maybe resolve this?

This is how I call my proc currently:

```
sql.default.open(connectionString, function (error, conn) {
    var pm = conn.procedureMgr();
    pm.setTimeout(60);
    pm.callproc('myProc', function (err, results, output) {
        console.log('results:' + results);
        console.log('error:' + err);
        console.log('output: ' + output);
    });
});
```

Thanks

**Comment by TimelordUK** [comment]
Hello,

I have written a little test below 

- note the stored proc manager can call back multiple times with more than one statement.  See the check for output vector below ie. if you have not received the return code from procedure, more callbacks are due.

Can you add a return such as below and check again once proc completes.

If you still see an example, we will need to try and reproduce it by enhacing the example below as this is working OK currently.  I added this test into sproc.js under unit.tests


```javascript
  test('test sproc with insert, update and delete', testDone => {
    const spName = 'test_sp_multi_statement'

    const def = `alter PROCEDURE <name>(
@p1 INT,
@p2 nvarchar(15),
@p3 nvarchar(256)

)AS
BEGIN
    insert into TestMultiStatement (BusinessEntityID, NationalIDNumber, LoginID) values (@p1, @p2, @p3)
    
    update TestMultiStatement set BusinessEntityID = 100 where BusinessEntityID = @p1
    
    delete from TestMultiStatement where BusinessEntityID = 100 
END
`
    const fns = [
      asyncDone => {
        theConnection.queryRaw('DROP TABLE TestMultiStatement', () => {
          asyncDone()
        })
      },

      asyncDone => {
        theConnection.queryRaw(`CREATE TABLE TestMultiStatement (
          [BusinessEntityID] [int] NOT NULL,
          [NationalIDNumber] [nvarchar](15) NOT NULL,
          [LoginID] [nvarchar](256) NOT NULL,
          )`,
        e => {
          assert.ifError(e)
          asyncDone()
        })
      },

      asyncDone => {
        procedureHelper.createProcedure(spName, def, () => {
          asyncDone()
        })
      },

      asyncDone => {
        const pm = theConnection.procedureMgr()
        pm.get(spName, proc => {
          const count = pm.getCount()
          assert.strictEqual(count, 1)
          proc.call([1, 'NI123456', 'Programmer01'], (err, results, output, more) => {
            assert.ifError(err)
            if (!output) return
            asyncDone()
          })
        })
      }
    ]

    async.series(fns, () => {
      testDone()
    })
  })
```

**Comment by sydneyvert** [comment]
Thanks for getting back to me. 

I am not sure how to add this into my code without writing a full testing script. I have added in the following:
```
sql.open(connectionString, (error, conn) => {
    assert(error === false)
    const pm = conn.procedureMgr();
    pm.setTimeout(60);
    pm.get('myProc', proc => {
        const count = pm.getCount()
        assert.strictEqual(count, 1)
        proc.call([], (err, results, output, more) => {
            assert.ifError(err)
            if (!output) return 'no output';
        });
    });
});
```
It now only executes the initial insert using this method.
I do not get anything out from the assertions either.

It may be worth noting that my insert and update are slightly more complex than a simple insert and update as they check for things also.

**Comment by TimelordUK** [comment]
can you add a console debug for example - if you have many selects /
updates etc the stored procedure should call back more than once - are you
setting a breakpoint and holding code?  It needs to run until you
see output vector set.

you can add debug trace to procedure which may help -

const qp = proc.call([], (err, results, output, more) => {

            console.log('output ` + output
            assert.ifError(err)
            if (!output) return 'no output';
        });

qp.on('info', (i) => {
console.log(`info ${i}`)

})
BEGIN
raiserror('a print in proc message',0,0) with nowait;
select LEN(@param) as len;
END


sql.open(connectionString, (error, conn) => {
    assert(error === false)
    const pm = conn.procedureMgr();
    pm.setTimeout(60);
    pm.get('myProc', proc => {
        const count = pm.getCount()
        assert.strictEqual(count, 1)
        proc.call([], (err, results, output, more) => {

            console.log('output ` + output
            assert.ifError(err)
            if (!output) return 'no output';
        });
    });
});

**Comment by sydneyvert** [comment]
So in my proc I have used try catch and in the catch block it raises errors. Also for testing I have added in a SELECT statement for insert complete, update complete and delete complete after each of the respective parts. I have added in to log everything to the console and I get:
output: 0
results:
more: undefined
error: null

It has executed the insert part of my proc, however. It looks like it has stopped after this.

**Comment by TimelordUK** [comment]
if you run that procedure with the selects etc added in SSMS, you do not
have to post exact results but what do you see in terms of rows affected.
It is possible the driver is assuming no more processing is needed but
without knowing exactly what it is doing it is impossible for me to know.
Ideally the problem needs to be reduced to something simple that can be
reproduced.

**Comment by sydneyvert** [comment]
Yeah of course. So if I run in SSMS these are the results:
![ssmsResults](https://user-images.githubusercontent.com/40839435/84131235-327c7b80-aa3c-11ea-959c-fa268922bfaa.PNG)

It also might make a difference - something I forgot to mention - that the insert and update are invoked by calling another stored procedure that performs this as well as checking the values are allowed in our table. However nothing is returned when I call the procedures.

Below I have added my procedure (there are some placeholders where I have removed anything sensitive):
```
BEGIN

    BEGIN TRY

         --insert new values

        DECLARE @Results TABLE (CorrelationId VARCHAR(100),
	    PositionId INT,
	    LastChangeBitmask BIGINT,
	    ChangeBitmask BIGINT);

        DECLARE @PositionTable <TableTemplate>
        INSERT @PositionTable (
              <columns>)
        VALUES                                                                                                                                                                                                                                                                                                                                                                                      
              (
		<values> );

        INSERT INTO @Results (
            CorrelationId,
            PositionId,
            LastChangeBitmask,
            ChangeBitmask )
        EXECUTE [<otherStoredProc>] @PositionTable;

        -- assign PositionId to use for deletion stage

        DECLARE @TestPositionId INT;
        SET @TestPositionId = (SELECT [PositionId] From @Results);

	SELECT 'Insert Complete'

        WAITFOR DELAY '000:00:20';

        --soft delete

	    DECLARE @ResultsSD TABLE (CorrelationIdSD VARCHAR(100),
	    PositionIdSD INT,
	    LastChangeBitmaskSD BIGINT,
	    ChangeBitmaskSD BIGINT);

        DECLARE @PositionTableSD <TableTemplate>
        INSERT @PositionTableSD (
              <columns> )
        VALUES                                                                                                                                                                                                                                                                                                                                                                                      
              (
		<values> );

	INSERT INTO @ResultsSD (
        CorrelationIdSD,
        PositionIdSD,
        LastChangeBitmaskSD,
        ChangeBitmaskSD )
        EXECUTE [<otherStoredProc>] @PositionTableSD;

	SELECT 'Update Complete';

	--for test

        SELECT [CorrelationId], 
           [PositionId], 
           [LastChangeBitmask], 
           [ChangeBitmask],
           [CorrelationIdSD], 
           [PositionIdSD], 
           [LastChangeBitmaskSD], 
           [ChangeBitmaskSD]
        FROM @Results r
        INNER JOIN @ResultsSD s
        ON r.PositionId = s.PositionIdSD;

        WAITFOR DELAY '000:00:20'

        --hard delete

        DELETE FROM <tableWhereChangesWereMade> WHERE PositionId = @TestPositionId;

	SELECT 'Delete Complete';

	--use in the test

	EXECUTE <getPositionsProc> @PositionId = @TestPositionId;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
        BEGIN
            ROLLBACK TRAN;
        END;

        DECLARE @Error_Number   INT
                , @Error_Severity INT
                , @Error_Line            INT
                , @Error_State           INT
                , @Error_Message  NVARCHAR(2048)
                , @Error_Procedure NVARCHAR(200);
        SELECT @Error_Number = ERROR_NUMBER()
               , @Error_Severity = ERROR_SEVERITY()
               , @Error_Line = ERROR_LINE()
               , @Error_State = ERROR_STATE()
               , @Error_Procedure = ISNULL(DB_NAME() + '.' + ERROR_PROCEDURE(), '-');
        SELECT @Error_Message =  N'Error %d, Level %d, State %d, Procedure %s, Line %d, ' + CHAR(10) + CHAR(13) + 'Message: ' +  ERROR_MESSAGE();
        RAISERROR
            (
            @Error_Message
            , @Error_Severity
            , 1
            , @Error_Number
            , @Error_Severity
            , @Error_State
            , @Error_Procedure
            , @Error_Line
            );
    END CATCH;

END;
```

Thanks again for your help.

**Comment by TimelordUK** [comment]
so I have tried to reproduce this issue with no luck I am afraid - I created a procedure similar to above.  It has already taken couple hours to get this far and below simply runs as I would expect.

Unless I can have an actual example that shows the problem I am just guessing and cannot proceed.

```javascript
       console.log('about to call')
        procedure.call(['a user', 'newuser1', 55, 99000, 98765432109876, new Date(2010, 1, 10)], (err, res, output, more) => {
          assert.ifError(err)
          all.push(res)
          if (!output) return
          assert.strictEqual(2, res.length)
          assert.deepStrictEqual(expected, all)
          asyncDone()
        })
```

and I get the expected results i.e. array of 3

```javascript
  const expected = [
      [
        {
          Column0: 'Insert Complete'
        }
      ],
      [
        {
          Column0: 'Insert 2 Complete'
        }
      ],
      [
        {
          description: 'a user',
          username: 'newuser1',
          age: 55,
          salary: 99000,
          code: 98765432109876,
          start_date: new Date(2010, 1, 10)
        },
        {
          description: 'a user',
          username: 'newuser1',
          age: 55,
          salary: 99000,
          code: 98765432109876,
          start_date: new Date(2010, 1, 10)
        }
      ]
    ]
```


```sql
CREATE TYPE TestTvpType  AS TABLE (description varchar(max), username nvarchar(30), age int, salary real, code numeric(18,3), start_date datetime2)
```

```sql
  create PROCEDURE callProcedureFromProcedure
(
      @description varchar(max),
      @username nvarchar(30),
      @age int,
      @salary real,
      @code numeric(18,3),
      @start_date datetime2
)
AS
BEGIN
 set nocount on

 declare @TmpTvpTable TestTvpType;
 INSERT @TmpTvpTable
 (
   [description],
   [username],
   [age],
   [salary],
   [code],
   [start_date]
 )
 values
(
   @description,
   @username,
   @age,
   @salary,
   @code,
   @start_date
 )
 
execute InsertTestTvp @TmpTvpTable;

SELECT 'Insert Complete';

WAITFOR DELAY '000:00:02';

execute InsertTestTvp @TmpTvpTable;

SELECT 'Insert 2 Complete';

 SELECT 
 [description],
 [username],
 [age],
 [salary],
 [code],
 [start_date]
FROM TestTvp;

END
```

which calls

```sql
create PROCEDURE InsertTestTvp 
@tvp TestTvpType READONLY
AS
BEGIN
 set nocount on
 INSERT INTO TestTvp
(
   [description],
   [username],
   [age],
   [salary],
   [code],
   [start_date]
 )
 SELECT 
 [description],
 [username],
 [age],
 [salary],
 [code],
 [start_date]
n FROM @tvp tvp
END
```

**Comment by sydneyvert** [comment]
Thanks for your help. I have reached out to security to see if they will allow me to share with you the code. It is quite a complex proc so difficult to explain.

**Comment by TimelordUK** [comment]
I do appreciate the enquiry even then from my perspective it would likely take a long tme to strip that down into something i can see the problem.   I am sorry but realistically the only way it could be solved is to slowly strip your procedure away piece by piece and produce the minimal unit where problem is still seen.  Else even if you are permitted to share the code I will be faced with quite a challenge doing this myself.  The procedure you are calling for example - is it possible in test to strip it back to bare bones or even a shell - does that mean the parent then proceeds.   Its not related to the set no count by any chance which i note i added at top of my test ...

**Comment by sydneyvert** [comment]
Okay that makes sense. I will try strip my proc back and if I find the part that causes this I will let you know.

**Comment by TimelordUK** [comment]
this may be connected to https://github.com/TimelordUK/node-sqlserver-v8/issues/165

hence may want to try latest version - the driver did have a problem with info messages being returned and could cause the query to compelte too early which is fixed in 1.1.8

**Comment by frfancha** [comment]
@sydneyvert perhaps already done, but I don't see it mentioned in the thread, so here it is:
-make sure you have included the SET NOCOUNT ON; statement in the beginning of your stored proc
-make sure you don't use any 'print' statement in your procedure(s). Stored procedures including print statements are a nightmare to call correctly remotely, even from C#

**Comment by TimelordUK** [comment]
i believe this issue is solved, so closing.
