### ISSUE TITLE
Connection close callback hangs occasionally

### ISSUE THREAD

**Issue by NoelAbrahams** [TimelordUK/node-sqlserver-v8#16]
Hi,

**Version**:  0.1.35, node version 4.4.3

Firstly thanks for the work on this.

We've recently looked at replacing the original node-sqlserver with your `v8` version and have run into a small issue. The code we have for connecting to SQL Server looks like this:

```js
new Promise(function (resolve, reject) {

    // Open the connection
    nodesqlv8.open('connectionString', function (error, con) {

        // Execute the query
        con.query('SELECT * FROM foo.bar', undefined, function (error, results, hasMore) {

            // Close the connection.
            con.close(function (closeError) {

                // Resolve result
                resolve(results);
            });
        });
    });
});

```

This bit of code was working correctly in the original node-sqlserver, but in the `v8` version it hangs occasionally. Stepping into the code I see that the `resolve(results)` line gets executed, but control flow never reaches the outer world. I have not been able to reproduce this consistently, but have found that the following two workarounds get rid of the hang:

**Workaround 1:** Add a `setTimeout`
```js
  // Execute the query
  con.query('SELECT * FROM foo.bar', undefined, function (error, results, hasMore) {

            // Close the connection.
            con.close(function (closeError) {

                // Resolve with setTimeout
                setTimeout(function () { resolve(results); });
            });
});
```

**Workaround 2:** Do not wait for the connection close callback

```js
        // Execute the query
        con.query('SELECT * FROM foo.bar', undefined, function (error, results, hasMore) {

            // Resolve
            resolve(results);

            // Close the connection.
            con.close(function () { });
        });
```

This is a bit strange and is probably related to #5.

**Comment by TimelordUK** [comment]
yes, your right this is similar to issues I have already seen.  I will look into this, thanks for bringing it to my attention.  Ill report back when I have a fix.

**Comment by TimelordUK** [comment]
this should hopefully be fixed now in latest version

**Comment by NoelAbrahams** [comment]
@TimelordUK, I've upgraded to version 0.1.39 and the problem appears to have been resolved.

Thanks!
