### ISSUE TITLE
Prepare statement not allowed with connection pool?

### ISSUE THREAD

**Issue by herrdragon** [TimelordUK/node-sqlserver-v8#162]
I am using sql.open(connString...) with prepare statements and is workin fine, but after a few hours of inactivity, sql-server closes my connection. 
I wanted to use "pool = new sql.Pool(options)", but now when I try to use pool.prepare() I get an error pool.prepare is not a function.
How to use prepared statements with a connection pool?
Thank you.

**Comment by herrdragon** [comment]
Does anyone has a suggestion about how to accomplish this?

**Comment by TimelordUK** [comment]
The simple answer is no, the Pool does not support a prepared statement.  The statement belongs to a connection and once allocated to that connection it must always be used with the same connection - this is somewhat counter to a pool where any old connection is taken that is available.  From what you were implying, it is fact the connection will eventually disconnect on idle.  I would have thought the easiest thing is to simply issue a keep alive during times of idle to ensure this does not occur.

**Comment by herrdragon** [comment]
Thank you for your answer.  But isn't it dangerous to have connections without prepare statements? How would you prevent sql injection with pools? and how can I implement the keep alive, something similar like the pool is already doing?
Thanks

**Comment by TimelordUK** [comment]
The Pool I guess could be enhanced such that is a statement is prepared via the pool every connection within pool is prepared.  So connection 1 ... n would all be independently prepared such that regardless of which one is used by pool it would work.  Of course depending on number of connections the resources on server would hence multiply - I believe the statement is really under covers a stored procedure that is compiled hence you would see n x procs server side.

**Comment by herrdragon** [comment]
Ok, I see what you are saying.  So it will be better to just keep a simple query in a timeInterval() to keep the connection alive.
