### ISSUE TITLE
Bulk Insert Exception Crash

### ISSUE THREAD

**Issue by bsEmo** [TimelordUK/node-sqlserver-v8#164]
**Which feature the issue appears in:** 
Bulk insert

**Under what circumstances the issue appears:** 
Invalid date is passed to column defined as a date (datetime, datetime2 included)

**What is desired behavior:**
Error would be catchable by awaiting the call to .bulk()

**What is breaking:**
Application crash even when await .bulk() call is wrapped in try/catch

**What is the impact (things like loss or corruption of data, compromizing security, disruption of service etc.)**
Should be able to catch and handle the exception instead of an unhandled exception causing application crash.

**Any code that will be helpful to reproduce the issue:**

```
... create connection
... create table instance
table.columns.add('date column', TYPES.datetime, { nullable: false })

table.rows.add(...['not a date'])

try {
await connection.request().bulk(table)
} catch (ex) {
... handle exception
}

```

**Additional Notes:**
error message reads: 'Invalid date value passed to bulk rows'
looks to be coming from table.js _makeBulk()

**Comment by TimelordUK** [comment]
this does not seem to have anything to do with msnodesqlv8 - you are calling from mssql and it looks like the error is thrown from a function invoked by  setImmediate(callback).  Hence you cannot catch the error and node will terminate.  I am pretty sure I have the exact same type of problem in msnodesqlv8 but in this particular case the termination is produced from within mssql as far as I can see.

```javascript
      case TYPES.DateTime2:
        for (let j = 0; j < this.rows.length; j++) {
          const dateValue = this.rows[j][i]
          if (typeof dateValue === 'string' || typeof dateValue === 'number') {
            const date = new Date(dateValue)
            if (isNaN(date.getDate())) {
              throw new TypeError('Invalid date value passed to bulk rows')
            }
            this.rows[j][i] = date
          }
        }
        break
```

```javascript
_bulk (table, options, callback) {
    if (!this.parent) {
      return setImmediate(callback, new RequestError('No connection is specified for that request.', 'ENOCONN'))
    }

    if (!this.parent.connected) {
      return setImmediate(callback, new ConnectionError('Connection is closed.', 'ECONNCLOSED'))
    }

    this.canceled = false
    setImmediate(callback)
  }
```

**Comment by TimelordUK** [comment]
Closing I don’t think this is related to our library.
