### ISSUE TITLE
None of the binaries loaded succesully. Is your node version either 0.12.x or 4.1.x

### ISSUE THREAD

**Issue by NoelAbrahams** [TimelordUK/node-sqlserver-v8#17]
Hi,

**Version**: 0.1.35

We'd like to try out Node version 6.0 (6.1.0 to be exact), but node-sqlserver-v8 load fails with the exception above. The [bin directory](../tree/master/lib/bin) appears to have builds only for a couple of versions.

Is it possible to release a build that is compatible with later version of Node?

**Comment by TimelordUK** [comment]
I will take a look at this and get back to you shortly.  Hopefully the API is similar, it may just require a re-compilation.

**Comment by NoelAbrahams** [comment]
If there is a build available I'm happy to try it out and see if it makes a difference in Visual Studio.

**Comment by TimelordUK** [comment]
I have built the library for node 6.1.0 and should be available in latest npm version. Please give it a shot and see how it goes in VS.

**Comment by NoelAbrahams** [comment]
@TimelordUK, is there a way to make `node-sqlserver-v8` independent of the node version? Node JS development is currently iterating quite fast. And we'd like the flexibility to pick any of the newer versions > 4 (for example 6.2.1).

Part of the reason is that there are other components that we depend on, which either work or don't work with certain versions. So being able to choose any of the newer versions would be very helpful.

Thanks.

**Comment by TimelordUK** [comment]
The latest version of library should be compatible with node 4 5 and 6.  For every major version the cpp needs to be rebuilt. For minor node version updates the driver should work fine.  Most of the problems come about with major version changes where the code has to be rebuilt

Let me know if the latest version is not working currently on newer versions I have tested it against versions 4 5 and 6.

**Comment by NoelAbrahams** [comment]
I see. I didn't realise that the minor versions did not matter. I'll try it out and let you know. Thanks.

**Comment by aubonpain** [comment]
msnodesqlv8 is at 0.2.8. is still having trouble with node version 6.5.0. It fails with: "Error: None of the binaries loaded succesully. Is your node version either 0.12.x or 4.1.x".

**Comment by TimelordUK** [comment]
can you try latest version 0.2.9

**Comment by TimelordUK** [comment]
ok i patched the build with latest version, please try again

**Comment by aubonpain** [comment]
Hmm, I'm still getting the same 'None of the binaries loaded successfully. Is your node version either 0.12.x or 4.1.x'. I cleared the cache (npm cache clean msnodesqlv8) and reinstalled globally. This is my package.json in case that helps w/ seeing whether there are non-explicit dependency errors:

```
"engines": {
    "node": ">=6.5.0"
  },
  "dependencies": {
    "chai": "~1.9.1",
    "config": "~1.6.0",
    "format-json": "~1.0.3",
    "grunt": "~0.4.5",
    "grunt-eslint": ">=2.0.0",
    "grunt-githooks": "~0.3.1",
    "grunt-mocha-test": "^0.12.2",
    "load-grunt-tasks": "^1.0.0",
    "lodash": "~2.4.1",
    "mocha": "~2.0.1",
    "mocha-jenkins-reporter": "0.1.9",
    "requirejs": "~2.1.14",
    "superagent": "~0.20.0",
    "mssql":">=3.0.0",
    "msnodesqlv8": "~0.1.35"
  },

```

**Comment by TimelordUK** [comment]
can you try Node 6.6.0, this is the version I have built against.

**Comment by TimelordUK** [comment]
the error raised in sqlserver.native.js (which I need to correct, versions
are out of date)

is as below - are you definitely running 0.2.9

throw new Error('None of the binaries loaded successfully. Is your
node version either >= 0.12.7 or >= 4.2.x or >= 5.1.1 or >= 6.1.0'

**Comment by aubonpain** [comment]
That is so weird - what you're saying makes sense and I should see the new error message, but after I installed node 6.6.0, and reinstalled using npm install -g msnodesqlv8 again it shows:

![image](https://cloud.githubusercontent.com/assets/557641/18690428/0bd097a0-7f5c-11e6-874c-a1b3b79c9e60.png)

Which is good. But, when I run my tests:

![image](https://cloud.githubusercontent.com/assets/557641/18690444/1af21178-7f5c-11e6-8336-a2ba36e21577.png)

Which is not what you've got in your exception message. Do you think something isn't getting pushed with the 0.2.9 build? I even did a blanket npm install -g so all the latest dependencies from package.json would reinstall, but still getting the same error...

**Comment by TimelordUK** [comment]
is the module installed in C:\Program Files\nodejs\node_modules\npm\node_modules

if that is the case, can you find the  lib\sqlserver.native.js file and change the error to ensure this is the one your loading.  Or possibly rename the actual msnodesqlv8 folder temporarily and see if you still load an old version from somewhere else.

I will have to check the documents I assume it is possible to find out from node where a module has loaded from which would help us.

**Comment by aubonpain** [comment]
Okay, it worked. I basically had to blow away my entire node_modules, redo npm install, then my code ran without errors. Thank you for the fix!
