### ISSUE TITLE
Swedish characters from javascript to mssql - appear as question marks in db table?

### ISSUE THREAD

**Issue by pythonIsMySnake** [TimelordUK/node-sqlserver-v8#170]
Im trying to insert values to my mssql table and some of the values includes the swedish characters "åäö". Anyhow when I do this they appear as "??????". Each special character appear as two question marks ("ö" -> "??").

Some details:

MyCode:

var sql = require('msnodesqlv8');
const connectionString = "server=host;Database=MyDb;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}"
q = "Insert into [MyDb].[dbo].[MyTable] (testCol) values ('ö')"

sql.query(connectionString, q, (err,data) => {
      if (err) {
           console.log(err);
      }
      else {
           console.log('Imported row to table.');
      }
})

*The columns in the db table that will retrieve values containing "åäö" is defined as datatype nvarchar(50)

*console.log('ö') prints ö in console as expected

*I have also trid with N'ö' in variable q and these characters (within the double quotes) appear in db table "ￃﾶ"

*I have tried all conversions i can think about in js (for example utf-8, latin1, etc...)

*Collation in db is Finnish_Swedish_CI_AS

*I have tried to read out swedish chrs from another table and it works fine through the package msnodesqlv8

The problem to me seems to be somewhere when sending the query from js (everything looks fine here), through package msnodesqlv8 and when mssql shall interpret the values. Im very glad if someone can help me.

**Comment by TimelordUK** [comment]
ok thanks we will take a look and report back shortly

**Comment by pythonIsMySnake** [comment]
Many thanks. Appreciate it.

**Comment by TimelordUK** [comment]
OK well I do not doubt you are seeing a problem however first thing I always try to do is write a test to show the issue.  So I added this test which seems to pass - running windows x64 driver 2.04 (latest msnodeslv8) and connection string as below.

in management studio i then 

```sql
select * from [dbo].[test_swedish_insert]
```
id	text_col
1	åäöåäöåäöåäöåäö

se conn_str Driver={ODBC Driver 17 for SQL Server}; database=node; Server=; UID=linux; PWD=linux

```cmd
 √ query containing Swedish "åäö"
 √ insert/query containing Swedish "åäö"
```

```js
test('insert/query containing Swedish "åäö"', testDone => {
    const STR_LEN = 5
    const str = 'åäö'.repeat(STR_LEN)
    const name = 'test_swedish_insert'
    testBoilerPlate(name, { text_col: 'nvarchar(50)' },
      done => {
        theConnection.query(`INSERT INTO ${name} (text_col) VALUES (?)`, [str], e => {
          assert.ifError(e, 'Error inserting large string')
          done()
        })
      },

      done => {
        theConnection.query(`SELECT text_col FROM ${name}`, (e, r) => {
          assert.ifError(e)
          assert(r[0].text_col === str, 'bad insert')
          done()
        })
      },
      () => {
        testDone()
      })
  })
```

**Comment by TimelordUK** [comment]
looking at your example again I have not added a test where these characters are part of SQL query itself - possibly that explains the difference.  I shall try that shortly.

**Comment by TimelordUK** [comment]
this was indeed a bug - we were binding params as 16 bit wide strings but query itself as utf8

this should be fixed in 2.0.5

**Comment by pythonIsMySnake** [comment]
Hi Timelord. Yes we got it to work when had the values with åäö as question marks in the query and giving them separately in a list. Many thanks for taking the time to look at this.

**Comment by TimelordUK** [comment]
Ok thanks closing this issue
