### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by simlina** [TimelordUK/node-sqlserver-v8#171]
Hi, I use node v12.18.3 on a Windows machine and I need to connect to an MS-SQL Server using Windows authentication (trustedConnection = true). So I tried to use this package but could not get it running. I installed mssql 6.2.1 (npm install mssql) and also msnodesqlv8 2.0.5 (npm install msnodesqlv8) and at the first glance the installation seems to work fine. However, when I try to use the msnodesqlv8 package, then I get the error 

**"Module did not self-register".** 

So something is hindering the execution of the module. This is my code:
```javascript
var mssql = require('mssql/msnodesqlv8');
const config = {
             driver: 'msnodesqlv8',
             server: 'myserver', 
             database: 'mydb',
            options: {
                trustedConnection: true
          }
};
let pool = mssql.connect(config);
```

The error happens already in the first line.
Same problem if I use `var mssql = require('msnodesqlv8');`

I tried several things like deleting the node_modules folder and typing npm install,  typing npm upgrade etc. but it did not help.
Do you know what could be wrong?

**Comment by TimelordUK** [comment]
does not seem like correct binary is deployed in build\Release

the javascript installs via NPM and this needs to download correct binary c++ module for your system. I have just tried node 12.13.1 on x64 windows and it works fine

you can try installing prebuild-install and running in verbose mode as below

note you should see msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz

being deployed to build\Release folder as below

```cmd
02/09/2020  15:53    <DIR>          .
02/09/2020  15:53    <DIR>          ..
29/08/2020  15:11         1,740,800 sqlserverv8.node
               1 File(s)      1,740,800 bytes
               2 Dir(s)  23,659,827,200 bytes free

C:\Users\\dev\js\published\node_modules\msnodesqlv8\build\Release
```

```cmd
$ prebuild-install --verbose
prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ C:\Users\\AppData\Roaming\npm-cache\_prebuilds\20acb4-msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\\AppData\Roaming\npm-cache\_prebuilds\20acb4-msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\Users\\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!

Stephen@DESKTOP-9RLN5E4 C:\Users\\dev\js\published\node_modules\msnodesqlv8
```

**Comment by TimelordUK** [comment]
just repeated using 12.18.3 seems to be fine

```cmd
@ C:\Users\\dev\js\published\node_modules\msnodesqlv8
$ ..\.bin\prebuild-install --verbose msnodesqlv8
prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ C:\Users\\AppData\Roaming\npm-cache\_prebuilds\20acb4-msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\\AppData\Roaming\npm-cache\_prebuilds\20acb4-msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\Users\\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!

@ C:\Users\\dev\js\published\node_modules\msnodesqlv8
$ node --version
v12.18.3

@ C:\Users\\dev\js\published\node_modules\msnodesqlv8
$ cd ../../

@ C:\Users\\dev\js\published
$ cd samples

@ C:\Users\\dev\js\published\samples
$ cd javascript

@ C:\Users\\dev\js\published\samples\javascript
$ node streaming.js
submitted SELECT * FROM syscomments elapsed 1 ms
```

**Comment by simlina** [comment]
I followed your instructions:

```
\node_modules\msnodesqlv8> ..\.bin\prebuild-install --verbose msnodesqlv8
prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ C:\Users\mobsip\AppData\Roaming\npm-cache\_prebuilds\20acb4-msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\mobsip\AppData\Roaming\npm-cache\_prebuilds\20acb4-msnodesqlv8-v2.0.5-node-v72-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\ta-api-tests\PartnerAPI_RegressionTests\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\ta-api-tests\PartnerAPI_RegressionTests\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```
But I still get the same error when I run the require statement for msnodesqlv8:
   "Module did not self-register"

**Comment by TimelordUK** [comment]
Are you definitely picking up version of msnodesqlv8 from installed folder. If you delete it totally from node modules you get a different error I assume. 

Forget mssql create a test folder install only msnodesv8 and in top folder create index js file with the require statement.  What then happens.

**Comment by simlina** [comment]
What I did not mention above, is that I am trying to run the code from within the API-Testing tool vREST NG in which one can write custom utility mehtods in js and which can be extended with npm packages. There I get the  "Module did not self-register" error.

I now followed your instructions and run the following code outside of the API Testing tool (just in a js file run with node in Windows console) and it worked.
```
const sql = require("msnodesqlv8");
 
const connectionString = "server=xxxx;Database=xxxx;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";
const query = "select xxx";
 
sql.query(connectionString, query, (err, rows) => {
    console.log(rows);
});
```

So the problem is not the msnodesqlv8 itself but its integration in the vREST NG tool. I think the native modules need to be rebuild for the vREST NG application in order to use them there. I will contact vREST NG support to get help. 

Thank you for your support.

**Comment by simlina** [comment]
Ok, so the support team of the vREST NG clarified this for me. They use ElectronJS in the vREST NG Application. So for any native module, they need to rebuild it for electron using electron-rebuild or more specifically node-gyp. They just did that for msnodesqlv8 and delivered the rebuilt binary to me which works fine in vREST NG. Sorry for bothering you here.
