### ISSUE TITLE
Question: BigInt Stored Proc Parameter

### ISSUE THREAD

**Issue by bsEmo** [TimelordUK/node-sqlserver-v8#179]
What is the best practice for sending a parameter to a stored procedure of type BIGINT? Thus far I've only had success sending as a string, making the stored proc parameter a VARCHAR, and then casting inside the stored proc. Hoping there is a better way. 

If I send as a string and the parameter type is anything numeric, parseInt() will be called on the string causing a loss of precision.

Thanks

**Comment by TimelordUK** [comment]
if you use the lib natively as below then we should bind params as types they are defined in the procedure itself i.e. it should simply send the params with correct types. How are you calling this procedure? if it is via mssql wrapper then they format a SQL string i believe and we simply submit that.  You will have to include an actual simple example of what you are doing.

```js

const spName = 'test_sp_select_select'

    const def = `alter PROCEDURE <name>(
@num1 INT,
@num2 INT,
@num3 INT OUTPUT

)AS
BEGIN
   SET @num3 = @num1 + @num2
   RETURN 99;
END
`

const pm = theConnection.procedureMgr()
        pm.get(spName, proc => {
          const count = pm.getCount()
          assert.strictEqual(count, 1)
          const o = {
            num1: 10,
            num2: 100
          }
          const p = proc.paramsArray(o)
          proc.call(p, (err, results, output) => {
            assert.ifError(err)
```
