### ISSUE TITLE
procedureMgr.bindParams never increments the current param id (j)

### ISSUE THREAD

**Issue by davewthompson** [TimelordUK/node-sqlserver-v8#18]
Hey there,

There's a bug inside procedureMgr.bindParams where the 'j' variable is never updated; this means that parameters with more than one input parameter won't work properly.

I have altered the function to:

```javascript
function bindParams(meta, params) {
        var j = 0;
        for (var i = 0; i < params.length; ++i) {
            while (j < meta.params.length && meta.params[j].is_output === true) {
                ++j;
            }
            if (j < meta.params.length) meta.params[j++].val = params[i];
        }
    }
```

Looks good?

**Comment by Miramac** [comment]
Funny, I had exactly the same problem today :)

the fix worked for me

**Comment by TimelordUK** [comment]
I really appreciate you finding this issue and reporting a fix.  I have added a test case and patched your revised function into latest version.

thanks!

**Comment by TimelordUK** [comment]
I'll close thanks for fix.  It is in latest version.

**Comment by gh0st** [comment]
I'm wondering if I'm running into a similar issue. I'm getting the error

```
D:\Project\node_modules\msnodesqlv8\lib\procedure.js:93
        if (meta.params[j].is_user_defined) {
                          ^

TypeError: Cannot read property 'is_user_defined' of undefined
    at bindParams (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:93:27)
    at privateCall (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:104:22)
    at Object.callNotify (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:126:7)
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:323:11
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:294:13
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:183:9
    at Object.callback (D:\Project\node_modules\msnodesqlv8\lib\meta.js:77:11)
    at onQueryRaw (D:\Project\node_modules\msnodesqlv8\lib\connection.js:126:20)
    at D:\Project\node_modules\msnodesqlv8\lib\reader.js:83:13
    at D:\Project\node_modules\msnodesqlv8\lib\driver.js:158:13
```
With an SP call like so

```
sql.open(config.connectionString, (err, conn) => {
    const pm = conn.procedureMgr();
    let params = [fromDate, toDate, employeeId, caseId, offset];
    pm.callproc('CalWINAuditLog.spFactIsu', params, (err, results, output) => {
        console.log(results);
    });
});
```

**Comment by TimelordUK** [comment]
It would be handy if under lib queries you could run the proc describe and just edit by using your stored procedure name.  you could even try in your local system if isnull(is_user_defined,false) in that file  to force a value to be returned. Any information to help track it down gratefully received.

**Comment by gh0st** [comment]
I'm not quite following you. So edit the `lib/queries/proc_describe.sql` file and replace `<escaped_procedure_name>` with the name of my sp, and `<schema_name>` with my schema name, and try it again?

**Comment by gh0st** [comment]
And furthermore, is `isnull()` defined somewhere else in node-sqlserver-v8?
```
\node_modules\msnodesqlv8\lib\procedure.js:93
    if (isnull(meta.params[j].is_user_defined, false)) {
            ^

ReferenceError: isnull is not defined
```

**Comment by TimelordUK** [comment]
sorry, scrub the isnull() part - and thanks for sending the sql output, it looks like we have 6 input parameters? are some of these defaulted in the stored procedure? Actually the code should probably check the parameter vector is correctly sized.

the code is actually looping through the set returned as above and expecting the param vector to be indexed at each place from 0 .. 5, unless of course the parameter is defined as output.

can you try 

sql.open(config.connectionString, (err, conn) => {
    const pm = conn.procedureMgr();
    // place params in order and default those unused.
    let params = [fromDate, toDate, null, null, offset, null];
    pm.callproc('dbo.spSearch', params, (err, results, output) => {
        console.log(results);
    });
});

**Comment by gh0st** [comment]
Yes I'll try this as soon as I'm back in the office.

**Comment by gh0st** [comment]
@TimelordUK, definitely still getting the `isnull is not defined`.

```
[ '20180421', '20180521', null, null, '0', null ]
D:\Project\node_modules\msnodesqlv8\lib\procedure.js:93
        if (isnull(meta.params[j].is_user_defined, false)) {
            ^

ReferenceError: isnull is not defined
    at bindParams (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:93:13)
    at privateCall (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:104:22)
    at Object.callNotify (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:126:7)
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:323:11
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:294:13
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:183:9
    at Object.callback (D:\Project\node_modules\msnodesqlv8\lib\meta.js:77:11)
    at onQueryRaw (D:\Project\node_modules\msnodesqlv8\lib\connection.js:126:20)
    at D:\Project\node_modules\msnodesqlv8\lib\reader.js:83:13
    at D:\Project\node_modules\msnodesqlv8\lib\driver.js:158:13
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gh0st** [comment]
```
D:\Project\node_modules\msnodesqlv8\lib\procedure.js:93
        if (meta.params[j].is_user_defined) {
                          ^

TypeError: Cannot read property 'is_user_defined' of undefined
    at bindParams (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:93:27)
    at privateCall (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:104:22)
    at Object.callNotify (D:\Project\node_modules\msnodesqlv8\lib\procedure.js:126:7)
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:323:11
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:294:13
    at D:\Project\node_modules\msnodesqlv8\lib\procedure.js:183:9
    at Object.callback (D:\Project\node_modules\msnodesqlv8\lib\meta.js:77:11)
    at onQueryRaw (D:\Project\node_modules\msnodesqlv8\lib\connection.js:126:20)
    at D:\Project\node_modules\msnodesqlv8\lib\reader.js:83:13
    at D:\Project\node_modules\msnodesqlv8\lib\driver.js:158:13
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gh0st** [comment]
So I do it after the first loop, before the second loop inside `bindParams(...)`. This is what I get from a `console.log(JSON.stringify(meta.params))`:

```
[{
  "is_output": true,
  "name": "@returns",
  "type_id": "int",
  "max_length": 4,
  "order": 0,
  "collation": null
}]
```

**Comment by TimelordUK** [comment]
Ok so weirdly it thinks there are no parameters other than the default return.  This is why we see an error this should be the list of arguments into the procedure.  Basically file meta.js getProcedureDefinition

I would add console.log of sql after the sql and before the query. Then console.log Json.stringify the typeresults just before the callback. 

Are we definitely binding to correct one do you have different procedures with same name on different schemes 

Sorry about format I’m on the iPad I’ll log on and tidy up code below later.  




function getProcedureDefinition (conn, procedureName, mapFn, callback) {
resolveDescribeProcedureSql(function (sql) {
sql = mapFn(sql)
conn.query(sql, function (err, typeResults) {
callback(err, typeResults)
})
})
}

**Comment by gh0st** [comment]
So here is what my `getProcedureDefinition(...)` looks like

```javascript
function getProcedureDefinition (conn, procedureName, mapFn, callback) 
  resolveDescribeProcedureSql(function (sql) {
    sql = mapFn(sql)
    console.log(sql);
    conn.query(sql, function (err, typeResults) {
      console.log(JSON.stringify(typeResults));
      callback(err, typeResults)
    })
  })
}
```

and here are the results
```
sql: select
    is_output,
    sp.name,
    type_id   = type_name(sp.user_type_id),
    sp.max_length,
    'order'  = parameter_id,
    'collation'   = convert(sysname,
        case
            when sp.system_type_id in (35, 99, 167, 175, 231, 239)
                then ServerProperty('collation') end),
    ty.is_user_defined
 from
        sys.parameters sp
        left outer join sys.table_types ty
            on ty.name=type_name(sp.user_type_id)
                and ty.schema_id = schema_id('MySchema')
        where
            object_id = object_id('spSearch')
typeResults:  []
```

Definitely the right stored proc.

**Comment by gh0st** [comment]
Correct, no data is being returned. If I change `where object_id = object_id('spSearch')` to `where object_id = object_id('MySchema.spSearch')` data is returned.

**Comment by gh0st** [comment]
Seeing this now, if I change my `pm.callproc('MySchema.spSearch', ...)` to `pm.callproc('MySchema.MySchema.spSearch', ...)` then I get data in my `typeResults`, and my `meta.params`.

**Comment by gh0st** [comment]
I'm using MSSQL Server 2016.

**Comment by gh0st** [comment]
If I call `pm.callproc('MySchema.MySchema.spSearch', ...)` I get an error of `[Microsoft][SQL Server Native Client 11.0][SQL Server]Database 'MySchema' does not exist. Make sure that the name is entered correctly.`

If I provide a stored proc name of `MyDatabase.MySchema.spSearch` it executes succcessfully. This seems to be the fix.
