### ISSUE TITLE
call SP works in simple node run, not called from http

### ISSUE THREAD

**Issue by frfancha** [TimelordUK/node-sqlserver-v8#180]
Using the exact same calls to stored proc from node.js script works, but no more once in http server.
With message: p.callNotify is not a function
So I'd like to try to bind myself the parameters preparing the statement exec myProc ?, ?, ?  (like I have to do from C# e.g.)
But except mentioning that preparedStatement are supported in the readme, I haven't been able to find any documentation.
Is this possible for stored proc? How?

**Comment by TimelordUK** [comment]
do you mean something like below but you are calling a procedure?

please run and change the select query to run current db, schema, user for example - are you using authenticated user with different login / access rights to how you are running as test from console

The procedure code needs improved error management it is likely the driver is trying to get meta data from the server on proc name and it is not getting anything and this is error produced - needs to return an error rather throw exception

SELECT CURRENT_USER;  
SELECT SCHEMA_NAME();  
SELECT db_name();  

```js
const http = require('http')
const hostname = 'localhost'
const port = 2020
const sql = require('msnodesqlv8')
const util = require('util')

const connectionString = 'driver={SQL Server Native Client 11.0};server=(localdb)\\node;trusted_connection=yes;`database=scratch;`'
const query = 'select top 50 object_name(c.object_id), (select dc.definition from sys.default_constraints as dc where dc.object_id = c.default_object_id) as DefaultValueExpression from sys.columns as c'

async function test (request, response) {
  response.statusCode = 200
  response.setHeader('Content-Type', 'text/plain')

  console.log('>> test')
  const sqlOpen = util.promisify(sql.open)
  try {
    console.log('sqlOpen ....')
    const connection = await sqlOpen(connectionString)
    console.log('..... sqlOpen')
    const connectionQuery = util.promisify(connection.queryRaw)
    const close = util.promisify(connection.close)
    try {
      const d = new Date()
      console.log('connectionQuery 1 ....')
      const data = await connectionQuery(query)
      console.log('... connectionQuery 1')
      const elapsed = new Date() - d
      console.log(`rows.length ${data.rows.length} elapsed ${elapsed}`)
      response.end(JSON.stringify(data, null, 4))
      console.log('close ...')
      await close()
      console.log('... close')
      console.log('<< test')
    } catch (err) {
      response.end(err.message)
    }
  } catch (err) {
    response.end(err.message)
  }
}

const httpServer = http.createServer((request, response) => {
  test(request, response)
})
httpServer.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`)
})
```

**Comment by frfancha** [comment]
Thanks for your help, I really appreciate that.
Meanwhile I have done some progress...
1) I was wrongly using the SQL Server Native Client 11, using ODBC Driver 17 For SQL Server has helped!
2) The stored procedure wasn't using the SET NOCOUNT ON statement, and therefore the pm.callproc callback was called at each SQL statement from the proc without possibility to know if the proc was finished or not ... I'm not working on my usual DB (otherwise would use C#), in "my" DB all stored proc include that statement ... I will (let) change the stored proc to set it.
3) It is now clear that passing the wrong number of arguments causes the message "p.callNotify is not a function" ... honestly you could give better error messages ;-)

**Comment by TimelordUK** [comment]
on windows this driver should work SQL Server Native Client 11.0 - i just tried node 14.9.0

if you run ODBC data sources does the driver show up in Drivers tab?

I have added slightly better error handling for sprocs this is on master however I have not yet released on npm.  You are right, it definately needs improvement.

```cmd

$ node --version
v14.9.0

$ node runtest.js -l -t query
{ _: [], l: true, t: 'query' }
use conn_str Driver={SQL Server Native Client 11.0}; Server=(localdb)\node;Database=scratch;Trusted_Connection=yes;


  query
    √ test retrieving a string with null embedded (126ms)
    √ test retrieving a large decimal as a string
    √ multiple results from query in callback
    √ verify empty results retrieved properly
    √ object_name query  (210ms)
    √ select nulls union all nulls
    √ test function parameter validation (38ms)
    √ test retrieving a LOB string larger than max string size
    √ query with errors
    √ simple query
    √ simple rawFormat query
    √ simple query of types like var%
    √ streaming test
    √ serialized queries
    √ query with errors
    √ multiple results from query in events
    √ boolean return value from query
    √ test retrieving a non-LOB string of max size
    √ test retrieving an empty string
    √ test function parameter validation
    √ verify metadata is retrieved for udt/geography types (862ms)
```

**Comment by frfancha** [comment]
Really appreciate your time, if I can help this project by doing some tests, happy to do so.

I think I have understood the 2 main causes of my issues:

1 - pm.callproc is a function containing a callback to a callback and that plays wrongly with http server and try catch, and even more promises. Correct understanding of errors was challenging.
Much easier to debug if I first describe and then call the proc, like pm.callproc does but stopping between the two if describe doesn't work:

```
      pm.describe(proc, (p) => {
        try {
          if (!p.call) {
            return reject("invalid " + proc);
          }
          p.call(params, (callprocError, res, out) => {
            try {
...
```

2 - There is an enormous assumption in the code of procedure.js that output parameters are output only  and not passed in the parameters array ... That's plainly wrong: in SQL Server output parameters are input as well ... I'll open another issue for that.

NB: by using full async/await code and describe/call instead of callproc, I was able to test again SQL Server Native Client 11.0 and it works as well as ODBC Driver 17 For SQL Server.

NB2: here is my full "await/async" code to call proc e.g. when using the Koa.js framework, works quite well:

```
const exec = async (proc, params) => {
  const con = await getSql();
  return new Promise((resolve, reject) => {
    try {
      const pm = con.procedureMgr();
      let i = 0;
      console.debug("Describing " + proc);
      pm.describe(proc, (p) => {
        try {
          if (!p.call) {
            return reject("invalid " + proc);
          }
          console.debug("Calling " + proc + " " + params);
          p.call(params, (callprocError, res, out) => {
            try {
              i += 1;
              if (callprocError) {
                return reject(callprocError);
              }
              if (i === 1) {
                console.debug("Called proc " + proc + " " + params + " out=" + out);
                return resolve({ res, out });
              } else {
                console.debug("ReCalled proc ?? cb " + i + " " + proc + " " + params);
              }
            } catch (ex) {
              console.error(ex);
              return reject(ex);
            }
          });
        } catch (ex) {
          console.error(ex);
          return reject(ex);
        }
      });
    } catch (ex) {
      console.error(ex);
      return reject(ex);
    }
  });
};
```

And while we are busy:

```
const getSql = async () => {
  return new Promise((resolve, reject) => {
    try {
      const connectionString = `server=${env.SQLSERVER};Database=${env.SQLDB};Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}`;
      const sql = require("msnodesqlv8");
      sql.open(connectionString, (openError, con) => {
        if (openError) {
          return reject(openError);
        }
        return resolve(con);
      });
    } catch (ex) {
      return reject(ex);
    }
  });
};
```

Bonus, query:

```
const query = async (query) => {
  const con = await getSql();
  return new Promise((resolve, reject) => {
    try {
      con.query(query, (queryError, rows) => {
        if (queryError) {
          return reject(queryError);
        }
        return resolve(rows);
      });
    } catch (ex) {
      return reject(ex);
    }
  });
};
```

**Comment by frfancha** [comment]
Let's close this thread, there were some issues calling stored procedures under http, mainly catching errors correctly, but no real bug to solve.
