### ISSUE TITLE
impossible to pass input/output parameter to SQL Procedure

### ISSUE THREAD

**Issue by frfancha** [TimelordUK/node-sqlserver-v8#181]
This is working:
```
create or alter procedure dbo.testOp1 (
	@a INT,
	@b INT,
	@plus INT out
)
AS begin
  SET XACT_ABORT ON;
  SET NOCOUNT ON;
  set @plus = @a + @b;
end;
```
3+2=5 in SQL:
```
declare @v int;
exec dbo.testOp1 2, 3, @v out;
print @v
```
and node-sqlserver-v8 as well:
```
{"res":[],"out":[0,5]}
```
But this is working in SQL and not in node-sqlserver-v8 :-( :
```
create or alter procedure dbo.testOp2 (
	@a INT,
	@plus INT out
)
AS begin
  SET XACT_ABORT ON;
  SET NOCOUNT ON;
  set @plus = @a + @plus;
end;
```
3+2=5 in SQL:
```
declare @v int = 3;
exec dbo.testOp2 2, @v out;
print @v
```
not in node-sqlserver-v8, problem is that output parameter is ignored when setting parameter from input:
```
TypeError: Cannot read property 'is_user_defined' of undefined
    at bindParams (d:\Dev\secure-js-api-jwt\node_modules\msnodesqlv8\lib\procedure.js:105:28)
```
This code:
```
      for (let i = 0; i < params.length; i += 1) {
        while (j < meta.params.length && meta.params[j].is_output === true) {
          j += 1
        }

        if (meta.params[j].is_user_defined) {
          vec[j] = params[i]
        } else {
          vec[j].val = params[i]
        }
        j += 1
      }
```
Makes the enormous assumption that out parameters are not passed as in.

The best solution I can think of is to keep the existing behaviour when you pass an array of parameters, but to add the possibility to pass an object of parameters and to match from the object attribute to parameter using the attribute name instead of the position in an array.
That would have the big advantage to be able to pass only required parameters (when some are optional) quite easily.

**Comment by TimelordUK** [comment]
ok thanks ill take a look at this one first - agreed looking at code this is exactly what is going on

**Comment by TimelordUK** [comment]
I have not released to npm yet but below tests now work which is the input output params and optional params

basically you can send in 

```js
          const o = {
            a: 2,
            b: 3,
            c: 4
          }
          proc.call(o, (err, results, output) => {

```

```javascript
test('optional parameters set output to 0', testDone => {
    const spName = 'test_sp_get_optional_p'

    const def = `create or alter procedure <name>(
      @plus INT out,
      @a INT,
      @b INT,
      @c INT = 0
    )
    AS begin
      SET XACT_ABORT ON;
      SET NOCOUNT ON;
      set @plus = @a + @b + @c;
    end;
`
    const fns = [
      asyncDone => {
        procedureHelper.createProcedure(spName, def, () => {
          asyncDone()
        })
      },

      asyncDone => {
        const pm = theConnection.procedureMgr()
        pm.get(spName, proc => {
          const count = pm.getCount()
          assert.strictEqual(count, 1)
          const o = {
            a: 2,
            b: 3,
            c: 4
          }
          proc.call(o, (err, results, output) => {
            assert.ifError(err)
            if (output) {
              assert(Array.isArray(output))
              const expected = [
                0,
                o.a + o.b + o.c
              ]
              assert.deepStrictEqual(expected, output)
              asyncDone()
            }
          })
        })
      }
    ]

    async.series(fns, () => {
      testDone()
    })
  })

  test('use input output parameters i.e. use a param as both input and output ', testDone => {
    const spName = 'test_sp_get_in_out_p'

    const def = `create or alter procedure <name> (
      @a INT,
      @plus INT out
    )
    AS begin
      SET XACT_ABORT ON;
      SET NOCOUNT ON;
      set @plus = @a + @plus;
    end;
`
    const fns = [
      asyncDone => {
        procedureHelper.createProcedure(spName, def, () => {
          asyncDone()
        })
      },

      asyncDone => {
        const pm = theConnection.procedureMgr()
        pm.get(spName, proc => {
          const count = pm.getCount()
          assert.strictEqual(count, 1)
          const o = {
            a: 2,
            plus: 3
          }
          proc.call(o, (err, results, output) => {
            assert.ifError(err)
            if (output) {
              assert(Array.isArray(output))
              const expected = [
                0,
                o.a + o.plus
              ]
              assert.deepStrictEqual(expected, output)
              asyncDone()
            }
          })
        })
      }
    ]

    async.series(fns, () => {
      testDone()
    })
  })
```

**Comment by frfancha** [comment]
Splendid.
Now, if I may be difficult, stored procedure parameters in SQL Server are case insensitive.
You can't have both parameters @a & @A for the same procedure.
(Same for column names: you can't have column a & A in the same table.
And SQL is case insensitive in parsing your query: "select a from myTable" or "select A from MyTaBlE" will always both work for a column named a or A.)
So, it would really be great if mapping object keys to parameter names would be case insensitive as well...

**Comment by mtriff** [comment]
@frfancha SQL Server is case insensitive by default, but can be set to case sensitive during installation, see the docs on [changing the server collation](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation) for details.

**Comment by frfancha** [comment]
Nope. You are confusing the case sensitivity of SQL contents such as column content which is indeed managed by collation, and case sensitivity of SQL keywords such as select, from, where, and column names. Keywords and column names are always case insensitive (column contents follow the collation indeed). But here we are speaking of parameter names and these names are case insensitive.

**Comment by mtriff** [comment]
No, I am referring to Server Collation, not Column or Database Collation. The documentation I linked states:

> Variables `@pi` and `@PI` are considered as different variables if the server-level collation is case-sensitive, and the same variables if the server-level collation is case-insensitive.

**Comment by frfancha** [comment]
Hum yes indeed. But are you allowed to create a procedure with two parameters differing by case only ?
I don't have access to an empty server right now to test it.

**Comment by TimelordUK** [comment]
Ok I have already made significant changes I think we will leave it there for now - on my test server the database throws an error on proc create if i include mixed case on the same name but whether than is an install option i do not not know.  Either way I have left the legacy array handling as it is despite its problems

now you can use an input object 


```js
    const spName = 'test_sp_get_optional_p'
    const a = 10
    const b = 20
    const def = `alter PROCEDURE <name> (
      @plus INT out,
      @a INT = ${a},
      @b INT = ${b}
      )
    AS begin
      -- SET XACT_ABORT ON;
      SET NOCOUNT ON;
      set @plus = @a + @b;
    end;
`
```

call with no params, the driver now assumes they are default input and will not bind them i.e. 

```js
          const o = {}
          proc.call(o, (err, results, output) => {
```

you can bind one param

```js
          const o = {
             a: 10
         }
          proc.call(o, (err, results, output) => {
```

or both

you can bind one param

```js
          const o = {
             a: 10,
             b: 20
         }
          proc.call(o, (err, results, output) => {
```

I will release shortly

**Comment by frfancha** [comment]
Great.
What would be the api we can call on 'proc' just before call to check the list of available parameter names?
Ideally allowing to read meta.params (or at minimum meta.params.map(p=>p.name) )?
Thanks

**Comment by TimelordUK** [comment]
closng fixed
