### ISSUE TITLE
timeout on "prebuild-install || node-gyp rebuild"

### ISSUE THREAD

**Issue by TayYates** [TimelordUK/node-sqlserver-v8#185]
Connection timeout when attempting install 

```
q:\CQDV\bin>cd ..

q:\CQDV>npm i msnodesqlv8

> msnodesqlv8@2.0.8 install q:\CQDV\node_modules\msnodesqlv8
> prebuild-install || node-gyp rebuild

prebuild-install WARN install connect ETIMEDOUT 140.82.112.4:443

q:\CQDV\node_modules\msnodesqlv8>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd q:\CQDV\node_modules\msnodesqlv8
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN cqdv@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msnodesqlv8@2.0.8 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msnodesqlv8@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Manually installing node-gyp didn't help, not sure what to do with this.

Also I'm pretty new to Node so I'm sorry if it's something easy, thanks!

**Comment by mtriff** [comment]
Something on your network is blocking the download. Are you on a corporate network with a proxy server? If so, you can follow [these steps to configure it for Node](https://jjasonclark.com/how-to-setup-node-behind-web-proxy/). 

Your firewall may also be blocking the download of a binary package via `npm`. If that's the case, you can try a couple options:
1. Download the correct version manually

    All the pre-built binaries are available on the [Releases](https://github.com/TimelordUK/node-sqlserver-v8/releases) page. The format of the binary tarballs is: 

    `msnodesqlv8-v[Package Version]-node-v[Node NODE_MODULE_VERSION]-[Platform].tar.gz`

    You can find your NODE_MODULE_VERSION from [this page](https://nodejs.org/en/download/releases/). Based on your output, it looks like you're running Node 12.19.0, which corresponds to NODE_MODULE_VERSION 72 on that page. Since you're running Windows (I'm assuming 64-bit), you should download `msnodesqlv8-v2.0.8-node-v72-win32-x64.tar.gz`.

    Then, extract `sqlserverv8.node` from the tarball, and copy it to `node_modules\msnodesqlv8\build\Release\sqlserverv8.node`.

2. Build from source

    I'm not sure what state your `node_modules` directory is in after that failed install. If the `msnodesqlv8` module isn't there at all, it will probably be easier to build from source locally on your machine. To do that, clone this repo and run the following from the `node-sqlserver-v8` folder:
    ```
    npm install
    npx node-gyp rebuild
    ```
    The npm install command will likely fail, but the `npx node-gyp rebuild` should run successfully. You may need to install some prerequisites for `node-gyp`, see [here](https://github.com/nodejs/node-gyp) for details.

    Then from your project directory, you can run:

    ```
    npm install C:\path\to\node-sqlserver-v8
    ```

    To install from the local package.

**Comment by TayYates** [comment]
Thanks for the quick response! I've never had a problem before with the network firewalling anything out of npm, but it does block everything out of pip so that may be the issue. I'll try to install on another network and let you know if that works.

**Comment by TayYates** [comment]
It's been over a year and I'm pretty sure it was just a networking issue. Closing Issue.
