### ISSUE TITLE
Invalid precision value when inserting a long string (> 2000 chars) to a NVARCHAR(MAX) column

### ISSUE THREAD

**Issue by nikoraisu** [TimelordUK/node-sqlserver-v8#19]
I seem to be getting an Invalid precision value error when attempting to insert a long string. The string is just over 2000 chars long, and the column is an `NVARCHAR(MAX)`, which is plenty big enough to hold it. The query works fine when running in a tool (e.g. Visual Studio / SQL Server Management Studio), but falls over when using this library.

My research led me here:

http://stackoverflow.com/questions/15007721/sqlbindparameter-invalid-precision-value-on-a-nvarcharmax-column

which suggests that we need to use `SQL_WLONGVARCHAR` rather than `SQL_WVARCHAR` when binding long strings. Looking through the code, my best guess is in `src/BoundDatum.cpp`, should we set `sql_type` to `SQL_WLONGVARCHAR` rather than `SQL_WVARCHAR` if it's over a certain length? Does that sound plausible, or am I barking up the wrong tree?

**Comment by TimelordUK** [comment]
yes, I have just tested a tentative fix - binding to SQL_WLONGVARCHAR does seem to work.  I will add a user defined binding function sql.WLongVarChar(s) to manually bind a long string and I guess the driver can switch to this automatically for long strings.  I will release a fix in next day or so/

conn.query("declare @s NVARCHAR(MAX)  = ?; select @s as s", [sql.WLongVarChar(s)], function (err, res) {

**Comment by TimelordUK** [comment]
can you update and try the user binding method above which forces the driver to use SQL_WLONGVARCHAR .  I have added any code to select automatically as I need to check further what is going on - there is a unit test case already which seems to do exactly as you require and this test passes.

use [sql.WLongVarChar(s)] as the param binding in the insert statement.

**Comment by NoelAbrahams** [comment]
@TimelordUK, does this only affect parametrised queries or all queries?

e.g.

```js
conn.query("declare @s nvarchar(max); SELECT @s = '...'; exec dbo.foo @s ");
```

**Comment by nikoraisu** [comment]
@TimelordUK Great - yes that fixes it; thanks! I can also confirm that without the custom binding, it falls over on *exactly* 2001 characters (2000 chars is fine).

Oddly I also have a similar issue to you in that I'm failing to reproduce the problem on a small testbed I rigged up, so I'm currently digging around to try and find out what is different between that and my main project/database.

**Comment by nikoraisu** [comment]
Ah OK - now it is happening in my testbed, so it seems to be intermittent (which doesn't make a lot of sense to me, admittedly). The bottom answer in [this thread](http://stackoverflow.com/questions/3460899/sql-server-invalid-precision-on-exists-check-query) suggests that the default binding logic can end up rearranging the query and basing its decisions on all manner of things.

In any case, the fix is good, so I'm sorted. It seems strange that sometimes it's fine and sometimes it isn't, but then again I know I'm storing a very large string, so it's seems reasonable for me to specify the binding function. Unless you want to keep it open, I'd be very happy to close this issue as resolved.

**Comment by TimelordUK** [comment]
Ok great thanks for the update.   I will close the issue if it's working.
