### ISSUE TITLE
bulkMgr is generating wrong update signature

### ISSUE THREAD

**Issue by jakehe808** [TimelordUK/node-sqlserver-v8#193]
Right now, `bulkMgr.updateRows` can't support updating multiple columns at once.
Because in the update statement it generates, the columns to be updated are joined with 'and' instead of ','.
Example of wrong update statement: `update [database_name].[dbo].[table_name] set [col1] = ? and [col2] = ? where ( [ID] = ? )`.
To fix it, change 'and' to ',' in **columnSet** function in https://github.com/TimelordUK/node-sqlserver-v8/blob/master/lib/table.js.

**Comment by TimelordUK** [comment]
Thanks will check this and fix shortly.

**Comment by TimelordUK** [comment]
released as 2.0.9

**Comment by TimelordUK** [comment]
closing fixed
