### ISSUE TITLE
Error installing msnodesqlv8 on linux

### ISSUE THREAD

**Issue by abhi-tcs** [TimelordUK/node-sqlserver-v8#195]
Hi,

I am trying to install msnodesqlv8 package on openshift pod, but I'm getting the following error:
```
msnodesqlv8@2.0.10 install /opt/app-root/src/node_modules/msnodesqlv8
--
  | > prebuild-install || node-gyp rebuild
  |  
  | prebuild-install WARN install EACCES: permission denied, mkdir '/opt/app-root/src/node_modules/msnodesqlv8/build'
  | gyp ERR! configure error
  | gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/app-root/src/node_modules/msnodesqlv8/build'
  | gyp ERR! System Linux 3.10.0-1160.11.1.el7.x86_64
  | gyp ERR! command "/opt/rh/rh-nodejs12/root/usr/bin/node" "/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/bin/node-gyp.js" "rebuild"
  | gyp ERR! cwd /opt/app-root/src/node_modules/msnodesqlv8
  | gyp ERR! node -v v12.16.1
  | gyp ERR! node-gyp -v v5.0.5
  | gyp ERR! not ok
```
I am not getting this error while installing it on my local system(windows os), but I am getting this while deploying the code in linux environment. Node of the other npm packages are giving this type of error.

**Comment by TimelordUK** [comment]
well it looks like the installation is trying to create a sub folder and does not have sufficient permissions - are you able to test by installing in a folder with global write access to see if that helps.

**Comment by TimelordUK** [comment]
Closing this looks to be environment rather than general
