### ISSUE TITLE
Retrive multiple resulsets when executing stored procedure 

### ISSUE THREAD

**Issue by bpjs159** [TimelordUK/node-sqlserver-v8#197]
Hello!, I´m trying to execute a stored procedure  that returns multiple recordsets, But I just got first table result. I have tried the request.multiple = true parameter. But it does not keep working.

How can I retrive multiple resulsets when executing stored procedure with node-sqlserver-v8?

Thanks.

**Comment by TimelordUK** [comment]
there is a test in sproc which may help - i am not sure if you are using library natively if you use mssql i am afraid i do not know how that would work, we should support this in the native lib ourselves

```javascript
 test('proc with multiple select  - should callback with each', testDone => {
    const spName = 'test_sp_select_select'

    const def = `alter PROCEDURE <name>(
@num1 INT,
@num2 INT,
@num3 INT OUTPUT

)AS
BEGIN
BEGIN
    select top 5 'syscolumns' as table_name, name, id, xtype, length from syscolumns
    select top 5 'sysobjects' as table_name, name, id, xtype, category from sysobjects
END
END
`

    const fns = [
      asyncDone => {
        procedureHelper.createProcedure(spName, def, () => {
          asyncDone()
        })
      },

      asyncDone => {
        const pm = theConnection.procedureMgr()
        pm.get(spName, proc => {
          const count = pm.getCount()
          assert.strictEqual(count, 1)
          const aggregate = []
          const reducer = (arr) => {
            return arr.reduce((t, latest) => {
              t.push(latest.table_name)
              return t
            }, [])
          }
          proc.call([], (err, results, output) => {
            assert.ifError(err)
            aggregate.push(results)
            if (output) {
              assert.strictEqual(2, aggregate.length, 'results didn\'t match')
              assert.strictEqual(true, Array.isArray(aggregate[0]))
              assert.strictEqual(true, Array.isArray(aggregate[1]))
              const tableNames0 = reducer(aggregate[0])
              tableNames0.forEach(s => {
                assert.strictEqual('syscolumns', s)
              })
              const tableNames1 = reducer(aggregate[1])
              tableNames1.forEach(s => {
                assert.strictEqual('sysobjects', s)
              })
              asyncDone()
            }
          })
        })
      }
    ]

    async.series(fns, () => {
      testDone()
    })
  })
```

**Comment by bpjs159** [comment]
> there is a test in sproc which may help - i am not sure if you are using library natively if you use mssql i am afraid i do not know how that would work, we should support this in the native lib ourselves
> 
> ```js
>  test('proc with multiple select  - should callback with each', testDone => {
>     const spName = 'test_sp_select_select'
> 
>     const def = `alter PROCEDURE <name>(
> @num1 INT,
> @num2 INT,
> @num3 INT OUTPUT
> 
> )AS
> BEGIN
> BEGIN
>     select top 5 'syscolumns' as table_name, name, id, xtype, length from syscolumns
>     select top 5 'sysobjects' as table_name, name, id, xtype, category from sysobjects
> END
> END
> `
> 
>     const fns = [
>       asyncDone => {
>         procedureHelper.createProcedure(spName, def, () => {
>           asyncDone()
>         })
>       },
> 
>       asyncDone => {
>         const pm = theConnection.procedureMgr()
>         pm.get(spName, proc => {
>           const count = pm.getCount()
>           assert.strictEqual(count, 1)
>           const aggregate = []
>           const reducer = (arr) => {
>             return arr.reduce((t, latest) => {
>               t.push(latest.table_name)
>               return t
>             }, [])
>           }
>           proc.call([], (err, results, output) => {
>             assert.ifError(err)
>             aggregate.push(results)
>             if (output) {
>               assert.strictEqual(2, aggregate.length, 'results didn\'t match')
>               assert.strictEqual(true, Array.isArray(aggregate[0]))
>               assert.strictEqual(true, Array.isArray(aggregate[1]))
>               const tableNames0 = reducer(aggregate[0])
>               tableNames0.forEach(s => {
>                 assert.strictEqual('syscolumns', s)
>               })
>               const tableNames1 = reducer(aggregate[1])
>               tableNames1.forEach(s => {
>                 assert.strictEqual('sysobjects', s)
>               })
>               asyncDone()
>             }
>           })
>         })
>       }
>     ]
> 
>     async.series(fns, () => {
>       testDone()
>     })
>   })
> ```

Thanks for responding, I use the 'mssql/msnodesqlv8'.

Found that it just retrive one recordset when running stored procedure: EXEC SP_HELPDB @dbname = 'master'.

But with user-created stored procedure works fine!
