### ISSUE TITLE
JSON.stringify( obj[] ) parameter to Stored Procedure

### ISSUE THREAD

**Issue by ogdonis** [TimelordUK/node-sqlserver-v8#199]
I am trying to pass a json string as a parameter to MS Stored Procedure

Works if I copy the JSON string, execute the SP from SSMS as a parameter.

PROC def
ALTER PROCEDURE [Integration].[InsertAlertTrigger_test] 
	-- Add the parameters for the stored procedure here
	@jsonparam varchar(max)
	
AS
BEGIN
--- ETC

const json = JSON.stringify(alert)

Not working for 

const params = {
  jsonparam : json
}
const pm = connection.procedureMgr()
            pm.get('[Integration].[InsertAlertTrigger_test]', proc => {
                const count = pm.getCount()
                const o = {
                    jsonparam: `N'${json}'`
                }
                proc.call(o, (err, results, output) => {
                    if(err != null) {
                        reject({ state: 'ERROR', message: err });
                    }
      --- ETC

or 
         
const params = [ json ]

pm.callproc('[SCHEMA].[InsertAlert_test]',
     params,
    function (err, results, output) {
    
    --- ETC

Error:
stack:'Error: [Microsoft][ODBC SQL Server Driver]Invalid character value for cast specification'
sqlstate:'22018'
message:'[Microsoft][ODBC SQL Server Driver]Invalid character value for cast specification'
code:0

for ref:  this works
const jsonstring = JSON.stringify(alert)
const insertQ = `INSERT INTO [SCHEMA].[__tempTest]  ([jsonstring]) VALUES(N'${json }')`
return new Promise((resolve, reject) => {
const q = pool.query(insertQ, (err, rows) => {
etc
--

**Comment by TimelordUK** [comment]
can you take a look at the json unit test added to trunk - it inserts a vector of records such as

```json
	{
	"BusinessEntityID":8,
	"NationalIDNumber":"811994146",
	"LoginID":"adventure-works\\diane1",
	"OrganizationNode":{"type":"Buffer","data":[90,225,88]},
	"OrganizationLevel":4,
	"JobTitle":"Research and Development Engineer",
	"BirthDate":"1980-07-06T00:00:00.000Z",
	"MaritalStatus":"S",
	"Gender":"F",
	"HireDate":"2003-01-30T00:00:00.000Z",
	"SalariedFlag":true,
	"VacationHours":62,
	"SickLeaveHours":51,
	"CurrentFlag":true,
	"rowguid":"31112635-663B-4018-B4A2-A685C0BF48A4",
	"ModifiedDate":"2008-07-31T00:00:00.000Z"
	},
```

```js
test('use proc to insert a JSON based complex object', testDone => {
    async function work () {
      try {
        const tableName = 'employeeJson'
        const procName = 'AddUpdateEmployeeJsonRecord'
        const h = new JsonHelper(theConnection, tableName, procName)
        await h.create()
        const parsedJSON = helper.getJSON()
        const pm = theConnection.procedureMgr()
        const promisedGetProc = util.promisify(pm.getProc)
        const p = await promisedGetProc(procName)
        let id = 0
        const promises = parsedJSON.map(r => insertRec(p, id++, r))
        const expected = await Promise.all(promises)
        const promisedQuery = util.promisify(theConnection.query)
        const selectedRecords = await promisedQuery(`select * from ${tableName} order by id asc`)
        const selected = selectedRecords.map(rec => rec.json)
        assert.deepStrictEqual(expected, selected)
      } catch (e) {
        assert.ifError(e)
      }
    }
    work().then(() => {
      testDone()
    }).catch(e => {
      assert.ifError(e)
    })
```

![image](https://user-images.githubusercontent.com/7300251/111034237-87ef1a00-840c-11eb-9565-4d02f4d93b8d.png)

**Comment by ogdonis** [comment]
The example you provided is good for a single object, one at a time. TY.
-- const promises = parsedJSON.map(r => insertRec(p, id++, r))

I want to send an array of objects as a JSON string. The Stored Procedure I have, takes a parameter  @jsonparam varchar(max) and parses an array of objects in a transaction.

I.E.
[
	{"BusinessEntityID":8,"NationalIDNumber":"811994147", "rest": "other"},
	{"BusinessEntityID":9,"NationalIDNumber":"811994148", "rest": "other"},
	{"BusinessEntityID":10,"NationalIDNumber":"811994149", "rest": "other"}
]

**Comment by ogdonis** [comment]
I back the version down to 2.0.5 and it is working. Was using 2.0.11s

**Comment by TimelordUK** [comment]
ok so i added a new test which parses an array in  proc on server and seems to be working fine. i.e. the proc below parses and returns a result set and i receive the parsed rows back to client after handing in a stringify array of objects

```js
 test('use proc to insert a JSON array and bulk parse on server', testDone => {
    async function work () {
      try {
        const tableName = 'employeeJson'
        const procName = 'AddUpdateEmployeeJsonRecord'
        const procNameJson = 'ParseJsonArray'
        const h = new JsonHelper(theConnection, tableName, procName, procNameJson)
        await h.create()
        const parsedJSON = helper.getJSON()
        const pm = theConnection.procedureMgr()
        const promisedGetProc = util.promisify(pm.getProc)
        const p = await promisedGetProc(procNameJson)
        const json = JSON.stringify(parsedJSON, null, 4)
        const promisedCall = util.promisify(p.call)
        const res = await promisedCall({
          json: json
        })
        assert(res)
        assert(Array.isArray(res))
      } catch (e) {
        assert.ifError(e)
      }
    }
    work().then(() => {
      testDone()
    }).catch(e => {
      assert.ifError(e)
    })
  })
```

```js
 const createJsonProcedureSql = `CREATE PROCEDURE ${jsonProcName}
      (
          @json nvarchar(max)
      )
      AS
BEGIN
  SELECT 
    BusinessEntityID, 
    NationalIDNumber, 
    LoginID,
    OrganizationLevel,
    JobTitle,
    BirthDate,
    MaritalStatus,
    Gender,
    HireDate,
    SalariedFlag,
    VacationHours,
    SickHours,
    CurrentFlag
    FROM OPENJSON(@json)
    WITH (
      BusinessEntityID int 'strict $.BusinessEntityID',
      NationalIDNumber nvarchar(50) '$.NationalIDNumber',
      LoginID nvarchar(50) '$.LoginID',
      OrganizationLevel int '$.OrganizationLevel',
      JobTitle nvarchar(50) '$.JobTitle',
      BirthDate DateTime2 '$.BirthDate',
      MaritalStatus char '$.MaritalStatus',
      Gender char '$.Gender',
      HireDate DateTime2 '$.HireDate',
      SalariedFlag char '$.SalariedFlag',
      VacationHours int '$.VacationHours',
      SickHours int '$.SickHours',
      CurrentFlag char '$.CurrentFlag'
    )
 END`
```

**Comment by TimelordUK** [comment]
I believe the JSON handling to be correct. Closing please provide a new test and issue showing how JSON is not working as expected.
