### ISSUE TITLE
Change Codepage for error messages to utf-8 because German letters were lost.

### ISSUE THREAD

**Issue by heroboy** [TimelordUK/node-sqlserver-v8#2]
Please merge this pull request. https://github.com/Azure/node-sqlserver/pull/134

**Comment by TimelordUK** [comment]
Thanks for raising this issue.  I will be releasing support for bulk insert,  delete and amend very shortly so will take a look at this in time for release.

**Comment by TimelordUK** [comment]
I have applied your change to master, the unit tests still seem to pass OK.  The master branch now contains bulk operations support.  I will be releasing on npm very shortly. Thanks for taking the time to raise this issue.

**Comment by TimelordUK** [comment]
i believe this issue to be fixed so will close.
