### ISSUE TITLE
Empty string parameter results in NULL value in column

### ISSUE THREAD

**Issue by nikoraisu** [TimelordUK/node-sqlserver-v8#20]
It seems that when binding an empty string, the resulting value in my column is NULL, not the empty string. This has come in recently - between 0.1.35 (where this doesn't occur) and the latest (0.1.44):

`UPDATE [mytable] SET [textfield] = ?', ['']`

Results in `textfield` being NULL, not the empty string

**Comment by TimelordUK** [comment]
ok, sorry about that.  I will fix it as a priority and let you know when it is ready.

thanks for letting me know.

**Comment by TimelordUK** [comment]
this should be fixed in 0.1.45 which has been published.

**Comment by NoelAbrahams** [comment]
@TimelordUK, I suggest making official tagged releases on GitHub as well so that they appear on the [releases tab](https://github.com/TimelordUK/node-sqlserver-v8/releases).

**Comment by nikoraisu** [comment]
Yep lovely that's fixed - thanks!

**Comment by TimelordUK** [comment]
Ok great thanks i will close the issue.  Appreciate raising.
