### ISSUE TITLE
RequestError: [Microsoft][ODBC Driver Manager] Function sequence error

### ISSUE THREAD

**Issue by heychazza** [TimelordUK/node-sqlserver-v8#204]
Hi all,

When streaming requests with the library, I occassionally get the following error:
```
RequestError: [Microsoft][ODBC Driver Manager] Function sequence error
```

I'm streaming around 1.5mil rows from a database within my workplace.

Versions:
 - Node: v15.3.0
 - MSSQL: v6.3.1
 - MSNodeSQLV8: v2.0.12
 

### Code
```js
        let streamedRequest = new sqlConnector.Request(this.pool)
        streamedRequest.stream = true
        streamedRequest.query('query')

        let quotesWithSimilarity = []
        let rowsToCheck = []
        const BATCH_SIZE = 25

        let totalChecked = 0

        streamedRequest.on('row', async (row) => {
            rowsToCheck.push(row)

            if (rowsToCheck.length >= BATCH_SIZE) {
                streamedRequest.pause()

                let batchedData = await checkBatchForDuplicates(rowsToCheck, policiesYesterday)
                batchedData.forEach(row => quotesWithSimilarity.push(row))
                totalChecked += rowsToCheck.length

                await setProgress(quoteQueryLoader, BATCH_SIZE, totalChecked)
                rowsToCheck = []

                streamedRequest.resume()
            }
        })

        streamedRequest.on('error', (error) => {
            quoteQueryLoader.stopAndFail(`Failed to stream 11 months of quotes (${error})`)
            reject()
        })

        streamedRequest.on('done', async (result) => {
            let batchedData = await checkBatchForDuplicates(result, policiesYesterday)
            batchedData.forEach(row => quotesWithSimilarity.push(row))
            totalChecked += rowsToCheck.length
            rowsToCheck = []
            queryTimer.end()

            quoteQueryLoader.stopAndSucceed(`Took ${queryTimer.getFormattedDuration()} to check ${common.addCommas(totalChecked)} quotes (11 months) with ${common.addCommas(quotesWithSimilarity.length)} similar from database.`)
            resolve(quotesWithSimilarity)
        })
```

Any reason for this?

I originally asked in https://github.com/tediousjs/node-mssql/issues/1215

**Comment by TimelordUK** [comment]
this error implies  internally the state machine has tripped up and we are calling functions in unexpected order - given number rows clearly this is not something bny sounds of it that can easily be reproduced, a few things to watch out for

1. in reader.js whilst it is not (yet) exported to client, you can try playing around with line 41 - this is number rows being fetched in one call from native driver and sent back to JS.   If you have small rows which i assume price quotes are, then i would be tempted o try for example setting this much higher to lower the number transactions - even say something like 10000.   Does this make it more likely to hit error or no difference?

```js
        let infoFromNextResult = false

        const rowBatchSize = 50 /* ignored for prepared statements */

        function isInfo (err) {
          return err && err.sqlstate && err.sqlstate.length >= 2 && err.sqlstate.substring(0, 2) === '01'
        }
```

2. do you have some sort of unique QuoteID, in which case can the select be broken into a number of smaller calls. i.e. select a range, process and select next range.

3. what is happening to memory footprint i.e. is process growing substantially, if we are failing to allocate memory all bets are off this is not handled at all in the native library.

4. it would be interesting to know what range this starts to become liekly to happen - for example would it ever occur on 1/5 million rows, or is there anything different about values in certain rows like Nan / null or something like that. i.e. for example if you have select top <N> where we cap N is there  a point where query always seems to work out of interest.

5. was going to suggest pause  resume i see you already do this - may be interesting to try using the library natively to achieve same thing to see if this makes any difference or at least simplifies the problem - something along lines of throttle.js  included in samples

```js
const sql = require('msnodesqlv8')
const util = require('util')

function getConnection () {
  const path = require('path')
  const config = require(path.join(__dirname, 'config.json'))
  return config.connection.local
}

main().then(() => {
  console.log('done')
})

async function main () {
  const connectionString = getConnection()
  const promisedOpen = util.promisify(sql.open)
  try {
    const con = await promisedOpen(connectionString)
    const promisedClose = util.promisify(con.close)
    await asStream((con))
    await promisedClose()
  } catch (err) {
    if (err) {
      if (Array.isArray(err)) {
        err.forEach((e) => {
          console.log(e.message)
        })
      } else {
        console.log(err.message)
      }
    }
  }
}

// create a long running task e.g. use batch for web call
function dispatch (batch) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(null)
    }, 1500, batch)
  })
}

function asStream (con) {
  return new Promise((resolve, reject) => {
    const sql = 'select top 750 * from master..syscolumns;'
    console.log('stream fetch query with throttle back to server to slow results')
    const q = con.query(sql)
    const errors = []
    let row = null
    let meta = null
    const rowsPerBatch = 100
    let batch = []
    let rowCount = 0
    let batchIndex = 0

    q.on('submitted', q => {
      console.log(`on.submitted ${q.query_str}`)
    })

    q.on('error', (err, more) => {
      if (more) {
        errors.push(err)
      } else {
        const msg = errors.map(e => e.message).join(', ')
        reject(new Error(msg))
      }
    })

    q.on('meta', (m) => {
      meta = m
    })

    // start of row so create a new array and store for later
    q.on('row', () => {
      ++rowCount
      row = [meta.length]
      batch.push(row)
    })

    function next () {
      const d = new Date()
      const ts = d.toLocaleTimeString()
      console.log(`${ts} - [${batchIndex}] (rowCount ${rowCount}): pause and dispatch ${batch.length} rows ...`)
      q.pauseQuery()
      dispatch(batch).then(() => {
        console.log(`${ts} - [${batchIndex}] (rowCount ${rowCount}): ... done, resume query`)
        batchIndex++
        batch = []
        q.resumeQuery()
      })
    }

    q.on('column', (c, d) => {
      const last = meta.length - 1
      row[c] = d
      if (c === last && batch.length === rowsPerBatch) {
        next()
      }
    })

    q.on('done', () => {
      console.log('on.done')
      if (batch.length > 0) {
        console.log(`[${batchIndex}] (rowCount ${rowCount}): last dispatch ${batch.length} rows`)
        dispatch(batch).then(() => {
        })
      }
    })

    q.on('free', () => {
      resolve(null)
    })
  })
}

```

to be honest whilst a lot of effort goes into testing this library, we have no tests for this sort of select size making it very hard to track down. 

sorry could not be more help presently.

**Comment by heychazza** [comment]
> this error implies internally the state machine has tripped up and we are calling functions in unexpected order - given number rows clearly this is not something bny sounds of it that can easily be reproduced, a few things to watch out for
> 
> 1. in reader.js whilst it is not (yet) exported to client, you can try playing around with line 41 - this is number rows being fetched in one call from native driver and sent back to JS.   If you have small rows which i assume price quotes are, then i would be tempted o try for example setting this much higher to lower the number transactions - even say something like 10000.   Does this make it more likely to hit error or no difference?
> 
> ```js
>         let infoFromNextResult = false
> 
>         const rowBatchSize = 50 /* ignored for prepared statements */
> 
>         function isInfo (err) {
>           return err && err.sqlstate && err.sqlstate.length >= 2 && err.sqlstate.substring(0, 2) === '01'
>         }
> ```
> 
> 1. do you have some sort of unique QuoteID, in which case can the select be broken into a number of smaller calls. i.e. select a range, process and select next range.
> 2. what is happening to memory footprint i.e. is process growing substantially, if we are failing to allocate memory all bets are off this is not handled at all in the native library.
> 3. it would be interesting to know what range this starts to become liekly to happen - for example would it ever occur on 1/5 million rows, or is there anything different about values in certain rows like Nan / null or something like that. i.e. for example if you have select top  where we cap N is there  a point where query always seems to work out of interest.
> 4. was going to suggest pause  resume i see you already do this - may be interesting to try using the library natively to achieve same thing to see if this makes any difference or at least simplifies the problem - something along lines of throttle.js  included in samples
> 
> ```js
> const sql = require('msnodesqlv8')
> const util = require('util')
> 
> function getConnection () {
>   const path = require('path')
>   const config = require(path.join(__dirname, 'config.json'))
>   return config.connection.local
> }
> 
> main().then(() => {
>   console.log('done')
> })
> 
> async function main () {
>   const connectionString = getConnection()
>   const promisedOpen = util.promisify(sql.open)
>   try {
>     const con = await promisedOpen(connectionString)
>     const promisedClose = util.promisify(con.close)
>     await asStream((con))
>     await promisedClose()
>   } catch (err) {
>     if (err) {
>       if (Array.isArray(err)) {
>         err.forEach((e) => {
>           console.log(e.message)
>         })
>       } else {
>         console.log(err.message)
>       }
>     }
>   }
> }
> 
> // create a long running task e.g. use batch for web call
> function dispatch (batch) {
>   return new Promise((resolve, reject) => {
>     setTimeout(() => {
>       resolve(null)
>     }, 1500, batch)
>   })
> }
> 
> function asStream (con) {
>   return new Promise((resolve, reject) => {
>     const sql = 'select top 750 * from master..syscolumns;'
>     console.log('stream fetch query with throttle back to server to slow results')
>     const q = con.query(sql)
>     const errors = []
>     let row = null
>     let meta = null
>     const rowsPerBatch = 100
>     let batch = []
>     let rowCount = 0
>     let batchIndex = 0
> 
>     q.on('submitted', q => {
>       console.log(`on.submitted ${q.query_str}`)
>     })
> 
>     q.on('error', (err, more) => {
>       if (more) {
>         errors.push(err)
>       } else {
>         const msg = errors.map(e => e.message).join(', ')
>         reject(new Error(msg))
>       }
>     })
> 
>     q.on('meta', (m) => {
>       meta = m
>     })
> 
>     // start of row so create a new array and store for later
>     q.on('row', () => {
>       ++rowCount
>       row = [meta.length]
>       batch.push(row)
>     })
> 
>     function next () {
>       const d = new Date()
>       const ts = d.toLocaleTimeString()
>       console.log(`${ts} - [${batchIndex}] (rowCount ${rowCount}): pause and dispatch ${batch.length} rows ...`)
>       q.pauseQuery()
>       dispatch(batch).then(() => {
>         console.log(`${ts} - [${batchIndex}] (rowCount ${rowCount}): ... done, resume query`)
>         batchIndex++
>         batch = []
>         q.resumeQuery()
>       })
>     }
> 
>     q.on('column', (c, d) => {
>       const last = meta.length - 1
>       row[c] = d
>       if (c === last && batch.length === rowsPerBatch) {
>         next()
>       }
>     })
> 
>     q.on('done', () => {
>       console.log('on.done')
>       if (batch.length > 0) {
>         console.log(`[${batchIndex}] (rowCount ${rowCount}): last dispatch ${batch.length} rows`)
>         dispatch(batch).then(() => {
>         })
>       }
>     })
> 
>     q.on('free', () => {
>       resolve(null)
>     })
>   })
> }
> ```
> 
> to be honest whilst a lot of effort goes into testing this library, we have no tests for this sort of select size making it very hard to track down.
> 
> sorry could not be more help presently.

Really appreciate the lengthy reply even so, even if the _end achievable result_ isn't there - I appreciate the time! 👍 

Weirdly, this error only happens every so often, could this be a issue with one of the dashboards at my workplace? Most of the time this runs, but then the odd time I get that error - or the application kills without _any_ form of error - this happens at the streaming part of the quotes (as there are around 1.5mil of them roughly speaking).
