### ISSUE TITLE
setUseUTC does not seem to work

### ISSUE THREAD

**Issue by brbeaird** [TimelordUK/node-sqlserver-v8#205]
I am having trouble disabling UTC translation (in some cases, I simply need dates returned from the DB that are not UTC dates).

I noticed an earlier issue (https://github.com/TimelordUK/node-sqlserver-v8/issues/44) that referenced setting setUseUTC to false on the connection, but that does not appear to be working. Has anyone verified this works lately?

```
msnodesql.open(connection_string, function (err, conn) {
        if (err) return console.error(err);
        conn.setUseUTC = false;
        conn.query("select convert(datetime, '2021-04-22 08:13:00.000') as test_field", function (err, res) {
            console.log(res);
        });
    });
```
**Expected:** 
Thu Apr 22 2021 08:13:00 GMT-0500 (Central Daylight Time)

**Actual Result:** 
Thu Apr 22 2021 03:13:00 GMT-0500 (Central Daylight Time)

**Software versions**

- NodeJS: 14.15.0
- node-sqlserver-v8: 2.0.15
- SQL Server: 2016

**Comment by TimelordUK** [comment]
Can you look in reader.is around line 184. I do not think this has either been changed or tested in some time indeed looking at it seems like we only even make an adjustment in callback mode which looks odd in itself. 

Don’t have time currently to look further at this.

**Comment by brbeaird** [comment]
It is working; this was my mistake - sorry. setUseUTC() is a function call, not a property to be set. The corrected code should be:

```
msnodesql.open(connection_string, function (err, conn) {
        if (err) return console.error(err);
        conn.setUseUTC(false);
        conn.query("select convert(datetime, '2021-04-22 08:13:00.000') as test_field", function (err, res) {
            console.log(res);
        });
    });
```

I thought I had tried that earlier but guess I had not. I have been doing a ton of testing with this combined with node-mssql, which handles that setting differently. Thanks again.

**Comment by brbeaird** [comment]
@TimelordUK  - one more question: are there any examples of how to set useUTC when using connection pools? I can't quite figure out how to access the connection in the same way to be able to to set it.

**Comment by TimelordUK** [comment]
looks to be a problem - in that it is missing, we need to add to the pool
create options and so it would be passed down on all child connections

I will get a fix out for it very shortly.

**Comment by brbeaird** [comment]
Thanks. I still think we may have an issue with reader.js around line 184. I am not sure why we would only want to do the translation depending on callback mode. I can submit a PR if you think this makes sense:

**Old code**
```
if (callback) {
  if (rowColumn && useUTC === false) {
    if (meta[column].type === 'date') {
      rowColumn = new Date(rowColumn.getTime() - rowColumn.getTimezoneOffset() * -60000)
    }
  }
  currentRow[column] = rowColumn
}
notify.emit('column', column, rowColumn, false)
}
```

**Proposed**
```
if (rowColumn && useUTC === false) {
  if (meta[column].type === 'date') {
    rowColumn = new Date(rowColumn.getTime() - rowColumn.getTimezoneOffset() * -60000)
  }
}
if (callback) {
  currentRow[column] = rowColumn
  notify.emit('column', column, rowColumn, false)
}

```

**Comment by brbeaird** [comment]
Sorry to keep piling on here, but it looks like this may also be an issue when doing a bulk insert. When we're inserting, it looks like dates are being automatically converted to UTC before inserting into the DB.
When using the tedious driver with mssql, as long as we pass in useUTC = false in the config, that does not happen. I'm wondering if there's something in this driver that needs to be altered to get the same effect.

**Comment by TimelordUK** [comment]
can you provide an example of how this issue manifests itself i.e. even
with a single column

**Comment by brbeaird** [comment]
Yep - may not get to it today, but I'll try to put together a simple example.

**Comment by brbeaird** [comment]
Ok, here's an example with a table named **utc_test** with a single column _testdate_. 

I am simply inserting a new JS date, which naturally contains my local timezone (Central). However, what actually gets inserted into the DB is the UTC equivalent, bumped out 5 hours.

```
sql.open(connectionString, function (err, conn) {
    conn.setUseUTC(false);
    var tm = conn.tableMgr();
    tm.bind('utc_test', cb);
 })

function cb(bulkMgr) {    
    var parsedJSON = [{testdate: new Date()}]; //{testdate: Mon Apr 26 2021 22:05:38 GMT-0500 (Central Daylight Time)}
    if (bulkMgr){bulkMgr.insertRows(parsedJSON, (result) => {})}
  }
```

Actual result in DB: 2021-04-27 03:05:38.760

**Comment by TimelordUK** [comment]
great thanks i will take a look at what driver is doing and report back shortly.

**Comment by TimelordUK** [comment]
this is on master - the release is now very significant in amount of change but your test case works, the bound table can now sent actual types to driver based on table definition, and for the datetime columns it will also send offset when the utc flag is off - the native driver then adjusts and sends the time so it is written in local time.

It wont be released for a few days, for testing it is still under test.  All unit tests pass it is now a candidate version.
'''js

 test('use tableMgr bulk insert single non UTC based date with datetime col', testDone => {
    async function runner () {
      const helper = new TypeTableHelper(theConnection, 'datetime')
      const testDate = new Date('Mon Apr 26 2021 22:05:38 GMT-0500 (Central Daylight Time)')
      const expected = helper.getVec(1, () => testDate)
      theConnection.setUseUTC(false)
      const table = await helper.create()
      const promisedInsert = util.promisify(table.insertRows)
      const promisedSelect = util.promisify(table.selectRows)
      try {
        await promisedInsert(expected)
        const res = await promisedSelect(expected)
        res.forEach(a => {
          delete a.col_a.nanosecondsDelta
        })
        assert.deepStrictEqual(res, expected)
      } catch (e) {
        assert.ifError(e)
      }
    }
    runner().then(() => {
      testDone()
    })
  })

'''

**Comment by brbeaird** [comment]
Wow. Thanks so much for your time and work on this. We will give it a test ourselves and see how it looks.

**Comment by brbeaird** [comment]
I just ran a few tests, and everything seems to be working correct now, even if I make calls from the mssql library that reference this new driver code. This will be such a huge help for us as it will enable us to use Windows authentication but still maintain some of the lesser-known features like this one. Thanks again.

**Comment by brbeaird** [comment]
With 2.1.0 out, I think we can close this.
