### ISSUE TITLE
typescript issues (Pool type)

### ISSUE THREAD

**Issue by larsjaas** [TimelordUK/node-sqlserver-v8#207]
I'm using msnodesqlv8 directly in a typescript+electron project, and I'm trying to use a connection pool and prepared statements.

First issue was that I could not write `const pool = new sql.Pool(options)` because the type-declaration for SqlClient.Pool is as a function that is not newable. So I made a declarations/-directory locally where I could override node-module types and started tweaking it. Altering the declaration for SqlClient.Pool to the below seems to please the syntax checker / compiler at least:
```
    Pool: { (options:PoolOptions) : Pool } & { new (options:PoolOptions) : Pool }
```
I am in the midst of porting from `tedious` (because of the windows auth issue) so I don't have code that runs at the moment though.

Next issue is that Pool is merged with EventEmitter, but the EventEmitter-functions are not declared on Pool, so you can't do for instance `pool.on('open', (options) => { console.log(...); })` since there is no 'on()' on the Pool type. So I added that.

So then I was ready to start preparing a statement, but looking at the examples and the type declaration file, I can only see that prepare() is a method on Connection, but with a Pool, where do I get hold of a Connection object? Or is it the Pool.query(sql, params, cb) method that wraps all that for prepared-statements?

**Comment by TimelordUK** [comment]
thanks ill try and add the additional declarations to the Pool type or even if you could post what you feel is correct would be very useful - great

at moment we do not support prepared statements on pool - the current implementation of the library is such the prepared statement even in low level cpp is owned by a specific connection and i believe under covers is a stored proc compiled on server.  Hence with a pool the only way i could think of is trying to prepare over all connections but that is wasteful and what about connections that are harvested and re-started

that said i will be honest and say i have not given it a huge amount of thought it was just not that obvious how to do things efficiently.

Of course I am open to ideas and indeed there may well be a good way of implementing but specifically it has to work with low level cpp ODBC library provided by MS.

**Comment by TimelordUK** [comment]
latest checked into master and the below sample compiles and runs

```typescript
import {Error, PoolOptions, Query, SqlClient, QueryDescription, Pool, PoolStatusRecord} from 'msnodesqlv8';

// require the module so it can be used in your node JS code.
export const sql : SqlClient = require('msnodesqlv8');

function getConnection () {
  const path = require('path')
  const config = require(path.join(__dirname, '..\\javascript\\config.json'))
  return config.connection.local
}

const str = getConnection()
const pool: Pool = new sql.Pool({
  connectionString: str
})

pool.on('open', (options: PoolOptions) => {
  console.log(`ready options = ${JSON.stringify(options, null, 4)}`)
})

pool.on('debug', (msg: string) => {
  console.log(`\t\t\t\t\t\t${new Date().toLocaleTimeString()} <pool.debug> ${msg}`)
})

pool.on('status', (s: PoolStatusRecord) => {
  console.log(`status = ${JSON.stringify(s, null, 4)}`)
})

pool.on('error', (e: Error) => {
  console.log(e)
})

const testSql = 'waitfor delay \'00:00:10\';'

function submit (sql: string): Query {
  const q: Query = pool.query(sql)
  const timeStr = new Date().toLocaleTimeString()
  console.log(`send ${timeStr}, sql = ${sql}`)
  q.on('submitted', (d: QueryDescription) => {
    console.log(`query submitted ${timeStr}, sql = ${d.query_str}`)
    q.on('done', () => console.log(`query done ${timeStr}`))
  })
  return q
}

for (let i = 0; i < 7; ++i) {
  const q: Query = submit(testSql)
  switch (i) {
    case 5:
      console.log('cancel a query')
      q.cancelQuery()
      break
    case 6:
      q.pauseQuery()
      setTimeout(() => {
        console.log('resume a paused query')
        q.resumeQuery()
      }, 50000)
      break
    default:
      break
  }
}

setInterval(() => {
  submit(testSql)
}, 60000)

pool.open((e, options) => {
    if (e) {
        console.log(`Error ${e.message}`)
    } else {
        console.log(JSON.stringify(options,null, 4))
    }
})

```
