### ISSUE TITLE
Callback firing twice

### ISSUE THREAD

**Issue by C-Rodg** [TimelordUK/node-sqlserver-v8#21]
Hi,
I'm running into an issue with a nested connection callback running twice.  What is returned in the console is:
x is 0
x is 1
y is 0
y is 1

And my code is:

```
x = 0;

y = 0;

sql.open(sqlConnectionString, function(err, conn) {
  if(err){
    return;
  }
  conn.queryRaw("USE master CREATE DATABASE [db_" + guid + "]", function(err, results) {
    //the function below's callback runs twice
    conn.queryRaw("USE BuilderCatalog; insert into Events (Guid, Name, Edited, Date) VALUES('" + guid + "', '" + name + "', GETDATE(), '" + date.format() + "' )", function(err, results) {
      console.log("x is " + x);
      x++;
      conn.queryRaw("USE db_" + guid + "]; " + createTableString, function(err, results) {
        console.log("y is " + y);
        y++;
      }
    }
  }
});
```

Maybe I'm missing something, but any help would be appreciated!

**Comment by TimelordUK** [comment]
thanks for giving me an example of the error - I shall take a look and report back within the next few days with a response.

**Comment by TimelordUK** [comment]
sorry, I am in the middle of a massive update which allows support for prepared statements.  I have not therefore had time to look at this issue, but will do so as soon as possible.   I did write a test that simply did a simple query on 3 nested calls, and the code seemed to behave as expected

can you run below and ensure this is behaving in your environment as you expect.  If it does, must be something to do with what you are executing.

   var x = 0;
    var y = 0;

    sql.open(conn_str, function(err, conn) {
        if(err){
            return;
        }
        var s = new Array(500).join("a");
        conn.queryRaw("declare @s NVARCHAR(MAX)  = ?; select @s as s", [sql.WLongVarChar(s)], function(err, results) {
            //the function below's callback runs twice
            conn.queryRaw("declare @s NVARCHAR(MAX)  = ?; select @s as s", [sql.WLongVarChar(s)], function(err, results) {
                console.log("x is " + x);
                x++;
                conn.queryRaw("declare @s NVARCHAR(MAX)  = ?; select @s as s", [sql.WLongVarChar(s)], function(err, results) {
                    console.log("y is " + y);
                    y++;
                });
            });
        });
    });

**Comment by C-Rodg** [comment]
You are correct, your test query seems to run as expected in my environment. The issue of having things run twice must be coming from some other portion of my program (Express, middleware, click handlers, etc.). I'll investigate further and then reach out if I feel like this should still be labeled as a bug.  Thank you for your help!

**Comment by TimelordUK** [comment]
ill close this now, hope you got to bottom of the issue.
