### ISSUE TITLE
Bulk insert slow performance

### ISSUE THREAD

**Issue by brbeaird** [TimelordUK/node-sqlserver-v8#210]
We have noticed the performance of the bulk insert operation is quite slow, especially when compared to the tedious driver. Is there any particular reason for this? Here's a test table populated with 3000 records. It takes between 10-15 seconds to load into the table. However, loading the same data with tedious completes in under 3 seconds. The slowness is present even if I run the insert twice (ensuring the connection gets fired up the first time).

**msnodesqlv8 (10-15 seconds)**
```
sql.open(connectionString, function (err, conn) {
    conn.setUseUTC(false);
    var tm = conn.tableMgr();
    tm.bind('utc_test', cb);
 })

function cb(bulkMgr) {
  parsedJSON = []
  for (let i = 0; i < 3000; i++){
    parsedJSON.push(
      {
        testdate: new Date(),
        test1: '1',
        test2: 'testing2Data',
        test3: 'testing3Data',
        test4: 'testing4Data',
        test5: 'testing5Data'
      });
  }
    if (bulkMgr){bulkMgr.insertRows(parsedJSON, (result) => {})}
  }
```

**mssql/tedious (2-3 seconds)**
```
const table = new msql.Table(`${dbName}.dbo.${tableName}`);
    table.create = false;
    table.columns.add('testdate', msql.DateTime(23,3), {nullable: true});
    table.columns.add('test1', msql.VarChar(50), {nullable: true});
    table.columns.add('test2', msql.VarChar(100), {nullable: true});
    table.columns.add('test3', msql.VarChar(50), {nullable: true});
    table.columns.add('test4', msql.VarChar(50), {nullable: true});
    table.columns.add('test5', msql.VarChar(50), {nullable: true});

    parsedJSON = []
    for (let i = 0; i < 3000; i++){
        parsedJSON.push(
        {
            testdate: new Date(),
            test1: '1',
            test2: 'testing2Data',
            test3: 'testing3Data',
            test4: 'testing4Data',
            test5: 'testing5Data'
        });
    }

    for (let record of data) {
        {
            table.rows.add(...Object.values(record))
        }
    }
    const pool = await connectPool();
    const request = await pool.request();
    await request.bulk(table);
```

**Comment by TimelordUK** [comment]
bulk
inserted 3000 in 572 ms elapsed
selected 3000 in 698 ms elapsed
    √ load large number rows (1749ms)

```js

  class BulkTableTest {
    constructor (c, def) {
      function where (list, primitive) {
        return list.reduce((agg, latest) => {
          if (primitive(latest)) {
            agg.push(latest)
          }
          return agg
        }, [])
      }
      const tableName = def.tableName
      const columns = def.columns.map(e => `${e.name} ${e.type}`).join(', ')
      const insertColumnNames = where(def.columns, c => {
        const res = !c.type.includes('identity')
        return res
      }).map(e => `${e.name}`).join(', ')
      const columnNames = def.columns.map(e => `${e.name}`).join(', ')
      const dropTableSql = `IF OBJECT_ID('${tableName}', 'U') IS NOT NULL DROP TABLE ${tableName};`
      const createTableSql = `CREATE TABLE ${tableName} (${columns})`
      const clusteredSql = `CREATE CLUSTERED INDEX IX_${tableName} ON ${tableName}(id)`
      const insertSql = `INSERT INTO ${tableName} (${insertColumnNames}) VALUES `
      const selectSql = `SELECT ${columnNames} FROM ${tableName}`
      const trucateSql = `TRUNCATE TABLE ${tableName}`
      const paramsSql = `(${def.columns.map(_ => '?').join(', ')})`

      this.definition = def
      this.theConnection = c
      this.dropTableSql = dropTableSql
      this.createTableSql = createTableSql
      this.clusteredSql = clusteredSql
      this.selectSql = selectSql
      this.insertSql = insertSql
      this.truncateSql = trucateSql
      this.tableName = def.tableName
      this.paramsSql = paramsSql
      this.insertParamsSql = `${insertSql} ${paramsSql}`
    }

    async create () {
      const promisedQuery = util.promisify(theConnection.query)
      const tm = theConnection.tableMgr()
      const promisedGetTable = util.promisify(tm.getTable)
      await promisedQuery(this.dropTableSql)
      await promisedQuery(this.createTableSql)
      const table = await promisedGetTable(this.tableName)
      return table
    }
  }

  const bulkTableDef = {
    tableName: 'test_table_bulk',
    columns: [
      {
        name: 'id',
        type: 'INT PRIMARY KEY'
      },
      {
        name: 'd1',
        type: 'datetime'
      },
      {
        name: 's1',
        type: 'VARCHAR (255) NOT NULL'
      },
      {
        name: 's2',
        type: 'VARCHAR (100) NOT NULL'
      },
      {
        name: 's3',
        type: 'VARCHAR (50) NOT NULL'
      },
      {
        name: 's4',
        type: 'VARCHAR (50) NOT NULL'
      }
    ]
  }


  test('load large number rows', testDone => {
    async function runner () {
      const helper = new BulkTableTest(theConnection, bulkTableDef)
      const testDate = new Date('Mon Apr 26 2021 22:05:38 GMT-0500 (Central Daylight Time)')
      const expected = []
      const rows = 3000
      for (let i = 0; i < rows; ++i) {
        expected.push({
          id: i,
          d1: testDate,
          s1: `${i}`,
          s2: `testing${i + 1}2Data`,
          s3: `testing${i + 2}2Data`,
          s4: `testing${i + 3}2Data`
        })
      }
      theConnection.setUseUTC(false)
      const table = await helper.create()
      const promisedInsert = util.promisify(table.insertRows)
      const promisedSelect = util.promisify(table.selectRows)
      try {
        const start = new Date()
        await promisedInsert(expected)
        console.log(`inserted ${rows} in ${new Date() - start} ms elapsed`)
        const s1 = new Date()
        const res = await promisedSelect(expected)
        console.log(`selected ${res.length} in ${new Date() - s1} ms elapsed`)
        res.forEach(a => {
          delete a.d1.nanosecondsDelta
        })
        assert.deepStrictEqual(res, expected)
      } catch (e) {
        assert.ifError(e)
      }
    }
    runner().then(() => {
      testDone()
    })
  })

```

**Comment by brbeaird** [comment]
Thanks for putting that together. I am not sure why my operation would be so slow. I am not really familiar with mocha and do not know at this point how to run your example and point the connection to the server that is slow to do the insert, but at some point hopefully I can get some time to figure it out.

**Comment by TimelordUK** [comment]
if you are running on a VM i have noticed the client performance can be significantly worse - I have not looked into this, but that may be an explanation.

**Comment by brbeaird** [comment]
No VM's involved here. From the client part, this is just me running from my dev laptop.

Something kind of interesting, though - I traced the insert call from the SQL server just to compare things on that end between msnodesqlv8 and tedious. When msnodesqlv8 inserts, it appears to just be 3,000 separate insert statements via rpc calls. When tedious inserts, there is only a single sql_batch call (not rpc). Is there a different way I need to call this driver to have it make use of sql_batch instead of raw rpc insert statements? I see where the documentation mentions the possibility of configuring batch size - is that part of it?

**msnodesqlv8  - individual insert statements**
![image](https://user-images.githubusercontent.com/7239272/117052440-56445200-acdd-11eb-9e5d-843751ecff03.png)

**tedious - single sql_batch call**
![image](https://user-images.githubusercontent.com/7239272/117052511-6ceaa900-acdd-11eb-9e12-bb84d8dad07e.png)

**Comment by TimelordUK** [comment]
that doesnt seem right, we are binding one query with a vector of data 

batch size 0 is derfault which should send the whole data set in one go.

can you set a breakpoint in table.cs in function below

you should end up with in effect an array lengthed at number of columns and the value as an arrat of all data items - this is sent to native driver which sees it has to bind a vector and bulk binds.

it is as if batch size was 1 and we simply send one insert per row

```js
 function arrayPerColumnForCols (rows, colSubSet) {
        const colsByName = arrayPerColumn(rows).arrays_by_name
        const res = colSubSet.reduce((agg, col) => {
          if (Object.prototype.hasOwnProperty.call(colsByName, col.name)) {
            const valueVector = colsByName[col.name]
            if (Object.prototype.hasOwnProperty.call(declaredTypeByColumn, col.name)) {
              const declaration = declaredTypeByColumn[col.name]
              agg.push({
                value: valueVector,
                offset: declaration.offset || 0,
                sql_type: declaration.sql_type,
                precision: declaration.precision,
                scale: declaration.scale
              })
            } else {
              agg.push(valueVector)
            }
          }
          return agg
        }, [])
        return res
      }
```

**Comment by brbeaird** [comment]
That function does seem to return an array, sized at 6, and each of those contains 3000 elements.

![image](https://user-images.githubusercontent.com/7239272/117058250-03ba6400-ace4-11eb-942d-5d0b0fdd96a3.png)

**Comment by TimelordUK** [comment]
actually looking at my own server - even though we send vector arrays the server is translating that into indivisual inserts - I am unsure presently whether ODBC cpp native driver will allow the same call but in either case it wont be a trivial change and currently not something we will be undertaking. I may try looking at what tvp looks like via ODBC as we also support that.

But yes it does indeed look that is what is going on.

**Comment by brbeaird** [comment]
Bummer. Thanks for confirming. Will be glad to help test sometime down the road if dig more into it.

I am not sure how I would test this differently via transaction. I have set up bulk SQL insert calls with a few different platforms over the years, and I have honestly never understood the inner workings of it. All I know is if I need to insert thousands of rows, if I use the bulk interface (usually involving a different kind of method call), it happens in a much more optimized way behind the scenes.

**Comment by TimelordUK** [comment]
so i have been playing around on branch bcp which at moment only supports 2 column types - int and varchar for testing.

but looks promising. 50,000 rows inserted in 580ms -it wil only work with odbc17 below 

Debugger attached.
{ _: [], k: 'linux', t: 'bulk' }
use conn_str Driver={ODBC Driver 17 for SQL Server}; Server=192.168.1.102;UID=linux; PWD=linux; Database=node


  bulk
inserted 50000 in 580 ms elapsed

```js
test('bcp varchar varchar', testDone => {
    const bulkTableDef = {
      tableName: 'test_table_bcp',
      columns: [
        {
          name: 'id',
          type: 'INT PRIMARY KEY'
        },
        {
          name: 's1',
          type: 'VARCHAR (255) NOT NULL'
        },
        {
          name: 's2',
          type: 'VARCHAR (100) NOT NULL'
        }]
    }
    async function runner () {
      const helper = new BulkTableTest(theConnection, bulkTableDef)
      const expected = []
      const rows = 50000
      for (let i = 0; i < rows; ++i) {
        expected.push({
          id: i,
          s1: `column1${i}`,
          s2: `testing${i + 1}2Data`
        })
      }
      theConnection.setUseUTC(false)
      const table = await helper.create()
      table.setUseBcp(true)
      const promisedInsert = util.promisify(table.insertRows)
      const promisedQuery = util.promisify(theConnection.query)
      try {
        const start = new Date()
        await promisedInsert(expected)
        console.log(`inserted ${rows} in ${new Date() - start} ms elapsed`)
        const res = await promisedQuery(`select count(*) as rows from ${bulkTableDef.tableName}`)
        assert.deepStrictEqual(res[0].rows, rows)
      } catch (e) {
        assert.ifError(e)
      }
    }
    runner().then(() => {
      testDone()
    })
  })
```

![image](https://user-images.githubusercontent.com/7300251/117549249-342a3700-b031-11eb-8523-421ae06b01af.png)

**Comment by brbeaird** [comment]
Looks promising!

**Comment by TimelordUK** [comment]
not sure if you are in a position to test branch bcp?

you have to use TCP connection, connection string needs to be ODBC 17 only use conn_str 

Driver={ODBC Driver 17 for SQL Server}; Server= ....

the driver dll is as below - this is only one tested and i will not add bcp on any older versions

![image](https://user-images.githubusercontent.com/7300251/118196113-5adada00-b444-11eb-89af-d7c2edb4a765.png)

would be interesting to see if you see any improvement on insert speed.

to use bcp when fetching a table set bcp mode to true - this only effects row insert

```js
      theConnection.setUseUTC(false)
      const table = await helper.create()
      table.setUseBcp(true)
```

![image](https://user-images.githubusercontent.com/7300251/118195988-236c2d80-b444-11eb-92d1-ef882adb8ae0.png)

**Comment by brbeaird** [comment]
Awesome, thanks - I will test when I can but am pretty tied up at the moment. Will try to find a few minutes next week.

**Comment by TimelordUK** [comment]
closing bcp has been released for some time
