### ISSUE TITLE
can't install in openSUSE-Leap-15.2+node:14 nor in ubuntu:18.04+node:14

### ISSUE THREAD

**Issue by br4nnigan** [TimelordUK/node-sqlserver-v8#211]
so in my wsl host running openSUSE-Leap-15.2+node:14 I'm getting this:

    > npm i -s msnodesqlv8
    gyp: /usr/include/node14/common.gypi not found (cwd: /home/test/node_modules/msnodesqlv8) while reading includes of binding.gyp while trying to load binding.gyp

and inside a docker running ubuntu:18.04+node:14 I'm getting this:

    > npm i -s msnodesqlv8
    make: Entering directory '/home/node/node_modules/msnodesqlv8/build'
    CXX(target) Release/obj.target/sqlserverv8/src/ConnectionHandles.o
    In file included from ../src/ConnectionHandles.h:22:0,
                 from ../src/ConnectionHandles.cpp:1:
    ../src/stdafx.h:37:26: fatal error: sqltypes.h: No such file or directory

                          ^
    compilation terminated.
    sqlserverv8.target.mk:161: recipe for target 'Release/obj.target/sqlserverv8/src/ConnectionHandles.o' failed
    make: *** [Release/obj.target/sqlserverv8/src/ConnectionHandles.o] Error 1
    make: Leaving directory '/home/node/node_modules/msnodesqlv8/build'

🤷‍♂

**Comment by scola84** [comment]
[@types/mssql@7.1.0](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mssql) includes this package in its dependency list and stopped working due to this bug.

**Comment by mtriff** [comment]
> so in my wsl host running openSUSE-Leap-15.2+node:14 I'm getting this:
> 
> ```
> > npm i -s msnodesqlv8
> gyp: /usr/include/node14/common.gypi not found (cwd: /home/test/node_modules/msnodesqlv8) while reading includes of binding.gyp while trying to load binding.gyp
> ```
> 

This is an issue with [nodejs/node-gyp](https://github.com/nodejs/node-gyp) not being installed correctly. I'd recommend trying some of the fixes listed [here](https://github.com/nodejs/node-gyp/issues/313) and [here](https://github.com/nodejs/node-gyp/issues/376). Based on this output and those threads, I'd recommend trying to install `nodejs14-devel` with zypper, but that's just my first guess.

> and inside a docker running ubuntu:18.04+node:14 I'm getting this:
> 
> ```
> > npm i -s msnodesqlv8
> make: Entering directory '/home/node/node_modules/msnodesqlv8/build'
> CXX(target) Release/obj.target/sqlserverv8/src/ConnectionHandles.o
> In file included from ../src/ConnectionHandles.h:22:0,
>              from ../src/ConnectionHandles.cpp:1:
> ../src/stdafx.h:37:26: fatal error: sqltypes.h: No such file or directory
> 
>                       ^
> compilation terminated.
> sqlserverv8.target.mk:161: recipe for target 'Release/obj.target/sqlserverv8/src/ConnectionHandles.o' failed
> make: *** [Release/obj.target/sqlserverv8/src/ConnectionHandles.o] Error 1
> make: Leaving directory '/home/node/node_modules/msnodesqlv8/build'
> ```

Based on this output, it looks like you haven't installed the ODBC driver in the container, see [these instructions](https://github.com/TimelordUK/node-sqlserver-v8#linux-x64-only) from the README.

**Comment by scola84** [comment]
Thanks. I've solved my problem by moving @types/mssql@7.1.0 to the devDependencies of my app, which prevents it from being installed in the container.
