### ISSUE TITLE
getUserTypeTable is incorrect on the typescript definition

### ISSUE THREAD

**Issue by stephanussusanto** [TimelordUK/node-sqlserver-v8#213]
On the getUserTypeTable is not have name parameter.

```
export interface Connection {
    getUserTypeTable(cb:TableCb):void
....
}
```

Is that expected?
I saw on the example is still using 'name' parameter

Thanks..

**Comment by TimelordUK** [comment]
yes this looks to be an error it should read

```ts
   getUserTypeTable(name: string, cb:TableCb):void
```

**Comment by TimelordUK** [comment]
this is fixed please open new issue if required
