### ISSUE TITLE
dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by flaviodelgrosso** [TimelordUK/node-sqlserver-v8#215]
Hi, I'm on macOS 11.5.1 ARM64 and I'm trying to package my node application with pkg for macOS-x64 (https://www.npmjs.com/package/pkg).
In my project dependencies I have msnodesqlv8 v.2.2.0 and mssql v.7.2.0 installed.

It seems that including the sqlserverv8.node in the bundle generates this library error when I try to start the app:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object15CreationContextEv
  Referenced from: /var/folders/z1/7xys0dts0w743npnlnqt_npw0000gn/T/cebd4b365a52dbebb887a62e982742cae7b703c9660ade8ef63dc176cddc141a/sqlserverv8.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v86Object15CreationContextEv
  Referenced from: /var/folders/z1/7xys0dts0w743npnlnqt_npw0000gn/T/cebd4b365a52dbebb887a62e982742cae7b703c9660ade8ef63dc176cddc141a/sqlserverv8.node
  Expected in: flat namespace

Abort trap: 6
```
Anyone can suggest how to solve it?

Thanks in advance

**Comment by TimelordUK** [comment]
this looks to be a dynamic link error - we need the ODBC shared library as well as the MS odbcsqlv17 to be available in the link path - you will probably find links to them in /usr/lib ?

what happens if you run oTool -L on the target sqlserver.node, is it able to resolve the dependencies ?

I have not personally tried pkg on this subsystem so am unable to offer a solution.

**Comment by TimelordUK** [comment]
actually can you check with the latest binding gyp and verify if you have ODBC in your usr local lib folder. If there is dynamically linked ODBC you will see error above.

**Comment by TimelordUK** [comment]
I see I did not respond to this my apologies. Binding gyp has been simplified to support Linux Mac windows. I wonder if this Is still a problem. 

I’ll keep an eye on if any further responses here and close shortly. 

please test with latest version.

**Comment by TimelordUK** [comment]
Closing.
