### ISSUE TITLE
Run query with parameters without prepared statement

### ISSUE THREAD

**Issue by lroal** [TimelordUK/node-sqlserver-v8#217]
Is it possible to run a query and pass in an array of parameters ?
Without creating a prepared statement first.

**Comment by lroal** [comment]
I found it here:
https://github.com/TimelordUK/node-sqlserver-v8/wiki#executing-a-query

**Comment by TimelordUK** [comment]
thanks - you can also pass in a named param object if you prefer i.e.

[0] = 10, [1] = 12

or

{
  p1:10,
  p2:12
}
