### ISSUE TITLE
I am getting error in electron@14.0.0 version

### ISSUE THREAD

**Issue by TrSherlock** [TimelordUK/node-sqlserver-v8#218]
`[2840:0913/162609.777:ERROR:crashpad_client_win.cc(808)] not connected`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 4294930435`
`npm ERR! zirve_nodejs@1.0.0 start: electron .`
`npm ERR! Exit status 4294930435`
`npm ERR! `
`npm ERR! Failed at the zirve_nodejs@1.0.0 start script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
`npm ERR! A complete log of this run can be found in:`
`npm ERR!     [https://github.com/TimelordUK/node-sqlserver-v8/files/7154937/2021-09-13T14_17_18_083Z-debug.log]`

Help me please and thanks...

**Comment by idanwork** [comment]
@TrSherlock were you able to solve this?

I also got very weird errors after updating to electron 14, 14.0.1, 15.0.0 
At the moment I reverted to  "14.0.0-beta.10" which still works

**Comment by TimelordUK** [comment]
is latest version working just uploaded to NPM.  If not, will have to look into it further these binaries have all been rebuilt.

**Comment by TimelordUK** [comment]
with latest

![image](https://user-images.githubusercontent.com/7300251/134588904-399d56e8-afbe-4c67-9ac1-a6fb0787ceba.png)

```js
```

```cmd
 ➜ electron-quick-start git(master)
➜ electron-quick-start git(master) .\node_modules\.bin\electron-rebuild
√ Rebuild Complete

 ➜ electron-quick-start git(master) npm start

> electron-quick-start@1.0.0 start
> electron .
```

**Comment by idanwork** [comment]
Hi @TimelordUK  - checked with electron 15.0.0 as well and it works now
Thanks!

**Comment by TimelordUK** [comment]
Ok closing looks like this was fixed.
