### ISSUE TITLE
It works with sap (sybase) !

### ISSUE THREAD

**Issue by lroal** [TimelordUK/node-sqlserver-v8#219]
I had some trouble with https://npmjs.org/sapase, the sap/sybase lib,  so I tried node-sqlserver-v8 instead. And it worked ! 
I just replaced the driver part in the connection string with this: DRIVER=Adaptive Server Enterprise.
Does this this mean that node-sqlerver-v8 actually works against any database as long as there is a respective odbc dll in place ?
Do you see any cases where it would not work ? Except for sql dialects which needs to be dealt with by consumers of this lib.

**Comment by TimelordUK** [comment]
this is genuinely very interesting, thanks for this tip.

I had not considered this would be possible - you are right however, msnodesqlv8 is an ODBC bridge to JS and we talk to ODBC subsystem which itself loads the DB driver. So yes in theory any ODBC based driver should work.

Some features I guess would not work such as Table Value Parameters - but for reasons you already state, sandard calls should be fine.  Have you tried stored proc call for example?

thanks for this, will add to the WIKI.

**Comment by lroal** [comment]
Hello again. It only works with stored procedures if you write raw sql. It does not work with the procedureMgr().
Another thing I noticed, it does not give you the column names, but gives Column0, Column1 etc. Can anything be done with that you think ?
Example:
```
select TOP 1 _customer.id as s_customer0,_customer.name as s_customer1,_customer.balance as s_customer2,_customer.regDate as s_customer3,_customer.isActive as s_customer4,_customer.picture as s_customer5,_customer.document as s_customer6 from _customer _customer where _customer.id='a0000000-0000-0000-0000-000000000000' order by _customer.id
```
Returns: 
```
[
  {
    Column0: 'a0000000-0000-0000-0000-000000000000',
    Column1: 'George',
    Column2: 177,
    Column3: 2003-04-12T04:05:06.000Z { nanosecondsDelta: 0 },
    Column4: false,
    Column5: <Buffer af 03 08 3f ce>,
    Column6: '["foo", 1, {"bar": true}]'
  }
]
```

**Comment by TimelordUK** [comment]
I will try to install a sap sybase docker certainly we should be able to get Column names working the driver should return query meta data immediately before data it would seem either it is being overwritten or not returned at all.

**Comment by TimelordUK** [comment]
so i installed sybase the good news is I do see the same issue as you

It looks like (see attached) that the c++ driver is returning empty column names

I will have to research further as other attributes are returned fine such as type

![image](https://user-images.githubusercontent.com/7300251/155611087-c05a8b0c-1eea-42be-a206-8a1790bcce2c.png)

**Comment by TimelordUK** [comment]
ok looks like this issue is fixed easily

```js
const sql = require('msnodesqlv8')
const { GetConnection } = require('./get-connection')

const connectionString = new GetConnection().connectionString

const query = 'SELECT * FROM syscomments'

sql.open(connectionString, function (err, con) {
  if (err) {
    console.log(`failed to open ${err.message}`)
  }
  const d = new Date()
  con.query(query, function (err, rows) {
    if (err) {
      console.log(err.message)
      return
    }
    const elapsed = new Date() - d
    console.log(`rows.length ${rows.length} elapsed ${elapsed}`)
    console.log(`${JSON.stringify(rows, null, 4)}`)
  })
})

```

```bat
rows.length 42 elapsed 19
[
    {
        "id": 560001995,
        "number": 0,
        "colid": 1,
        "texttype": 0,
        "language": 0,
        "text": "create view sysquerymetrics (uid, gid, hashkey, id, sequence, exec_min, exec_max, exec_avg, elap_min, elap_max, elap_avg, lio_min, lio_max, lio_avg, pio_min, pio_max, pio_avg, cnt, abort_cnt, qtext) as select  a.uid, -a.gid, a.hashkey, a.id, a.sequence, c",
        "colid2": 0,
        "status": 0,
        "version": null,
        "partitionid": null,
        "encrkeyid": null
    },
    {
        "id": 560001995,
        "number": 0,
        "colid": 2,
        "texttype": 0,
        "language": 0,
```

**Comment by TimelordUK** [comment]
ok this should be sorted in latest version - also added manual register of stored proc so pm can be used if required.

- see release notes sample but column names should be fixed.

**Comment by lroal** [comment]
That is great news ! I just tried it, and now I get the column names. I will try the stored proc as well. I am very thankful for your quick response and action !
