### ISSUE TITLE
Using node-sqlserver-v8 inside electron 1.2.4

### ISSUE THREAD

**Issue by clooudch** [TimelordUK/node-sqlserver-v8#22]
I would like to use this module in my electron (v1.2.4) application, but unfortunately the module is not able to require the precompiled ".node" file (sqlserverv8.v6.1.0.x64.node).

Electron (v1.2.4) is using the following versions:

![image](https://cloud.githubusercontent.com/assets/15670381/16444641/58753af2-3ddf-11e6-9266-bba217b182f8.png)

I think that i have to build the c++ node addon for the correct electron version. But i have no idea if this is correct and how i have to do it.

Can someone help me please?

**Comment by clooudch** [comment]
I tried now to build msnodesqlv8 with the command `node-gyp build --version=1.2.4 --arch=x64 --dist-url=https://atom.io/download/atom-shell`.

But unfortunately i got a lot of error and warning messages:

![image](https://cloud.githubusercontent.com/assets/15670381/16450942/422adbd2-3e00-11e6-9115-0cf3594827df.png)

Am i doing someting wrong? Or is msnodesqlv8 not compatible with electron (v1.2.4)?

I would really appreciate help because i absolutely have no experience with c++ node addons.

**Comment by TimelordUK** [comment]
can you try 

1. rename bindingdotgyp.old to binding.gyp
2. find line   'defines': [ '_NODE_GYP_V4'], and remove underscore i.e. :-
3. find line   'defines': [ 'NODE_GYP_V4']

let us see if that compiles.

**Comment by clooudch** [comment]
Thank you for your help.

I already renamed `bindingdotgyp.old` to `binding.gyp`. But renaming the c++ preprocessor definition made it compile without any errors (warning messages are still there).

After compiling with the command i mentioned above i moved the resulting `.node` file into the `\livb\bin \` folder of the msnodesqlv8 module. But loading the module still not works.

The require command for the newly compiled `.node` file inside the `sqlserver.native.js` throws the error `The system cannot find message text for message number 0x%1 in message file for %2`

Did i maybe build it wrong?

**Comment by TimelordUK** [comment]
im not an expert unfortunately with electron but it looks 

https://github.com/brave/browser-laptop/issues/350

like this error is related to 64 bit / 32 bit compatibility.

"this happens if you compile a node native module as 32-bit and try to run it n 64-bit. The reverse is probably true as well."

so question is 

1. what OS are you running 64 bit / 32 bit
2. what node architecture are you on - 64 bit / 32 bit?
3. can you try and build the 32 bit version of node and see if that loads?

**Comment by clooudch** [comment]
It was all correct. I somehow messed up the compiled `.node` files. I am sorry for that. After i compiled and moved it to the correct folder again it worked like a charm.

Thank you for your fast help.

**Comment by clooudch** [comment]
The command to compile for node was actually `node-gyp build --target=1.2.4 --arch=x64 --dist-url=https://atom.io/download/atom-shell` and not like mentioned above `node-gyp build --version=1.2.4 --arch=x64 --dist-url=https://atom.io/download/atom-shell`.

I corrected it in the comment above.
