### ISSUE TITLE
node-sqlserver-v8 is not a valid 32 bit application

### ISSUE THREAD

**Issue by Bhagrot** [TimelordUK/node-sqlserver-v8#221]
node-sqlserver-v8 module works fine on my local machine but when I deploy API on remote server, I get following error
 node_modules\msnodesqlv8\build\Release\sqlserverv8.node is not a valid Win32 application.

I checked the remote server and local machine both have 64 bit operating system ("System Type").

**Comment by TimelordUK** [comment]
how are you deploying, is the binary in Release\sqlserver8.node the same size/checksum as running locally- this implies windows does not even recognise this as a valid DLL

what happen if you file <target>

```cmd
@➜ msnodesqlv8 git(master) file .\build\Release\sqlserverv8.node
.\build\Release\sqlserverv8.node: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
```

**Comment by Bhagrot** [comment]
Thanks for your reply ! I manually copied node modules on server because npm install was disabled on remote server. Today, I enabled npm install on server and install all modules using "npm install" command and now it is working fine.

**Comment by TimelordUK** [comment]
Ok closing)g this issue
