### ISSUE TITLE
How can I pass the response to the variable?

### ISSUE THREAD

**Issue by TrSherlock** [TimelordUK/node-sqlserver-v8#222]
Can you help again?
How can I pass the response to the variable?

class SqlQueries{
    constructor() {
        this.connString = `ConnectionString`
        sql.query(this.connString, 'select @@SPID as spid', (err, res)=>{
               this.resData = res
        })
    }
}

**Comment by TimelordUK** [comment]
Perhaps look to use a promise. I’m closing this issue please look at many sample code examples under javascript or one of many unit tests.
