### ISSUE TITLE
"ÇçĞğİıŞşÜü" character error in connection string...

### ISSUE THREAD

**Issue by TrSherlock** [TimelordUK/node-sqlserver-v8#226]
----- Syntax Error ----
`let ConnString = "Server=localhost\\ZRVSQL2014;Database=ÇETİNKAYALAR_2021;Uid=zirvenet;Pwd=zrvsql;Trusted_Connection=No;Driver={SQL Server Native Client 11.0}";
sql.query(ConnString, "SELECT * FROM dbo.yevmiye", (err, tableRows) => {
  if(err == "null"){
        console.log(err)
    } else {
        console.log(tableRows)
    }
})`
---- No Error -----
`let ConnString = "Server=localhost\\ZRVSQL2014;Uid=zirvenet;Pwd=zrvsql;Trusted_Connection=No;Driver={SQL Server Native Client 11.0}";
sql.query(ConnString, "SELECT * FROM ÇETİNKAYALAR_2021.dbo.yevmiye", (err, tableRows) => {
  if(err == "null"){
        console.log(err)
    } else {
        console.log(tableRows)
    }
})`

**Comment by TimelordUK** [comment]
Thanks I will try and take look seems like a Unicode issue.

**Comment by TimelordUK** [comment]
this should be fixed in git master but is not yet released - probably will be on npm within 5 days

**Comment by TrSherlock** [comment]
thank you...

**Comment by TimelordUK** [comment]
closing fixed I beieve
