### ISSUE TITLE
Error in TableMgr::getTable() for temporary tables

### ISSUE THREAD

**Issue by kuseni** [TimelordUK/node-sqlserver-v8#237]
If several temporary tables with same name in different sessions exist (for example, #t that maps in dbo.#t__________________________________________________________________________________________________________________0000000241C1 and dbo.#t__________________________________________________________________________________________________________________0000000245AF in tempdb), getTable() returns description of one of them, not exact the same that created in current connection. This is due to 
SELECT  TOP (1) ... FROM <table_catalog>.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME LIKE '<table_name>%' code in table_describe.2014.sql and table_describe.sql (getTable() -> describe() -> describeTable() -> getTableDefinition() -> query() for table_describe.2014.sql or table_describe.sql).

Wrong result of getTable() makes it impossible to use table.promises.insert() after it.

**Comment by kuseni** [comment]
I think

	WHERE TABLE_NAME = (SELECT name FROM <table_catalog>.sys.objects WHERE object_id = OBJECT_ID('<table_catalog>.<table_schema>.<table_name>')))
--	WHERE TABLE_NAME LIKE '<table_name>%')

in lines 8-9 of table_describe.2014.sql and something same in table_describe.sql looks better.

**Comment by kuseni** [comment]
It helps me to bulk insert into temporary table on MSSQL 2014, but I don't test it in other cases (normal tables, other MSSQL versions).

**Comment by TimelordUK** [comment]
i dont think there is an easy way of finding correct one

why not  use a more unique table name which will not be duplicated

```sql
select '#tmp_t_' + CAST(@@spid AS VARCHAR)
```

**Comment by TimelordUK** [comment]
Thanks yes I will test with this

**Comment by TimelordUK** [comment]
Should now be fixed thanks

**Comment by TimelordUK** [comment]
closing this now its fixed.
