### ISSUE TITLE
Can not find msnodesqlv8-v2.4.6-electron-v97-win32-x64.tar.gz

### ISSUE THREAD

**Issue by Billy-ZGJ** [TimelordUK/node-sqlserver-v8#238]
I got this error msg in electron-builder:

• install prebuilt binary  name=msnodesqlv8 version=2.4.6 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=msnodesqlv8
                                          version=2.4.6
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 7.0.1
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds\msnodesqlv8-v2.4.6-electron-v97-win32-x64.tar.gz
    prebuild-install info looking for cached prebuild @ C:\Users\guojun.zhang\AppData\Roaming\npm-cache\_prebuilds\865556-msnodesqlv8-v2.4.6-electron-v97-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.6/msnodesqlv8-v2.4.6-electron-v97-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.6/msnodesqlv8-v2.4.6-electron-v97-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=14.2.6 runtime=electron arch=x64 libc= platform=win32)

I checked the assets in release list, and found no v97 supported. But 
![image](https://user-images.githubusercontent.com/11631088/157391483-82cce2c1-00e6-4db9-9380-a24cb03d04fd.png)

Show, the electron 14.2.6 is base V97.
I want know, why there is no V97 in the asset list, and could you put one V97 asset in the release list?

**Comment by Billy-ZGJ** [comment]
@TimelordUK

**Comment by TimelordUK** [comment]
Thanks I will take a look to see why it is missing

**Comment by TimelordUK** [comment]
please check again these have now been uploaded

**Comment by Billy-ZGJ** [comment]
@TimelordUK  Thanks!!
