### ISSUE TITLE
Add an encrypt option to generated sequelize connection string

### ISSUE THREAD

**Issue by wkrasnicki-vizlib** [TimelordUK/node-sqlserver-v8#239]
Hi, we are using Sequelize in our project together with Tedious, but decided to migrate to your library. After looking at the sequelize code, I noticed that the generated connection string does not contain an `Encrypt=#{encrypt};` part, which we would really like to have. It is a simple fix and I wanted to create a PR for that, but your CLA link is not working :/

As a side note, the sequelize example in the wiki seems to be out of date, as I had to pass most options in `dialectOptions.options` on Sequelize v5. I also don't understand the relative import in the readme and there is no info what options are supported, I had to look at the code for that.

**Comment by TimelordUK** [comment]
I don’t believe this is still an issue ?  I will close shortly if nothing further reported

**Comment by TimelordUK** [comment]
Closing
