### ISSUE TITLE
Passing XML over 2000 characters long to stored procedure results in "[Microsoft][SQL Server Native Client 11.0]Invalid precision value"

### ISSUE THREAD

**Issue by davewthompson** [TimelordUK/node-sqlserver-v8#24]
Hey there,

I have noticed that trying to pass a XML string of over 2000 characters to a stored procedure as a parameter results in SQL returning "[Microsoft][SQL Server Native Client 11.0]Invalid precision value".

I suppose it's being truncated, but I can't find a way to stop this happening?

I'm just using:

 `procManager.callproc('SEL_GetDataByXml', parameters, function (err, result) {`
 
Any advice?

Thanks!

Dave

**Comment by TimelordUK** [comment]
Have you tried

sql.WLongVarChar(xml);

As the xml parameter in Param array. 

Is param[0] =sql.WLongVarChar(xml); 

This should force the driver to bind the string

I'm away from terminal so cannot test currently. 

I'll take a look later to see if this will fix it.

**Comment by TimelordUK** [comment]
function largeText() {
    console.log("largeText");
    var len = 2200;
    var s = "A".repeat(len);
    sql.open(connStr, function (err, conn) {
        conn.query("declare @s NVARCHAR(MAX) = ?; select @s as s", [sql.WLongVarChar(s)], function (err, res) {
            //conn.query("declare @s NVARCHAR(MAX) = ?; select @s as s", [s], function (err, res) {
            assert.ifError(err);
            var ss = res[0].s;
            assert(ss.length == len);
        });
    });
}

**Comment by davewthompson** [comment]
That's how I got it to work in the end - sql.WLongVarChar(s)!

Thanks very much!

Dave
