### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by miquik** [TimelordUK/node-sqlserver-v8#240]
Hello everybody,
in lib/pool.js around line 456, in case of catch you call `cb(e, null)` but you should check if "cb" is not null: `if (cb) { cb(e, null) }` isn't it?

**Comment by TimelordUK** [comment]
Thanks a lot I will fix this.

**Comment by TimelordUK** [comment]
Should now be fixed thanks

**Comment by TimelordUK** [comment]
closing- fixed
