### ISSUE TITLE
How to set Application Name for the connection requests initiated?

### ISSUE THREAD

**Issue by SaloniSonpal** [TimelordUK/node-sqlserver-v8#25]
Hi @TimelordUK ,
I'm using the Microsoft's driver [node-sqlserver ](https://github.com/Azure/node-sqlserver) for connecting to Azure SQL Database from lower versions of Node. But to connect from newer versions of Node.js I was trying to use this module. How can I set the Application Name to identify that the connection request coming from node-sqlserver-v8?

**Comment by TimelordUK** [comment]
Driver={SQL Server Native Client 11.0}; Server=np:\\.\pipe\LOCALDB#8704E301\tsql\query; Database={scratch}; Trusted_Connection=Yes; APP=msnodesqlv8

will this help? i..e APP=<appname>

**Comment by SaloniSonpal** [comment]
Got it, @TimelordUK . It will have to be specified by user, and hence it won't be standardized. What are your thoughts on changing the default value for the driver? That way users can easily filter on that app name to distinguish it.

**Comment by TimelordUK** [comment]
can you not try something that creates an app from say the username 

var app = 'sqlv8-' + process.env.USERNAME;

var driver = '.......; APP=' + app;

there is no reason you have to use the example given it was just for illustration.  Simply use any suitable value that is probably dependent on a user of your system like login.
