### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by SSIvanov19** [TimelordUK/node-sqlserver-v8#253]
Hi,
I am trying to deploy my project to Azure Web App with Linux. But when i try to run my code i get the following error:
```
Error: /home/site/wwwroot/node_modules/msnodesqlv8/build/Release/sqlserverv8.node: invalid ELF header
```

I am installing the node modules from the Azure Machine.
Also I have installed the"ODBC driver 17 for sql server".

**Comment by TimelordUK** [comment]
Any of this relevant 

https://stackoverflow.com/questions/29994411/invalid-elf-header-when-using-the-nodejs-ref-module-on-aws-lambda/29994851#29994851

**Comment by SSIvanov19** [comment]
I am 99% sure that all of the node modules are installed in the Azure Web App and therefore they are built on Linux.
