### ISSUE TITLE
Node 18 x86 support

### ISSUE THREAD

**Issue by dhensby** [TimelordUK/node-sqlserver-v8#258]
I'm trying to run builds on Node 18 (x64 and x86). The x64 builds are working fine, but on x86 the bindings fail to compile, (see: https://ci.appveyor.com/project/tediousjs/node-mssql/build/job/nopaeqohp8qb44qm). If I'm honest, the error is slightly lost on me, but I do note it appears to be trying to build AMD64 bindings and I also note that when looking for python it's loading x64 version, which may be a problem too...

This could be a (build) environment problem, but I thought I'd raise it here just in case you had any insight.

---

related: https://github.com/tediousjs/node-mssql/pull/1417

**Comment by TimelordUK** [comment]
hello thanks for heads up on this issue - looks like we forgot to upload 32 bit version node 18

it is now built and uploaded to this release so please try again.

**Comment by dhensby** [comment]
Great, thanks - it's working now :)
