### ISSUE TITLE
"COUNT field incorrect or syntax error" when string reaches a certain length during an insert?

### ISSUE THREAD

**Issue by skiplogic** [TimelordUK/node-sqlserver-v8#27]
Is there a byte length limit for values in an insert, or for the entire array during an insert? The following loop fails when value.length > 2000...

```
/* table structure:

USE [bn_dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ntextTest](
  [testme] [ntext] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
*/

var sql = require('msnodesqlv8');
var conn_str = "Driver={SQL Server Native Client 11.0};Server=(local);Database=bn_dev;Trusted_Connection={Yes}";

value = 'x';
q='insert into ntextTest values ( ? )';
didIFail=false;
times=0;
while(times<335) {
   sql.query(conn_str, q, [value], function (err, results) { if(err){ console.log(err); } });
   value = value + '+x+x+x';
   times = times+1;
}

/* output:

$ node load_test.js
{ Error: [Microsoft][SQL Server Native Client 11.0]COUNT field incorrect or syntax error
    at Error (native) sqlstate: '07002', code: 0 }

*/

```
`

**Comment by TimelordUK** [comment]
What happens if you use sql.WLongVarChar(value) .....

**Comment by skiplogic** [comment]
That works perfectly, thanks!

**Comment by Jeff-14159** [comment]
I was getting invalid precision type HY104 (msnodesql v0.1.46) I've since updated to v0.2.10 and now I'm getting this new error message 07002. How does one use the "WLongVarChar" in the above example?

Thanks,
Jeff

**Comment by TimelordUK** [comment]
if you are using  a very large string as a parameter

 sql.query(conn_str, q, [**sql.WLongVarChar(value)**], function (err, results) { if(err){ console.log(err); } });

should force the driver to use the correct type .... please provide the example you are trying if this does not work correctly.

**Comment by Jeff-14159** [comment]
Thanks for explaining working great now.  :+1:

**Comment by Jeff-14159** [comment]
Update:  I think I might have found a possible cause of this issue.... it would appear that it may not be counting the whitespace/newline characters properly to determine if the type should be a WLongVarChar

I have been able to test this by preforming a count on the sting I'm passing in if it is under 2000 including whitespace then no problem, how ever if the character count is like 1800 + 300 whitespaces then it will error until the character count goes over 2000 then it will start working again.....

In my case I'm storing some html and js into the database for dynamic offline content those naturally have lots of white space from the editor..... and I have a base sql update/insert function so for now I'm checking if length is over 2000 during my query builder and parameterizing process

`// data: {uuid: 'unique id', col1Name: 'string', col2Name: 'string', col3Name: 'string'};`
`// dataProps: ['uuid', 'col1Name', 'col2name']  // is an array of filtered propNames to update`

`var updateQuery = "UPDATE [dbo].[" + tableName + "] SET ";`
`var updateQueryPrams = [];`
`for (var i = 0; dataProps.length > i; i++) {`
`     ``if (dataProps[i] != "uuid") { // exclude the uuid`
`     ``     ``updateQuery += dataProps[i] + "= ?,";`
**`     ``     ``if (data[dataProps[i]] && data[dataProps[i]].length > 2000) {`**
**`       ``    ``    ``updateQueryPrams.push(sql.WLongVarChar(data[dataProps[i]]));`**
**`    ``      ``} else {`**
**`      ``     ``    ``updateQueryPrams.push(data[dataProps[i]]);`**
**`    ``      ``}`**
`   ``}`
`updateQuery += "lastUpdated = CURRENT_TIMESTAMP";`
`updateQuery += " where uuid= ?";`
`updateQueryPrams.push(data.uuid);`

`sql.query(connStr[database], updateQuery, updateQueryPrams, function (err) {........`

Thanks,
Jeff

**Comment by CycoPH** [comment]
I've had this problem when calling a stored procedure.  No spaces in the text being stored, but if the text has between 2048 and 8192 characters long then the driver wouth throw an error and go into a completely non-responsive state.

I made sure that my input variables to the stored proc (TEXT) are cast like this:
sql.engine.Text(data.json, data.json.length)

Giving it the correct length right at the beginning makes it work

**Comment by philbardem** [comment]
I am having the same issue. This is how I'm calling my stored procedure
```
const sql = require("mssql/msnodesqlv8")

module.exports = (req, res, next) => {
    var request = new sql.Request(connection)
    request.input("id", sql.Int, req.params.id)
    request.input("page_content", req.body.page_content)
    request.execute("editpage", function(err, rs){
        if (err) console.log(err)
        next()
    })
}
```
I tried adding request.input("page_content", sql.WLongVarChar(65000), req.body.page_content)
and I am getting "sql.WLongVarChar is not a function" error. Any adjustments I can make to get this to work? It appears the problem (like Jeff mentions above) happens only between 2000 and 8000 characters or so.

**Comment by TimelordUK** [comment]
Yes the method in question only shows up on the msnodesqlv8 driver itself so you are talking to the wrapper abstraction. I will try to address issue in driver so calling this method is no longer necessary.

**Comment by philbardem** [comment]
Awesome. Appreciate your help.

**Comment by ralfkuh** [comment]
I have the same problem, is there a fix coming?

**Comment by TimelordUK** [comment]
I will try and take a look and get back to you

**Comment by TimelordUK** [comment]
I believe this is now fixed so will close. Please reopen if still an issue.

**Comment by hobord** [comment]
I have the same problem. on 0.6.6...

**Comment by TimelordUK** [comment]
Can you provide an actual query which fails ? I’ll fix it as soon as possible I thought I added a unit test for this specifically.

**Comment by TimelordUK** [comment]
In fact under params.js unit tests line 143 I have a test which sends the exact sql mssql uses for a string length of 2001?
