### ISSUE TITLE
Kerberos Auth: Not Using Instance Name While Looking For SPN

### ISSUE THREAD

**Issue by Qualatea** [TimelordUK/node-sqlserver-v8#273]
Hello, there

I ran into an issue using Kerberos auth.  While using it on unnamed instances it works. While using a named instance it doesn't as kerberos is looking for an SPN without the named instance. When I try the same connection string with windows locally it works, so the string shouldn't be an issue. 
My connection string looks like this:
'Driver={ODBC Driver 17 for SQL Server};Server=server.domain.net\\instance_name;Trusted_Connection=yes;'
The kerberos returns a log trace without the instance name:
Requesting tickets for MSSQLSvc/server.domain.net:58075@DOMAIN.NET
The SPN on the server should be correct as our dotnet apps have no issue. It just looks like somewhere in the process the instance name got lost as kerberos is not using it to look for the server. 
The node's error is:
`ConnectionError: Error: [Microsoft][ODBC Driver 17 for SQL Server] SSPI Provider: Server not found in Kerberos database,Error: [Microsoft][ODBC Driver 17 for SQL Server] Cannot generate SSPI  at /app/node_modules/mssql/lib/msnodesqlv8/connection-pool :56:17 at Immediate.<anonymous> (/app/node_modules/msnodesqlv8/lib/connection.js:147:15) at process.processImmediate (node:internal/timers:471:21) {  code: }`

Any help would be appreciated.

Thanks

**Comment by TimelordUK** [comment]
does this keyword work?

https://learn.microsoft.com/en-us/sql/relational-databases/native-client/odbc/service-principal-names-spns-in-client-connections-odbc?view=sql-server-ver16



<html>
<body>


A client application using the current version of SQL Server Native Client specifies an SPN in the connection string as a domain user or computer account, as an instance-specific SPN, or as a user-defined string. | The ServerSPN keyword can be used in a provider, initialization, or connection string to do the following:-Specify the account used by the SQL Server instance for a connection. This simplifies access to Kerberos authentication. If a Kerberos Key Distribution Center (KDC) is present and the correct account is specified, Kerberos authentication is more likely to be used than NTLM. The KDC usually resides on the same computer as the domain controller.-Specify an SPN to look up the service account for the SQL Server instance. For every SQL Server instance, two default SPNs are generated that can be used for this purpose. These keys are not guaranteed to be present in Active Directory, however, so in this situation Kerberos authentication is not guaranteed.-Specify an SPN that will be used to look up the service account for the SQL Server instance. This can be any user-defined string that maps to the service account. In this case, the key must be registered manually in the KDC and must satisfy the rules for a user-defined SPN.The FailoverPartnerSPN keyword can be used to specify the SPN for the failover partner server. The range of account and Active Directory key values is the same as the values you can specify for the principal server.
-- | --



</body>
</html>

**Comment by Qualatea** [comment]
Genius, looks like my Googling skills need some work. Thanks, using the ServerSPN parameter fixed it.
