### ISSUE TITLE
"Invalid precision value" in QueryOperation::bindString

### ISSUE THREAD

**Issue by heroboy** [TimelordUK/node-sqlserver-v8#3]
Maybe varchar(0) is a invalid type in sqlserver. So if input string is empty, it will throw "Error: [Microsoft][ODBC SQL Server Driver]Invalid precision value".
So change the code like:
```
binding.param_size = str_len==0?1:str_len;
```

**Comment by TimelordUK** [comment]
OK, thanks I will look to patch with a fix.  I appreciate pointing out this issue.

**Comment by TimelordUK** [comment]
this has been resolved in latest version, hence I will close.  Thanks for raising.
