### ISSUE TITLE
Prebuilt binaries for Node 20 / alpine

### ISSUE THREAD

**Issue by lroal** [TimelordUK/node-sqlserver-v8#302]
I tried it on Node 20 with node:20-alpine Docker image without success.
It doesn't find the binaries, and then tries to build it. I haven't tested it with Python 3 pre-installed though.
The github action where it fails: https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979

**npm install output:**

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.3',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.6.0', npm: '9.8.1' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /__w/rdb/rdb/node_modules/msnodesqlv8
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=20.6.0 runtime=node arch=x64 libc=musl platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@20.6.0 | linux | x64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:1[5](https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979#step:16:6)9:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:202:1[6](https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979#step:16:7))
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:2[8](https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979#step:16:9))
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:2[9](https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979#step:16:10)2:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:484:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Linux 5.15.0-[10](https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979#step:16:11)41-azure
npm ERR! gyp ERR! command "/usr/local/bin/node" "/__w/rdb/rdb/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /__w/rdb/rdb/node_modules/msnodesqlv8
npm ERR! gyp ERR! node -v v[20](https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979#step:16:21).6.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by TimelordUK** [comment]
node-sqlserver-v8/docker/alpine-msnodesqlv8 at master · TimelordUK/node-sqlserver-v8github.comHave you tried building this alpine docker image which should work as a starting point Sent from my iPadOn 11 Sep 2023, at 14:58, Lars-Erik Roald ***@***.***> wrote:﻿
I tried it on Node 20 with node:20-alpine Docker image without success.
It doesn't find the binaries, and then tries to build it. I haven't tested it with Python 3 pre-installed though.
The github action where it fails: https://github.com/alfateam/rdb/actions/runs/6147258493/job/16678329979
npm install output:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: ***@***.******@***.***',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.6.0', npm: '9.8.1' }
npm WARN EBADENGINE }
npm WARN deprecated @***@***.***: This functionality has been moved to @npmcli/fs
npm WARN deprecated ***@***.***: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /__w/rdb/rdb/node_modules/msnodesqlv8
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=20.6.0 runtime=node arch=x64 libc=musl platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using ***@***.***
npm ERR! gyp info using ***@***.*** | linux | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder. (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/__w/rdb/rdb/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:484:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Linux 5.15.0-1041-azure
npm ERR! gyp ERR! command "/usr/local/bin/node" "/__w/rdb/rdb/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /__w/rdb/rdb/node_modules/msnodesqlv8
npm ERR! gyp ERR! node -v v20.6.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by TimelordUK** [comment]
Above was a reply on email

https://github.com/TimelordUK/node-sqlserver-v8/blob/master/docker/alpine-msnodesqlv8/Dockerfile

this is a working alpine docker which could be a start

**Comment by lroal** [comment]
Thank's I will have a look
