### ISSUE TITLE
`ConcreteColumnType.parseSS` method tampers with plain date strings

### ISSUE THREAD

**Issue by gulshan** [TimelordUK/node-sqlserver-v8#318]
The `ConcreteColumnType.parseSS` [method](https://github.com/TimelordUK/node-sqlserver-v8/blob/master/lib/user.js#L78) in `user.js` file uses the RegExp value `/(\d?\d)$/g`. This matches any regular date strings like `2020-01-01`. When the match is found the value of the parameter is changed to ~`1900-01-01`.

Please check this and make necessary corrections. Thanks in advance.

**Comment by gulshan** [comment]
I have made this temporary change to make plain date strings work in user.js file-
```js
      parse (s) {
        if (!this.parseHHMMSS(s) && !this.parseMMSS(s) /*&& !this.parseSS(s)*/) {
          this.value = new Date(s)
        }
      }
```

**Comment by TimelordUK** [comment]
no tests break with this change, so i have merged it - thanks

**Comment by gulshan** [comment]
Thank you for checking this. Closing the issue.
