### ISSUE TITLE
Stored proc with BigInt output parameter does not work

### ISSUE THREAD

**Issue by CycoPH** [TimelordUK/node-sqlserver-v8#32]
As a simple test case:
create PROCEDURE bigint_test 
	@a bigint = 0, 
	@b bigint = 0 output
AS
BEGIN
	set @b = @a
	select @b as b
END
GO

When you call this via the stored proc manager:
pm.callproc("bigint_test", [1234567890], function (err, results, output) {
				console.log("err", err);
				console.log("results", results);
				console.log("output", output);
			});

You get the following:
err null
results [ { b: 1234567890 } ]
output [ 0, null ]

So the "b" output parameter does not get assigned correctly

**Comment by TimelordUK** [comment]
thanks for letting me know, I will test it out and report back - we may be able to kludge it with one of the sql.xxxx mapping paramater calls such as [sql.BigInt(1234567890)] but im not at a terminal to check right now.

**Comment by TimelordUK** [comment]
it does look like an issue in actual fact.  I will get back in next day or 2 with hopefully a fix, looks like the c++ itself has a problem.

**Comment by TimelordUK** [comment]
please try again with 0.2.15

**Comment by CycoPH** [comment]
It works :)
Thank you
