### ISSUE TITLE
Missing binaries for Electron v28 and v29

### ISSUE THREAD

**Issue by rbolink** [TimelordUK/node-sqlserver-v8#324]
I'm building an Electron app (v29.3.1) using the [Electron builder](https://github.com/electron-userland/electron-builder) package. However, when doing this I'm getting the following error:

![afbeelding](https://github.com/TimelordUK/node-sqlserver-v8/assets/97297286/fde92574-6eb2-47d3-862d-f7a0fc885d0d)

It seems like binaries for Electron v28 and v29 are missing when looking at the [releases](https://github.com/TimelordUK/node-sqlserver-v8/releases). Will these be added anytime soon?

**Comment by TimelordUK** [comment]
v28 does not compile and that wont be looked at any time soon - v29, v30 both seem to compile I will release binaries for these shortly in coming day or so

**Comment by rbolink** [comment]
@TimelordUK I saw that you released `v4.2.0` of the package. However, when looking at the files that belong to this tag it seems like the new changes are not included. The `package.json` also contains `version: 4.1.2` instead of `version: 4.2.0`. Did something go wrong during the release or am I just too impatient?

**Comment by TimelordUK** [comment]
I’ll check tonight. The binaries should be attached to the release the tar gz.  I have not released anything to nom presently.

**Comment by TimelordUK** [comment]
i recreated release, i will push to npm in a day or so - v29,v30 should be working on this release

**Comment by rbolink** [comment]
@TimelordUK Thanks! Will close this issue if the release is working

**Comment by rbolink** [comment]
@TimelordUK It all seems to work, so I'm closing the issue. Thanks for adding the binaries on this short term!

**Comment by rbolink** [comment]
@TimelordUK It all seems to work, so I'm closing the issue. Thanks for adding the binaries on this short term!
