### ISSUE TITLE
Missing binaries for 4.x

### ISSUE THREAD

**Issue by ratanaklun** [TimelordUK/node-sqlserver-v8#33]
Binaries are missing for 4.x. Is it still supported?

**Comment by TimelordUK** [comment]
Yea it should be my apologies I will sort it out very shortly. In interim is it possible to copy previous binary versions into folder the library should work on previous. Or roll back 

Sorry about that it will be fixed within next 12 hrs.

**Comment by TimelordUK** [comment]
this should now be resolved. on 0,2.13

**Comment by TimelordUK** [comment]
thanks for raising this, sorry about that.   I will now close as these are back.

**Comment by ratanaklun** [comment]
Thanks!
