### ISSUE TITLE
Query field string result split as array

### ISSUE THREAD

**Issue by patriksimek** [TimelordUK/node-sqlserver-v8#37]
Hi @TimelordUK, I was wondering if you could help me solve https://github.com/patriksimek/node-mssql/issues/451. I was able to reproduce the behavior mentioned in the issue and I'm not sure whether this is a feature or bug? I can quite easily merge those string on my side but before I do that, I'm first asking you about our opinion there. Thank you.

**Comment by TimelordUK** [comment]
Ok i will take a look at it. Time is a bit of an issue currently i will at least try to verify what's going on. Thanks for heads up.

**Comment by robertmirro** [comment]
Is this issue still be considered for a potential fix?

**Comment by TimelordUK** [comment]
hello, we will need to see how the mssql driver is interacting with msnodesqlv8.

by that I mean, for a very large string it does get read in chunks from the C++ driver and re-assembled by the javascript before the callback is made.  I have already checked for your demo string you provided, this works as expected. 

If you were to write a test script that called msnodesqlv8 with the conn.query(sql, ......) it should work as expected.  If that is the case we will need to see how mssql is reading data from the driver, if it uses queryRaw etc.

currently I have no way of reproducing this issue with msnodesqlv8 isolated and run on its own.  I would have to check out the mssql code and run your query through that to see what is going on.

**Comment by TimelordUK** [comment]
Ok i think reading patriksimek/node-mssql#451. again he is actually using the 

q = sql.(.....)
.on('column', c=> {
}) 

api - I will check tonight but this almost certainly would generate multiple callbacks on the event as the C++ sends back chunks.   I will look to see how invasive it would be to change this behaviour, i was under impression it was on the callback from the query which i really would have found hard to understand.

I am working on branch "tvp" at the moment for table value parameters into stored procedures, so I will see if i can add a change to this release.

**Comment by robertmirro** [comment]
Hi and thanks for the prompt response!

I also noticed [the example in #451](https://github.com/patriksimek/node-mssql/issues/451) is using streaming.  

I'm seeing the array/split behavior without streaming with/without windows authentication:
```js
const db = new sql.ConnectionPool(...);
const data = await db
    .request()
    .input()
    .query('SELECT <varchar(max) field that is more than 8192 bytes> FROM...');
```
BTW...  The SP/tvp functionality would be awesome!  We are releasing code soon that will be refactored to use it when it's available.

**Comment by TimelordUK** [comment]
is it possible to checkout the tvp branch and check this against your code above?

**Comment by TimelordUK** [comment]
this is now fixed on latest version 0.4.5

**Comment by robertmirro** [comment]
Great!  Thanks!

**Comment by TimelordUK** [comment]
guys i am now closing this issue as I believe it to be resolved on latest version.  Thanks for bringing it to my attention.
