### ISSUE TITLE
Build for node v8.0.0

### ISSUE THREAD

**Issue by fuchanglin** [TimelordUK/node-sqlserver-v8#40]
Hi, 
    Is there any guide for building the binary for specific Node version like v8.0.0 ?

Thanks!

**Comment by TimelordUK** [comment]
The latest version of the library should support node 8 out there box. Generally speaking once the library is compiled against a major version of node it should remain compatible with all minor revisions. 

I have included some instructions on the wiki how to compile the code. It can be done with express edition 2015 visual studio or even the build tools 2015. Note currently vs2017 does not seem to be supported. 

Node-gyp is the npm sub system that drives all this. If you install this globally against your desired version of node it's a case of them generating the solution file and compiling the code. 


https://github.com/TimelordUK/node-sqlserver-v8/wiki#compiling

If you have any issues report back. Take a look in tools I use the build little bat script but as you see it is not a complex process.

**Comment by fuchanglin** [comment]
That's very helpful, thank you !

**Comment by TimelordUK** [comment]
thanks your welcome. closing this one.
