### ISSUE TITLE
Issue while inserting long strings

### ISSUE THREAD

**Issue by dNitro** [TimelordUK/node-sqlserver-v8#42]
Using this driver when i try to insert long strings in sql server tables whose columns set to `nvarchar(max)` through stored procedures via [`mssql`](https://github.com/patriksimek/node-mssql) client and setting input type to sql.NVarChar(sql.MAX), for long wkt text it gets:
```
Error:  String or binary would be truncated
```
and for other long strings it gets:
```
Error: Invalid precision value
```
and no insertion; But using tedious driver it works flawlessly with the same values.
I use your driver because of windows auth support but i have to make a sql login to use tedious.

**Comment by TimelordUK** [comment]
hello, have you tried this ?

https://github.com/TimelordUK/node-sqlserver-v8/wiki#strings

function largeText() {
    var len = 2200;
    var s = "A".repeat(len);
    sql.open(connStr, (err, conn) => {
        conn.query("declare @s NVARCHAR(MAX) = ?; select @s as s", [sql.WLongVarChar(s)],  
        (err, res) => {
            assert.ifError(err);
            var ss = res[0].s;
            assert(ss.length == len);
        });
    });
}

I intend to fix this in the driver, it is due to the selection of the type used in column binding being incorrect for large strings, this forces driver to use given one.

**Comment by dNitro** [comment]
Well, should do more search on this ;) seems this workaround is work fine and though officially not supported,  mssql has a [specific branch](https://github.com/patriksimek/node-mssql/issues/438) to use WLongVarChar datatype. So i close the issue hoping to fix in the driver. Thank you.
