### ISSUE TITLE
Issue with production build installing electron

### ISSUE THREAD

**Issue by CycoPH** [TimelordUK/node-sqlserver-v8#43]
Would it be possible to remove the dependency on electron when you do a production npm install.

**Comment by TimelordUK** [comment]
Sure i can do this as part of next patch release shortly.

**Comment by TimelordUK** [comment]
to confirm you think it best I remove electron completely from the package.json file? to be honest I included it for dev purposes, it is not necessary for me to have it even in the devDependencies where it lives presently?

**Comment by CycoPH** [comment]
It can be in the dev package.  Just when you do npm install for a production system it still installs electron.

the line:
"@types/electron": "^1.4.31",
in dependencies should only be in devDependencies

**Comment by TimelordUK** [comment]
thanks for confirmation, I have removed this and it is released on latest version 0.3.2

**Comment by TimelordUK** [comment]
closing, thanks for bringing to my attention.
