### ISSUE TITLE
Date Off By One Day

### ISSUE THREAD

**Issue by raquila** [TimelordUK/node-sqlserver-v8#44]
I'm having an issue pulling the correct datetime value. For example, the value in the database is 2009-05-27 00:00:00.000 but when I view the query results, the value is Tue May 26 2009 20:00:00 GMT-0400 (Eastern Daylight Time).  How can I pull exactly what is in the database?

**Comment by TimelordUK** [comment]
What is exact column definition being used in database. Ideally I need a unit test such as the ones already defined for dates in test/dates.js

Is it a datetimeoffset ?

**Comment by raquila** [comment]
The column data type is a datatime.  The database is local so the time zones are the same.  Here is an example where the result is Tue May 26 2009 20:00:00 GMT-0400 (Eastern Daylight Time) instead of 5/27/2009.  I want to make sure that no matter what time zone the client is in, I get back 5/27/2009.

var msnodesql = require('msnodesqlv8');
msnodesql.open(connection_string, function (err, conn) {
            if (err) return console.error(err);
            conn.query("select convert(datetime, '2009-05-27 00:00:00.000') as test_field", function (err, res) {
                console.log(res);               
            });
		});

**Comment by TimelordUK** [comment]
I have changed my time zone even and I currently cannot reproduce this issue

I am running on a locally installed instance of sqllocaldb

msnodesqlv8\test\edge-case.js -t datetz
Driver={SQL Server Native Client 11.0}; Server=np:\\.\pipe\LOCALDB#C7C00B16\tsql\query; Database={scratch}; Trusted_Connection=Yes;

**select convert(datetime, '2009-05-27 00:00:00.000') as test_field**
[1] more = false err null results [{**"test_field":"2009-05-27T00:00:00.000Z"**}]
[1] completes more = false

select convert(datetime, '2009-05-27 00:00:00.000') as test_field
[2] more = false err null results [{"test_field":"2009-05-27T00:00:00.000Z"}]
[2] completes more = false

**Comment by raquila** [comment]
Could it be a daylight savings issue?  Do you provide a 'use UTC' option?  This is exactly the same problem
https://stackoverflow.com/questions/7556591/javascript-date-object-always-one-day-off

**Comment by TimelordUK** [comment]
thats a fantastic link , certainly seems closely related to this issue

out of interest can you manipulate it back to what you want with something like below

new Date( doo.getTime() - doo.getTimezoneOffset() * -60000 ) );

where doo is the date returned by the library.

**Comment by TimelordUK** [comment]
actually looking at the driver code, i can see a potential issue, the question is how to safely fix it, we probably need as you say a way to switch the time zone adjustment on and off as it looks like I map from the database in c++ to a struct and assume timezone_hour and timezone_minute is 0 - so at that point it would translate the date I guess back. 

	void TimestampColumn::MillisecondsFromDate(TIMESTAMP_STRUCT const & ts)
	{
		SQL_SS_TIMESTAMPOFFSET_STRUCT timeStruct;
		timeStruct.year = ts.year;
		timeStruct.month = ts.month;
		timeStruct.day = ts.day;
		timeStruct.hour = ts.hour;
		timeStruct.minute = ts.minute;
		timeStruct.second = ts.second;
		timeStruct.fraction = ts.fraction;
		**timeStruct.timezone_hour = 0;
		timeStruct.timezone_minute = 0;**
		MillisecondsFromDate(timeStruct);
	}

it looks like the code does translate something like below i.e. the datetimeoffset type will be offset by the provided tz information.  But what I do not do in the driver is offset a datetime by the current timezone - which clearly would have to be optiional as i dare say this is not always desired.

DECLARE @datetimeoffset datetimeoffset(4) = '1912-10-25 12:24:32.1277 +10:0';  
DECLARE @datetime2 datetime2(3)=@datetimeoffset;  
SELECT @datetimeoffset AS '@datetimeoffset', @datetime2 AS '@datetime2';

**Comment by raquila** [comment]
Yes I believe an option would be best.  I asked about the useUTC option because I tried using your driver through https://github.com/patriksimek/node-mssql and there is an option to set useUTC to false but it doesn't seem to do anything.  If you could add that option to your library I think that would solve my problem.

**Comment by TimelordUK** [comment]
Do I assume the insert is OK i.e. if you insert a date column it ends up in the database as you intended or does it also translate that by the tz.  I am trying to work out if I need to add this in both directions

**Comment by raquila** [comment]
The application I'm using this library in is a read only database application.  So I'm not concerned about inserts, but I would think if the option is set to use utc then no translation.  Which would be the default.

**Comment by raquila** [comment]
Do you have a version that I can test pulling data with?

**Comment by TimelordUK** [comment]
I am working on this . It is proving to be a tricky change as this translation is buried deep in the driver and i need to make sure it behaves exactly the same if flag is not changed from default true.

**Comment by TimelordUK** [comment]
are you able to check out branch "strings" from git hub ?

there is a new method on the connection 

conn.setUseUTC(false); // switch off utc translate

it will then offset the datetime returned by the local TZ which should bring it back to as you require.

or you can use 

``` javascript
var msnodesql = require('msnodesqlv8');
msnodesql.open(connection_string, function (err, conn) {
if (err) return console.error(err);
conn.query(sql.TzOffsetQuery("select convert(datetime, '2009-05-27 00:00:00.000') as test_field"), function (err, res) {
console.log(res);
});
});
```

``` javascript
class DateTz {
    run(conn_str, argv) {
        let delay = argv.delay || 5000;
        console.log(conn_str);
        exports.sql.open(conn_str, (err, conn) => {
            if (err) {
                throw err;
            }
            let x = 1;
            if (err) {
                throw err;
            }
            conn.setUseUTC(false);
            let expected = new Date('2009-05-27 00:00:00.000');
            setInterval(() => {
                let qs = `select convert(datetime, '2009-05-27 00:00:00.000') as test_field`;
                console.log(qs);
                let q = conn.query(qs, (err, results, more) => {
                    console.log(`[${x}] more = ${more} err ${err} results ${JSON.stringify(results)}`);
                    assert.deepEqual(results[0].test_field, expected);
                    if (more)
                        return;
                    console.log(`[${x}] completes more = ${more}`);
                    ++x;
                });
                q.on('msg', (err) => {
                });
            }, delay);
        });
    }
}
```

**Comment by raquila** [comment]
It looks like '2009-05-27 00:00:00.000' works as expected but '2010-01-21 00:00:00.000' does not return the expected result.

var msnodesql = require('msnodesqlv8');
msnodesql.open(connection_string, function (err, conn) {
            if (err) return console.error(err);
			conn.setUseUTC(false); 
            conn.query("select convert(datetime, '2010-01-21 00:00:00.000') as test_field", function (err, res) {
                console.log(res);               
            });
		});
Result :		
Wed Jan 20 2010 23:00:00 GMT-0500 (Eastern Standard Time)

**Comment by TimelordUK** [comment]
Ok thanks. The translation is not constant.  I will change it to map in JavaScript rather than the cpp that will be easier to debug. I will patch the branch.

**Comment by TimelordUK** [comment]
can you pull strings branch again and try - this needs to be cleaned up a little I am now patching the date filed in the javascript.

**Comment by raquila** [comment]
Got an error
Uncaught TypeError: Cannot read property 'getTime' of null
    at queued_onReadColumn (C:\temp\ff\client\node_modules\msnodesqlv8\lib\driverRead.js:109)
    at Immediate.<anonymous> (C:\temp\ff\client\node_modules\msnodesqlv8\lib\driverRead.js:47)
    at runCallback (timers.js:672)
    at tryOnImmediate (timers.js:645)
    at processImmediate [as _immediateCallback] (timers.js:617)

**Comment by TimelordUK** [comment]
yes sorry about that .... can you pull and try that?

**Comment by raquila** [comment]
That fixed it thanks.

**Comment by raquila** [comment]
When do you think you will release this version?

**Comment by TimelordUK** [comment]
this should now be in 0.3.2 the latest release.

**Comment by TimelordUK** [comment]
ill close please raise new issue for any other date related problems.  Thanks for bringing this to my attention.
