### ISSUE TITLE
Issue with electron v1.7.5 Error: "None of the binaries loaded successfully"

### ISSUE THREAD

**Issue by panpetedextra** [TimelordUK/node-sqlserver-v8#45]
Hi,

It seems that this module error when running via Electron v.1.7.5. It will throw an error 

> "None of the binaries loaded successfully. Is your node version either >= 0.12.7 or >= 4.2.x or >= 5.1.1 or >= 6.1.0"

I have tried using Electon v1.6.12 and it was working fine.

**Comment by TimelordUK** [comment]
Can you try the strings branch from GitHub. You should be able to just download electron binaries and drop them in bin folder or take the whole branch it is functionally same

**Comment by panpetedextra** [comment]
Using strings branch and it is working now :+1: 
will this branch merge into master soon?

**Comment by TimelordUK** [comment]
yes I will merge across and release shortly.
