### ISSUE TITLE
Passing table value parameter to Store Proc

### ISSUE THREAD

**Issue by balakrishnanj** [TimelordUK/node-sqlserver-v8#46]
I'm having an issue when I try to pass a table value parameter to Store proc. 

const tvp= new sql.Table();
tvp.columns.add('x',sql.TYPES.Int);
tvp.columns.add('y', sql.TYPES.SmallInt);

When I try to pass this tvp to store proc
await db
            .request()
            .input("tvpTable", tvp) i'm getting this error RequestError: IMNOD: [msnodesql] Parameter 1: Invalid parameter type. 

But the same call works with MSSQL node module. Is table value parameter not supported in node-sqlserver-v8?

**Comment by TimelordUK** [comment]
It isn't currently but I can look to add it 

How in the working node interface do you then supply data for the tvp type can you send a full example of how this works

**Comment by skankanvar** [comment]
@TimelordUK : I guess when we use just import mssql it is using tedious TDS by default and when we use
await db
.request()
.input("tvpTable", tvp)
OR
await db 
.request()
.input("tvpTable",sql.TYPES.TVP, tvp) it works fine.


But when we import sql/msnodesqlv8 this doesnt work and gives above mentioned error.

**Comment by TimelordUK** [comment]
I have been looking at adding TVP parameter stored proc support to msnodesqlv8

in my library all that will be required is a call to the proc with an object parameter where columns are defined.

i.e. 

var tvpObj = {
   col_1 : "Hello",
   col_2 : "World"
}

and call the proc as usual - all the binding is done automatically by the driver.

I hope to have that released shortly but I will have to see how to integrate that into the mssql API.

**Comment by TimelordUK** [comment]
this is now fixed on latest version 0.4.5

**Comment by PeterStaev** [comment]
@TimelordUK , I cannot get this to work although I'm running version 0.4.7. 

**Try 1**
```ts
        const tvp = new sql.Table("[General].[BigintValueTVP]");
        tvp.columns.add("value", sql.BigInt(), { nullable: false });
        tvp.rows.add(1);
        tvp.rows.add(2);

        const request = new sql.Request(connection);
        request.input("tTVP", tvp);
        await request.execute("mySP");
```
Throws the same error as above: `IMNOD: [msnodesql] Parameter 1: Invalid parameter type`

**Try 2**
```ts
        const tvp = [{value:1}, {value:2}]
        
        const request = new sql.Request(this.connection);
        request.input("tTVP", tvp);
        await request.execute("mySP");
```
This throws the following error: `Operand type clash: nvarchar is incompatible with BigintValueTVP`

**Try 3**
```ts
        const tvp = [{value:1}, {value:2}]
        
        const request = new sql.Request(this.connection);
        request.input("tTVP", sql.TVP("[General].[BigintValueTVP]"), tvp);
        await request.execute("mySP");
```
This throws the first error: `IMNOD: [msnodesql] Parameter 1: Invalid parameter type`

So how do you work with TVPs when using this plugin?

**Comment by TimelordUK** [comment]
Sorry it does require a little patch to mssql I need to raise a pull request on the plugin. If you look at releases in git under table value parameters there is a few lines that needs patching in the mssql plugin.

**Comment by PeterStaev** [comment]
Thanks for your reply @TimelordUK , but even after the patch this does not work. If the TVP is in the dbo schema all works, but if it is in a custom scheme (like in my examples above) I get the following error:
`Column, parameter, or variable #1: Cannot find data type BigintValueTVP.`

**Comment by TimelordUK** [comment]
Ok thanks for letting me know. This should hopefully be simple to fix I will look at it as soon as possible.

**Comment by PeterStaev** [comment]
Here is the test scenario I'm using:
DB Setup:
```sql
CREATE SCHEMA [Gen]
GO
CREATE TYPE [dbo].[Test1] AS TABLE(
	[value] [bigint] NOT NULL
)
GO
CREATE TYPE [Gen].[Test] AS TABLE(
	[value] [bigint] NOT NULL
)
GO
CREATE PROCEDURE [Gen].[TestSp]
	@t			[Gen].[Test]		READONLY
AS
BEGIN
	select *
	from @t
END
GO
CREATE PROCEDURE [Gen].[TestSp1]
	@t			[Test1]		READONLY
AS
BEGIN
	select *
	from @t
END
GO
```

app
```js
var sql = require("mssql/msnodesqlv8");

var connection = new sql.ConnectionPool(config);

connection.connect()
    .then(function () {
        // This one is ok
        var tvp = new sql.Table("Test1");
        tvp.columns.add("value", sql.BigInt(), { nullable: false });        
        tvp.rows.add(5);
        const request = new sql.Request(connection);
        request.input("t", sql.TVP("Test1"), tvp);
        request.execute("Gen.TestSp1")
            .then(function () {
                console.log("OK");
            })
            .catch(function (e) {
                console.log(e);
            });

        // This one fails
        var tvp = new sql.Table("Gen.Test");
        tvp.columns.add("value", sql.BigInt(), { nullable: false });        
        tvp.rows.add(5);
        const request = new sql.Request(connection);
        request.input("t", sql.TVP("Gen.Test"), tvp);
        request.execute("Gen.TestSp")
            .then(function () {
                console.log("OK");
            })
            .catch(function (e) {
                console.log(e);
            });
    })
    .catch(function (e) { console.log(e) });
```

**Comment by TimelordUK** [comment]
OK, I have made some progress on this, unfortunately this will require a change to the c++ driver as it has to inform ODBC of the schema being used, I have hacked up an experimental build which gets your examples working.

I will hope to get this released in next day or 2 after tidying up and testing.

**Comment by TimelordUK** [comment]
0.4.9 should now run these 2 examples OK - thanks they are good tests.


C:\Program Files\nodejs\node.exe index.js
OK
OK

var sql = require('mssql/msnodesqlv8')

const connectionConf = {
  user: '',
  password: '',
  database: 'scratch',
  host: 'localhost',
  connectionString: 'Driver={SQL Server Native Client 11.0}; Server=np:\\\\.\\pipe\\LOCALDB#EBF94DD0\\tsql\\query; Database={scratch}; Trusted_Connection=Yes;',
  options: {
  },

  pool: {
    max: 5,
    min: 0,
    idle: 10000
  }
}

var connection = new sql.ConnectionPool(connectionConf)

connection.connect()
  .then(function () {
    // This one is ok
    var tvp = new sql.Table('Test1')
    tvp.columns.add('value', sql.BigInt(), {nullable: false})
    tvp.rows.add(5)
    const request = new sql.Request(connection)
    request.input('t', sql.TVP('Test1'), tvp)
    request.execute('Gen.TestSp1')
      .then(function () {
        console.log('OK')
      })
      .catch(function (e) {
        console.log(e)
      })
  }).then(function () {
// This one fails
    var tvp = new sql.Table('Gen.Test')
    tvp.columns.add('value', sql.BigInt(), {nullable: false})
    tvp.rows.add(5)
    const request = new sql.Request(connection)
    request.input('t', sql.TVP('Gen.Test'), tvp)
    request.execute('Gen.TestSp')
      .then(function () {
        console.log('OK')
      })
      .catch(function (e) {
        console.log(e)
      })
  })

**Comment by TimelordUK** [comment]
I believe this is now sorted - this has  been merged to mssql so hopefully tvp now works OK
