### ISSUE TITLE
Getting Binary/Image Type as a Buffer

### ISSUE THREAD

**Issue by Jeff-14159** [TimelordUK/node-sqlserver-v8#47]
Is there a way to get an Binary/Image column as actual binary data or better as a buffer? 

For example we have some pdf's stored in an old database as the sql "image" type and when I do a raw query the metadata confirms it as the "image" type but the data returned from the query is already decoded and in a string.... while this would normally be ok something is not being decoded properly and the PDF's are not showing up right.

so instead of this:
`%PDF-1.4
%����
1 0 obj<</Producer(DynamicPDF Generator v3.0.3 for .NET)/CreationDate(D:20080721130746)>>
endobj
..........
`

so is there a way to get the actual raw data like this:
`0x255044462D312E340A25E2E3CFD30A312030206F626A3C3C2F50726F64756365722844.......`

I think the underling issue is with the characters used in a pdf file and JavaScript native encoding/decoding being used, I had a similar issue when writing our new pdf file uploader and as a workaround/fix I kept the files in binary/base64 and they were left intact both in and out of the database.

Thanks,
Jeff

**Comment by TimelordUK** [comment]
does something like below force it to return a buffer - for a varbinary column it should not attempt to map to a string, but it probably drops to string by default, what is the actual column definition.

select cast(buffer_param as varbinary(1000)) from [dbo].[buffer_param_test] as raw_data

**Comment by Jeff-14159** [comment]
the above is working nicely but only for 1000 ..... if using (3000)+ or (max) it stops trying to buffer and just spits out the string? how to make this work for data larger that 2000?

**Comment by TimelordUK** [comment]
What is exact column definition of the column In the table that is holding the image. Is it defined as a varbinary ?

**Comment by TimelordUK** [comment]
Looking at the driver code looks like I will have to take a look at this. I don't think it currently handles larger than 2k binary columns as you have discovered. I will try to get a fix out as soon as possible in coming days.

**Comment by Jeff-14159** [comment]
the source column type is "image". With the cast it was successfully converting it to the varbinary type.

No rush on this now I was able to do the conversion in SQL first with this:

`SET ARITHABORT ON `
` SELECT`
`ReportID AS ReportID, `
`CAST(N'' AS XML).value('xs:base64Binary(xs:hexBinary(sql:column("PDFData")))', 'VARCHAR(MAX)') AS PDFEncoded `
`FROM ( `
`SELECT RPT.ReportID, `
`CONVERT(VARBINARY(max),RPT.PDFImage) AS 'PDFData'	`
`FROM Reports AS RPT ` 
`WHERE RPT.ReportID='00001' `
`) AS rtp_temp` 

Thanks,
Jeff

**Comment by TimelordUK** [comment]
I found cause of this issue it will be fixed in next version. Thanks for showing me how to reproduce it.

**Comment by TimelordUK** [comment]
this is now fixed on latest version 0.4.5

**Comment by Jeff-14159** [comment]
Thank you for your quick responses on the initial trouble shooting and continued support on this module.

Thanks,
Jeff
