### ISSUE TITLE
"None of the binaries loaded successfully." on Windows Server 2008 SP2, Node v4

### ISSUE THREAD

**Issue by seanpoulter** [TimelordUK/node-sqlserver-v8#49]
While trying to require the library I'm receiving an error loading the binaires:
```
Error: None of the binaries loaded successfully. Is your node version either >= 0.12.7 or >= 4.2.x or >= 5.1.1 or >= 6.1.0
    at failIfNoBinaryExported (...dir\node_modules\msnodesqlv8\lib\sqlserver.native.js:64:13)
    at liveLoad (...dir\node_modules\msnodesqlv8\lib\sqlserver.native.js:51:3)
    at Object.<anonymous> (...dir\node_modules\msnodesqlv8\lib\sqlserver.native.js:24:1)
```
<br>

I'm trying to get script to run in an environment with:
* Windows Server 2008 SP2 (x64)
* Node v4.8.4 x86, npm v2.15.11
* VS C++ 2015 Redistributable installed (x86, x64)
* SQL Native Client 11
* msnodesqlv8@0.3.2
<br>

Adding logging in the `attemptToExportBinary (filename)` function in `sqlserver.native.js` lists the expected binaries, but suppresses an error:
```
sqlserverv8.node.v4.8.4.ia32.node
[Error: The specified procedure could not be found.
\\?\c:\...dir\node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v4.8.4.ia32.node]

sqlserverv8.node.v4.8.4.x64.node
[Error: %1 is not a valid Win32 application.
\\?\c:\...dir\node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v4.8.4.x64.node]
```
<br>

Any suggestions what to try?

**Comment by TimelordUK** [comment]
can you try the latest msnodesqlv8 version - 0.4.5.  This definitely works against version node 4.8.4 64 bit,  I have not tried 32 bit testing for a while.

Can you run the system on your work station before release to server to check it is ok on another environment?

im running 4.8.4 below on my workstation but this is 64 bit binaries.

$ node --version
v4.8.4

$ tool\testonce.bat

$ node runtest -t tvp -t warnings.js -t compoundqueries.js -t querycancel.js -t txn.js -t datatypes.js -t params.js -t query.js -t querytimeout.js -t connect.js -t bulk.js -t sproc.js -t prepared.js -t userbind.js -t dates.js  2>&1
{ _: [],
  t:
   [ 'tvp',
     'warnings.js',
     'compoundqueries.js',
     'querycancel.js',
     'txn.js',
     'datatypes.js',
     'params.js',
     'query.js',
     'querytimeout.js',
     'connect.js',
     'bulk.js',
     'sproc.js',
     'prepared.js',
     'userbind.js',
     'dates.js' ] }


  tvp
    √ use tvp simple test type insert test using pm (93ms)
    √ use tvp simple test type select test
    √ use tvp simple test type insert test
    √ use tvp to select from table type complex object Employee type (428ms)
    √ employee use tm to get a table value type representing table and create that user table type (76ms)

**Comment by seanpoulter** [comment]
Wow. Thanks for the really fast reply!

I switched to Node x64 and installed the VS 2017 C++ Redistributables for x86 and x64 from [here](https://www.visualstudio.com/downloads/). Here's the latest output with some extra logging in `bootstrap.js`:

```
>node --version
v4.8.4

>npm ls msnodesqlv8
project@1.0.0 c:\scripts\project
└── msnodesqlv8@0.4.5

> tool\testonce.bat

c:\scripts\project\node_modules\msnodesqlv8>node runtest -t tvp -t warnings.js -t compoundqueries.js -t querycancel.js -t txn.js -t datatypes.js -t params.js -t query.js -t querytimeout.js -t connect.js -t bulk.js -t sproc.js -t prepared.js -t userbind.js -t dates.js  2>&1 

sqlserverv8.electron.v1.8.0.ia32.node
[Error: %1 is not a valid Win32 application.
\\?\c:\scripts\project\node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v1.8.0.ia32.node]

sqlserverv8.electron.v1.8.0.x64.node
[Error: The specified procedure could not be found.
\\?\c:\scripts\project\node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v1.8.0.x64.node]

sqlserverv8.node.v4.8.4.ia32.node
[Error: %1 is not a valid Win32 application.
\\?\c:\scripts\project\node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v4.8.4.ia32.node]

sqlserverv8.node.v4.8.4.x64.node
[Error: The specified procedure could not be found.
\\?\c:\scripts\project\node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v4.8.4.x64.node]

...

        throw new Error('None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7 or 8 ?')
        ^

Error: None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7 or 8 ?
    at failIfNoBinaryExported (c:\scripts\project\node_modules\msnodesqlv8\lib\bootstrap.js:65:15)
    at Object.liveLoad (c:\scripts\project\node_modules\msnodesqlv8\lib\bootstrap.js:48:5)
    at Object.<anonymous> (c:\scripts\project\node_modules\msnodesqlv8\lib\bootstrap.js:81:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at c:\scripts\project\node_modules\msnodesqlv8\lib\connection.js:10:19
```

Would you happen how to debug why the native module isn't loading? I'm firing up [Depends / Dependency Walker](http://www.dependencywalker.com) to figure out if what libraries I'm missing on the system.

**Comment by TimelordUK** [comment]
it is probably a dynamic link error i.e. I have linked against different version to your installation, my guess is ODBC version itself.   Generally process explorer I find helpful in these sorts of situations . (sysinternals). If you enable lower pane DLL view, this is the set I have loaded into node when the library is running.

[node.exe.txt](https://github.com/TimelordUK/node-sqlserver-v8/files/1331084/node.exe.txt)

**Comment by TimelordUK** [comment]
did you get any joy with this, have you another potential machine to try to check the system works OK?

**Comment by seanpoulter** [comment]
Thanks for the DLL list. Diffing against yours, the SQL Client Libraries
aren't loaded but for the most part the production system has libraries on
the same path.

Haven't been able to reproduce the problem with Node 4 yet. I'll fire up a
VM later today if we haven't found a different OS to run from. It's been
working beautifully on Node 6.


On Sep 26, 2017 07:34, "TimelordUK" <notifications@github.com> wrote:

did you get any joy with this, have you another potential machine to try to
check the system works OK?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TimelordUK/node-sqlserver-v8/issues/49#issuecomment-332170583>,
or mute the thread

**Comment by seanpoulter** [comment]
From my development PC the Node 4 x64 binaries load OK, so it's not the binaries. For what it's worth I'm happy to close this and attribute it to some missing library on the problem system. The [system requirements](https://www.microsoft.com/en-ca/download/details.aspx?id=36434) for the SQL Native Client v11 say it needs Windows Server 2008 R2 - a version *after* SP2 that we're on. I'd wager that's part of the problem.

Thanks for the prompt help @TimelordUK!
