### ISSUE TITLE
msnodesqlv8 not supporting on linux

### ISSUE THREAD

**Issue by sowjanya17** [TimelordUK/node-sqlserver-v8#51]
Not able to install msnodesqlv8 on linux. Getting the below error.
Unsupported platform for msnodesqlv8@0.4.5: Wanted {"os":"win32", "arch":"any"} (Current:{"OS":"linux","arch":"x64"
Could you please give a work around for this.

**Comment by TimelordUK** [comment]
https://www.npmjs.com/package/mssql

Try the above msnodesqlv8 is windows only currently.

**Comment by pellejacobs** [comment]
@sowjanya17 you can try `npm install --force` as workaround. 

@TimelordUK, would it be possible to remove the os requirement? We're using a linux CI/CD environment to build our cross-platform electron application. The windows version uses msnodesqlv8, but the windows binary is build on a linux environment, which is unable to properly install msnodesqlv8.

**Comment by gaspetcan** [comment]
Is there any solution ? Same issue

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8/releases

I have a build of msnodesqlv8 which as been tested on 64 bit Ubuntu using MS odbc 17 driver 

```cmd
:~/dev/js/sql/node_modules/msnodesqlv8/samples/javascript$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
~/dev/js/sql/node_modules/msnodesqlv8/samples/javascript$ node streaming.js 
submitted EXEC sys.sp_helpindex @objname = N'[users]' elapsed 1 ms
meta = [
    {
        "size": 128,
        "name": "index_name",
        "nullable": false,
        "type": "text",
        "sqlType": "nvarchar"
    },
    {
        "size": 210,
        "name": "index_description",
        "nullable": true,
        "type": "text",
        "sqlType": "varchar"
    },
    {
        "size": 2126,
        "name": "index_keys",
        "nullable": true,
        "type": "text",
        "sqlType": "nvarchar"
    }
]
column [0] = "PK__users__3213E83F3A5ED730"
column [1] = "clustered, unique, primary key located on PRIMARY"
column [2] = "id"
done
1 rows returned elapsed 1384
finished
free

```

**Comment by TimelordUK** [comment]
closing as Linux is now supported
