### ISSUE TITLE
Bulk insert error in conjunction with node-mssql

### ISSUE THREAD

**Issue by bchopson** [TimelordUK/node-sqlserver-v8#54]
Bulk insert example from the mssql docs fails when using msnodesqlv8 as the driver. From debugging, the error appears to be when calling the TableMgr bind function:
https://github.com/patriksimek/node-mssql/blob/master/lib/msnodesqlv8.js#L325

Please see patriksimek/node-mssql#532

Repro at https://github.com/bchopson/msnodesqlv8-bulk-insert-error

**Comment by bchopson** [comment]
SQL Server version: 2008

**Comment by TimelordUK** [comment]
my apologies for the late response I am testing a fix for this currently.

**Comment by TimelordUK** [comment]
thanks for the test, very useful

this should work on latest version 0.4.10

{ rowsAffected: 1 }
{"recordsets":[[{"a":777,"b":"test"}]],"recordset":[{"a":777,"b":"test"}],"output":{},"rowsAffected":[]}

```javascript
var connection = new sql.ConnectionPool(connectionConf)

sql.connect(connectionConf.connectionString)
  .then(function () {
    var table = new sql.Table('#table_name')
    table.create = true
    table.columns.add('a', sql.Int, {primary: true})
    table.columns.add('b', sql.VarChar(50), {nullable: false})
    table.rows.add(777, 'test')

    const request = new sql.Request()
    return request.bulk(table)
  })
  .then(function (res) {
    console.dir(res)
    new sql.Request().query('select * from #table_name', (err, result) => {
      console.log(JSON.stringify(result))
    })
  })
  .catch(function (err) {
    console.error(err)
  })
```

**Comment by bchopson** [comment]
Great, can confirm this works. Thanks for the quick fix!
