### ISSUE TITLE
Feature: allow specifying binary to use

### ISSUE THREAD

**Issue by tmcdonnell87** [TimelordUK/node-sqlserver-v8#59]
Currently the module expects to use a .node file that ships with the package. Some build processes (e.g., https://github.com/zeit/pkg/) don't do a good job of pulling these in. In these cases it's often possible to add the binary as an asset or ship it in a package, but there isn't a good way of telling msnodesqlv8 to look in a different location if it is difficult to inject into the expected path. 

This could be a config param, for example. Happy to provide a PR if it is a direction you'd consider. 

Thanks!

**Comment by TimelordUK** [comment]
Sure sounds good please have a go at what you require and providing it remains backwards compatible should be fine. Some sort of config for library probably is required and this could pave way for other options

**Comment by TimelordUK** [comment]
Please feel free to raise a PR if necessary. Closing for now.
