### ISSUE TITLE
Bulk insert doesn't understand table names wrapped in brackets

### ISSUE THREAD

**Issue by patriksimek** [TimelordUK/node-sqlserver-v8#6]
``` javascript
tm = connection.tableMgr();
tm.bind("bulk_table", function(mgr) {
    assert(mgr.columns.length > 0); // OK
});
```

``` javascript
tm = connection.tableMgr();
tm.bind("[bulk_table]", function(mgr) {
    assert(mgr.columns.length > 0); // Fails
});
```

Temporary tables are not recognized regardless if they're in brackets or not.

``` javascript
tm = connection.tableMgr();
tm.bind("#mytemptable", function(mgr) {
    assert(mgr.columns.length > 0); // Fails
});
```

**Comment by Miramac** [comment]
Also tables with schema indication are not recognized:

```javascript
tm = connection.tableMgr();
tm.bind("dbo.bulk_table", function(mgr) {
    assert(mgr.columns.length > 0); // Fails
});
```

**Comment by TimelordUK** [comment]
I will look at issue soon.  It is probably due to a regular expression substitution in the code for the table name.  If you get time you could try and hard wire the name of table you are testing in the describe.sql. I am
away from terminal so can't test right now.  If this works we know this is issue and how to fix it.

**Comment by TimelordUK** [comment]
Global temp tables should now work ok ##. Looking at documentation it does not look like it will be easy to get this working on local temp but I will keep looking.

**Comment by TimelordUK** [comment]
This should be sorted now - different schemas and temp tables are now supported in API, thanks for raising with me.  If you get a chance please merge the pull request for TVP into your msnodesqlv8 driver!
