### ISSUE TITLE
Some ideas to make the TypeScript experience better

### ISSUE THREAD

**Issue by kevinkuszyk** [TimelordUK/node-sqlserver-v8#60]
I have some ideas to make the TypeScript experience better.   For example instead of this:

```typescript
import { MsNodeSqlDriverApiModule as v8 } from "msnodesqlv8/lib/MsNodeSqlDriverApiModule";

const client: v8.v8driver = require("msnodesqlv8");

const connectionString = "server=.;Database=Master;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";
const sql = "SELECT name FROM sys.databases";

client.query(connectionString, sql, (err, rows) => {
    console.log(rows);
});
```

You could write this:

```typescript
import { SqlClient } from "msnodesqlv8";

const client: SqlClient = require("msnodesqlv8");

const connectionString = "server=.;Database=Master;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";
const sql = "SELECT name FROM sys.databases";

client.query(connectionString, sql, (err, rows) => {
    console.log(rows);
});
```

To achieve this I made the following changes:

1. Rename `MsNodeSqlDriverApiModule.ts` to `index.d.ts` and remove the `export module MsNodeSqlDriverApiModule`.
2. Add a `typings` element to the `package.json`.
3. Rename `v8driver` to `SqlClient`.

I would also like to drop the `v3` prefix from all the type names.

This would obviously be a breaking change for anyone who is already using the `MsNodeSqlDriverApiModule.ts`.  But to be honest, it's quite well hidden and I only discovered it mentioned in passing in the wiki today after a few months of using the lib.

What do you think?  If you like the idea I'll send a pull request.

**Comment by TimelordUK** [comment]
These seem to be great changes thanks for suggestions.  By all means if you have the time send a pull request.

**Comment by TimelordUK** [comment]
ice pulled your code, integrated and fixed all compile issues and got the ts demo and wrapper working so we are looking good.

I cannot get the appveyor to work presently in that when i install typescript on the cloud the tsc compiler is complaining

> msnodesqlv8.samples.typescript@1.0.0 tsc C:\projects\node_modules\msnodesqlv8\samples\typescript
805> tsc
806
807../../lib/MsNodeSqWrapperModule.ts:11:37 - error TS2304: Cannot find name 'require'.
808
80911     const legacyDriver: SqlClient = require('msnodesqlv8');
810                                       ~~~~~~~
811
812
813DriverModuleTest.ts:6:24 - error TS2304: Cannot find name 'require'.
814
8156 const sql: SqlClient = require('msnodesqlv8');
816                         ~~~~~~~
817
818
819DriverModuleTest.ts:11:14 - error TS2304: Cannot find name 'require'.
820
82111 let assert = require('assert');
822                ~~~~~~~
823

**Comment by TimelordUK** [comment]
ok i sorted out appveyor, and have published these changes in latest npm version

**Comment by kevinkuszyk** [comment]
Thanks for merging all that.

I just opened #64 which tidies up the TypeScript build for the samples a little.  

Whilst I was there I noticed it was emitting the compiled `.js` files next the the `.ts` and they are now committed.  Was that a conscious choice?  Usually they would go into a `~/dist` folder and not be committed.  I can fix that too if you want?

**Comment by TimelordUK** [comment]
Yes thanks sorry that was not a conscious decision on my part.

**Comment by kevinkuszyk** [comment]
No probs.  That's in #66.

**Comment by TimelordUK** [comment]
Thanks for all work on making this contribution. Closing.
