### ISSUE TITLE
Bulk insert "Geography Points" into database

### ISSUE THREAD

**Issue by subesokun** [TimelordUK/node-sqlserver-v8#61]
I'd like to know how I can insert multiple geography points into the database via a bulk insert. In the documentation I could find so far only a query example but no example to insert a single geography point or multiple via a bulk insert. Any help and hints would be appreciated :)

Thanks a lot!

**Comment by TimelordUK** [comment]
Have you got a sample of a set of points in JS I can use to test with. 

Thanks for letting me know I will take a look

**Comment by subesokun** [comment]
Just created some random points, hopefully that helps. https://gist.github.com/anonymous/46be2c34dd455580768d3846bc727556#file-map-geojson

**Comment by TimelordUK** [comment]
thanks

if you use latest version i include a geometry.js in unit.tests some of which use your provided json file to insert in bulk.  You can use a tvp user defined type with a stored procedure or simply use a parameter in sql bound to an array of values.

hopefully one of more of these will suit, i not let me know what it is you require to do.

**Comment by TimelordUK** [comment]
im assuming this is sorted, will close - please comeback if you need more guidance!  thanks for considering the library.
