### ISSUE TITLE
Bad performance with many rows

### ISSUE THREAD

**Issue by mokkabonna** [TimelordUK/node-sqlserver-v8#67]
I was hoping this library would give me performance boost since it's native. However I see the opposite.

The following query fetches about 10K rows and takes about **2,5-3 seconds.**

```js
const sql = require('msnodesqlv8')
const connectionString = "server=localhost;Database=monster;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";

console.time('mssnodesqlv8')
sql.query(connectionString, 'select * from component where caseset_id = 7', function (err, rows) {
  console.timeEnd('mssnodesqlv8')
})
```

For comparison the same query using tedious takes about **160ms**

```js
const sql = require('mssql')

sql.connect({
   user: 'sequelizeauto',
   password: '---',
   server: 'localhost', 
   database: 'monster',
}).then(pool => {
    console.time('tedious')
    return pool.request()
    .query('select * from component where caseset_id = 7')
}).then(result => {
    console.timeEnd('tedious')
}).catch(err => {
  console.log(err)
})
```

Am I doing something wrong? Are there other factors I  should be aware of that might affect performance?

**Comment by egmen** [comment]
It is becouse of cold start. Try to heat connection and then check perfomance.

**Comment by mokkabonna** [comment]
I am using this through https://www.npmjs.com/package/sequelize-msnodesqlv8 and sequelize does have connection pooling, still I'm seeing quite bad performance.

**Comment by mokkabonna** [comment]
Doing this still produces results about **2.2 seconds**

**Comment by mokkabonna** [comment]
I might add that the CPU also reaches 100% doing the query.

**Comment by TimelordUK** [comment]
thanks for letting me know - out of interest do you know what the bulk insert performance is like with TVP etc.  I will certainly look into what is going on, unfortunately it is likely not going to be a quick fix.  On select  side, the library is working one row at a time, I will look into binding a block or rows in one go to reduce the IO.

I will report back with my findings.

**Comment by TimelordUK** [comment]
I have put in performance enhancements which drop the number of calls made to native driver - this on my test machines has improved matters dramatically.   I doubt if performance has come down to tedious level , there are still other improvements I am looking at.  In meanwhile this does seemed to have significantly helped.

**Comment by TimelordUK** [comment]
I have added further improvements which should make two drivers comparable in performance - would be interesting to see your benchmark figures against 0.5.4.  I have been using select * from syscomments which originally was well over 2 seconds, it is now an order of magnitude faster.

rows.length 3266 elapsed 164 ms [ runs 14 avg 185.21428571428572 ]
rows.length 3266 elapsed 282 ms
rows.length 3266 elapsed 172 ms [ runs 16 avg 190.4375 ]
rows.length 3266 elapsed 233 ms
rows.length 3266 elapsed 133 ms [ runs 18 avg 189.61111111111111 ]
rows.length 3266 elapsed 293 ms
rows.length 3266 elapsed 159 ms [ runs 20 avg 193.25 ]
rows.length 3266 elapsed 196 ms
rows.length 3266 elapsed 147 ms [ runs 22 avg 191.27272727272728 ]
rows.length 3266 elapsed 214 ms
rows.length 3266 elapsed 128 ms [ runs 24 avg 189.58333333333334 ]
rows.length 3266 elapsed 310 ms
rows.length 3266 elapsed 128 ms [ runs 26 avg 191.84615384615384 ]

**Comment by mokkabonna** [comment]
Will check this after easter.

**Comment by mokkabonna** [comment]
I see the same results, about 9-10 times faster. That's quite an improvement. Thanks for doing the work!

**Comment by gh0st** [comment]
Hmmm, so what about 20,000+ rows?

**Comment by TimelordUK** [comment]
note test of 30 column randomly generated table mix column type, 20,000 rows. (see below)

normal query: average ~1.2 secs

[test_table ] rows.length 20000 elapsed 1360 ms [ runs 100 avg 1261.99 ]
[test_table ] rows.length 20000 elapsed 856 ms [ runs 101 avg 1257.970297029703 ]
[test_table ] rows.length 20000 elapsed 863 ms [ runs 102 avg 1254.0980392156862 ]

prepared query:~700ms

[test_table ] rows.length 20000 elapsed 650 ms [ runs 98 avg 702.4387755102041 ]
[test_table ] rows.length 20000 elapsed 724 ms [ runs 99 avg 702.6565656565657 ]
[test_table ] rows.length 20000 elapsed 813 ms [ runs 100 avg 703.76 ]

**Comment by TimelordUK** [comment]
Think I’ve done all I can on this one.  Closing. Thanks for raising issue.
