### ISSUE TITLE
Does this work with the 'SQL Server' driver?

### ISSUE THREAD

**Issue by gh0st** [TimelordUK/node-sqlserver-v8#69]
I notice in all the documentation we're using `SQL Server Native Client 11.0`. Does the package not work with the `SQL Server` driver?

**Comment by gh0st** [comment]
The SQL Server Native Client 11.0 was in fact missing in my dev environment. I installed it from [microsoft's website](https://msdn.microsoft.com/en-US/library/ms131321(SQL.120).aspx). I however am now getting this error: `[Microsoft][SQL Server Native Client 11.0]TCP Provider: No connection could be made because the target machine actively refused it.`

**Comment by TimelordUK** [comment]
That’s a tcp error looks like client can not get through to server. From machine you are running client on are you able to ping server hosting sql server or are you able to telnet onto the port which sql server is listening on.  Is the host being used on your local machine available on server.

**Comment by gh0st** [comment]
Yes able to ping. The `ApplicationIntent` piece of my connection string is triggering that tcp error. If I get rid of it I get the iis-node error 
```
HRESULT: 0x6d
HTTP status: 500
HTTP subStatus: 1013
HTTP reason: Internal Server Error
```

**Comment by gh0st** [comment]
I'm seeing this in the event logs of my dev server
```
Program: ...odesqlv8\lib\bin\sqlserverv8.node.v6.11.0.x64.node
File: ..\src\OdbcStatement.cpp
Line: 702
Expression: column >= 0 && column < resultset->GetColumns()
For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts
```

**Comment by gh0st** [comment]
I cleaned out my `node_modules` folder and it started working.
