### ISSUE TITLE
Compile issue on 0.6.2 after installing node v10.1.0

### ISSUE THREAD

**Issue by TheInnovativeTechnologist** [TimelordUK/node-sqlserver-v8#71]
On another issue:

I recently upgraded node to v10.1.0 and also your package to 0.6.2 and found it bombing out on the following:

`const sql = require('msnodesqlv8');`

I reinstalled node v8.11.1 and there were no compile issues.

**Comment by TimelordUK** [comment]
can you try and completely clean install i.e. if you have any global npm cache, delete and re-install to ensure the latest version is installed ok.  It seems like the driver is not picking up the new binaries installed under bin folder as v10 should be working fine.  I have run locally against 10.1 node without an issue.

**Comment by TheInnovativeTechnologist** [comment]
I reinstalled v10.1.0 and upgraded your package to 0.6.3 and there are no compile issues any longer.

thank you :)
