### ISSUE TITLE
Question : why `npm` module is listed as dep ?

### ISSUE THREAD

**Issue by marcelfalliere** [TimelordUK/node-sqlserver-v8#73]
In `package.json` at ligne 96 we can see you listed `npm` as a dependency.

What is the reason for this, if you don't mind me asking ?

https://github.com/TimelordUK/node-sqlserver-v8/blob/master/package.json#L96

**Comment by TimelordUK** [comment]
This looks to be a mistake on my part.  I will remove this dependency and rerelease.

**Comment by marcelfalliere** [comment]
Oh OK. Maybe you were trying to specify the engine ? Take a look here : https://docs.npmjs.com/files/package.json#engines

`{ "engines" : { "node" : ">=0.10.3 <0.12" } }`

`{ "engines" : { "npm" : "~1.0.20" } }`

Regards

**Comment by TimelordUK** [comment]
thanks for letting me know the information, I have removed
