### ISSUE TITLE
Errors creating SqlClient

### ISSUE THREAD

**Issue by puckhead456** [TimelordUK/node-sqlserver-v8#75]
All I have is the base angular project generated from angular cli, and I am just trying to log rows from my mssql db to the console but the type script dies when it hits "const sql: SqlClient = require("msnodesqlv8");".  I have been following the ReadMe and can't figure out what is wrong... If anybody has any advice it would be appreciated. 😄 (I am on node version 10.2.1 and npm version 5.6.0).

`import { Component, OnInit } from '@angular/core';
import { SqlClient } from 'msnodesqlv8';
import  notify from "devextreme/ui/notify";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor() {
    this.sqlv8();
  }
  title = 'app works!';
  
  sqlv8(){
    const sql: SqlClient = require("msnodesqlv8");
    const connectionString = "Server=blah;Database=blah;User Id=blah; Password=blah;";
    const query = "select * from someTable";
    sql.query(connectionString, query, (err, rows) => {
      console.log(rows);
    });
  }
}
`

**Comment by TimelordUK** [comment]
Hello. 

I have not tried msnodesqlv8 in angular yet.  I will try creating a base cli application as you have done to see what happens.  Do you see any error on the console or anything ?

**Comment by TimelordUK** [comment]
Sorry is this still an issue you still require me to take a look ? Regarding angular and this library

**Comment by TimelordUK** [comment]
Closing.
