### ISSUE TITLE
node proccess is died when using nvarchar(max) column & inner join combination

### ISSUE THREAD

**Issue by sagitsofan** [TimelordUK/node-sqlserver-v8#77]
Hello,
I have this code on my node app:

```
  const getSubWorkflows = (data) => {
    return new Promise((resolve, reject) => {

      let query = "SELECT Name, Description, InParams, Url FROM [entities].[workflow] INNER JOIN [entities].[workflowProvision] ON [entities].[workflow].[DeployedProvisionID] = [entities].[workflowProvision].[ProvisionID]"
      this.request.query(query).then(function(rows) {
        resolve(rows.recordset)
      }).catch(err => {
        reject(err)
      })
    })
  }

```
When "**InParams**" column type defined as "nvarchar(max)" and the code is running, the process is die  without any catch or exception (!!!).
When i change the column type into "nvarchar(4000)" code is working like charm!
VERY STRANGE behavior!!!

Please help....

**Comment by TimelordUK** [comment]
Have you tried against 0.6.6?

**Comment by sagitsofan** [comment]
No, i am using 0.6.2
Does it fixed on 0.6.6?

**Comment by TimelordUK** [comment]
Please update someone else reported an issue very similar to this.  Else if that doesn’t work I will take a look.

**Comment by sagitsofan** [comment]
I have updated the package into 0.6.6 and it work.
Thank you.
