### ISSUE TITLE
Some tests for node-mssql are failing with msnodesqlv8 0.5.3+

### ISSUE THREAD

**Issue by patriksimek** [TimelordUK/node-sqlserver-v8#79]
Hi @TimelordUK, I have been doing some updates on node-mssql and noticed that tests are failing for msnodesqlv8. [This test](https://github.com/tediousjs/node-mssql/blob/master/test/common/tests.js#L389) is failing with an exception. The test is trying to create a simple temporary SP and execute it. 

```
RequestError: Could not find stored procedure '#temporary'.
 at StreamEvents.req.once.err (lib\msnodesqlv8.js:553:17)
 at routeStatementError (node_modules\msnodesqlv8\lib\reader.js:27:18)
 at C:\node-mssql\node_modules\msnodesqlv8\lib\reader.js:155:15
 at C:\node-mssql\node_modules\msnodesqlv8\lib\driver.js:194:13
 at C:\node-mssql\node_modules\msnodesqlv8\lib\driver.js:176:11
```

I've also noticed significant performance regression in 0.5.3. Latest version behaves the same.

| 0.5.1 | 0.5.3 |
| --- | --- |
| ![screen shot 2018-07-04 at 03 42 08](https://user-images.githubusercontent.com/1000058/42252327-5643e422-7f3c-11e8-8c06-1af53da90224.png) | ![screen shot 2018-07-04 at 03 42 17](https://user-images.githubusercontent.com/1000058/42252332-59da30fa-7f3c-11e8-9b0f-22461605f5fd.png) |

My testing env is running on Windows Server 2012 with SQL Server 2012. Before I start digging deeper, do you have an idea what might cause those?

Thank you.

**Comment by TimelordUK** [comment]
I’ll try and take a look over coming days at the stored procedure error. Many changes went in for large query performance it is possible smaller queries via streaming have been effected. I’ll concentrate initially on the stored procedure issue.

**Comment by TimelordUK** [comment]
I have not looked into this in detail yet, but one thing you may help me is which connections should I expect to be opened, can you log the spid in each of these commands. Running a very simple code through a single connection and I seem get the required results.

Is it taking a connection from the pool - I see the connection constructor being invoked on more than 1 occasion.  I must admit so many changes have gone in my side I cannot yet isolate what has caused this behaviour.  I wonder if you can just confirm the connection is the same object?

```javascript
const sql = require('msnodesqlv8')

const connectionString = 'Driver={SQL Server Native Client 11.0}; Server=np:\\\\.\\pipe\\LOCALDB#D953BE5C\\tsql\\query; Database={master}; Trusted_Connection=Yes;'
const create = 'create procedure #temporary as select 1 as num'
const ex = 'exec #temporary'

sql.open(connectionString, function (err, con) {
  if (err) {
    console.log('failed to open ' + err.message)
  }
  con.query(create, () => {
      con.query(ex, (err, res) => {
          console.log(JSON.stringify(res, null, 4))
      })
  })
})

```

[
    {
        "num": 1
    }
]

**Comment by patriksimek** [comment]
Strange, now it seems more like a node-mssql bug triggered by the performance regression. I'll take a more in-depth look. Thank you.

**Comment by TimelordUK** [comment]
I will look at performance issue I suspect it specifically relates to stream interface normally this sort of thing happens due to JavaScript interactions with the cpp driver itself.

**Comment by TimelordUK** [comment]
- try the latest version to see if this helps, I have also changed the driver to return multiple errors where those errors are all generated from actual sql submission

**Comment by patriksimek** [comment]
I can confirm that the latest version solves the performance issues.

But there is something strange with the latest version. Consider this example (don't change db credentials, this test is supposed to fail on login):

```javascript
const sql = require('msnodesqlv8')

const connectionString = 'Driver={SQL Server Native Client 11.0}; Server=127.0.0.1;Trusted_Connection=No;Uid=test;Database=test;Pwd=...'

sql.open(connectionString, function (err, con) {
  if (err) console.log('failed to open ' + err.message)
  console.log('ok')
})
```

With 0.6.6, the output is:

```
failed to open [Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'test'.
```

With 0.6.7, there is no output. The process just crashes with no output to stdout/stderr.

------

Regarding the multiple errors - I wasn't able to figure out how to correctly accumulate all the errors from a query. Consider this code:

```javascript
const sql = require('msnodesqlv8')

const connectionString = 'Driver={SQL Server Native Client 11.0}; Server=127.0.0.1;Trusted_Connection=No;Uid=test;Database=test;Pwd=...'

sql.open(connectionString, function (err, con) {
  if (err) console.log('failed to open ' + err.message)

  const req = con.queryRaw('select a;select b;')

  req.on("info", (msg) => {
    console.log("info", msg)
  })

  req.on("done", (msg) => {
    console.log("done", msg)
  })

  req.on("error", (msg) => {
    console.log("error", msg)
  })
})
```

The output is:

```
error { Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'a'. sqlstate: '42S22', code: 207 }
error { Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'b'. sqlstate: '42S22', code: 207 }
```

I'm getting the `error` handler called correctly for both errors, but is there a way for me to recognize when all errors have been reported so I can be sure the query was completed?

Thank you.

**Comment by TimelordUK** [comment]
Thanks the login issue definitely looks like a regression problem I’ll take a little look at that and hopefully report back with a fix. 

Yes we can add something to show which index of how many errors have been sent which would allow them to be glued together.  I’ll get this into the release as well. 

Glad the performance issue is sorted

**Comment by TimelordUK** [comment]
ok I have isolated the problem will release shortly.

from below if we fail to login a single error is reported (rather than crash)

[Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'test'.

- it is possible multiple errors on connect are returned (in which case an array is returned)

[Microsoft][SQL Server Native Client 11.0]Named Pipes Provider: Could not open a connection to SQL Server [2]. 
[Microsoft][SQL Server Native Client 11.0]Login timeout expired
[Microsoft][SQL Server Native Client 11.0]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

else all query errors are returned - i have added a flag to events api so you can know when these are completed.

```javascript
sql.open(connectionString, function (err, con) {
  if (err) {
    if (Array.isArray(err)) {
      err.forEach((e) => {
        console.log(e.message)
      })
    } else {
      console.log(err.message)
    }
  } else {
    console.log('callback based multiple errors query')
    con.query('select a;select b;', function (err, res, more) {
      if (err) {
        console.log(err.message + 'more = ' + more)
        if (!more) {
          console.log('subscribe to multiple errors query')
          const req = con.query('select a;select b;')
          req.on('error', (msg, more) => {
            console.log('event error ', msg, ' more = ', more)
          })
        }
      } else {
        console.log(res)
      }
    })
  }
})
```
callback based multiple errors query
[Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'a'.more = true
[Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'b'.more = false
subscribe to multiple errors query
event error  { [Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'a'.] sqlstate: '42S22', code: 207 }  more =  true
event error  { [Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'b'.] sqlstate: '42S22', code: 207 }  more =  false

**Comment by TimelordUK** [comment]
Think this is now closed.

**Comment by Coveted284** [comment]
@TimelordUK https://lnkr.fun/fbae941
