### ISSUE TITLE
Error: failed to start

### ISSUE THREAD

**Issue by ontajenius** [TimelordUK/node-sqlserver-v8#81]
Hi, I'm trying connect to my server using trusted connection. My node version is v8.11.3 and running in Windows 10 x64

When trying with this simple code:
```
var sql = require("msnodesqlv8");

var connectionString = "Server=WEBGIS;Database=TRADE_NSI_BARU;Trusted_Connection=yes;Driver={SQL Server Native Client 11.0}";

sql.open(connectionString, function(err, con) {
  if(err)
    console.log(err);
})
```
The output is like this
```
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! tesobj@1.0.0 start: `node app.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the tesobj@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any idea what's going on? Maybe I need to recompile the driver?

**Comment by TimelordUK** [comment]
Do you actually have a connection. Can you put log statement to see if the callback fires. If you don’t have an error and your in callback then must have connected. Have you tried running a query like select count (*) from sysobjects

**Comment by ontajenius** [comment]
Yes I have connection, I had another .NET application with exact same connection string in my machine.

And I'm also try using query statement

```
var sql = require("msnodesqlv8");

var connectionString = "Server=WEBGIS;Database=TRADE_NSI_BARU;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";

var query = "SELECT name FROM sys.databases";

sql.query(connectionString, query, (err, rows) => {
    console.log("Query started");
    if(err)
      console.log(err);
    console.log(rows);
});
``` 
The output is still nothing, not even the "Query started" string

```
x:\Workspace Balabala\tesobj>npm start

> tesobj@1.0.0 start x:\Workspace Balabala\tesobj
> node app.js

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! tesobj@1.0.0 start: `node app.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the tesobj@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\2018-08-03T01_45_19_239Z-debug.log
```

There is the log file 
[2018-08-03T01_45_19_239Z-debug.log](https://github.com/TimelordUK/node-sqlserver-v8/files/2255702/2018-08-03T01_45_19_239Z-debug.log)

Thank you for your help, really appreciate

**Comment by TimelordUK** [comment]
I think this maybe related to (see the end)
https://github.com/TimelordUK/node-sqlserver-v8/issues/79

where driver is crashing on login, I will patch this to see if it helps - that is to say if connection fails the driver currently crashes .

**Comment by TimelordUK** [comment]
Assuming this is now resolved on latest. Closing.
