### ISSUE TITLE
[Help] Connection string error

### ISSUE THREAD

**Issue by fabiomor** [TimelordUK/node-sqlserver-v8#82]
Hi, 
i'm having trouble during azure connection with node-sqlserver-v8 library. It's probably dued to wrong parameters, but i have no problem when using tedious structure:

Can you provide the respeective connection string in  node-sqlserver-v8 corresponding to:

> var config = 
   {
     userName: 'someuser', // update me
     password: 'somepassword', // update me
     server: 'edmacasqlserver.database.windows.net', // update me
     options: 
        {
           database: 'somedb' //update me
           , encrypt: true
        }
   }

I tried this:

> Driver={SQL Server Native Client 13.0}; Server=edmacasqlserver.database.windows.net; Database=somedb;Uid=someuser;Pwd=somepassword;

but it gave me this error:

> { Error: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified sqlstate: 'IM002', code: 0 }

Thanks

**Comment by TimelordUK** [comment]
can you try v11

Driver={SQL Server Native Client 11.0}; Server=tcp:(local); Database={master}; Uid=sa; Pwd=Password12!
