### ISSUE TITLE
accessToken in connection

### ISSUE THREAD

**Issue by lenisha** [TimelordUK/node-sqlserver-v8#83]
I was wondering if  node-odbc driver will support connecting to an Azure SQL DB using the AD access token instead of user/password? Similar to how Python wrapper does it?
https://github.com/mkleehammer/pyodbc/issues/228#issuecomment-319190980

**Comment by lenisha** [comment]
@TimelordUK  do you know how hard is to add it?

**Comment by TimelordUK** [comment]
I can’t find that much on this in documentation other than it looks to be supported upwards of version ODBC version 13.  How would I test this I don’t have access to an azure platform. 

I can take a look at what code changes are required but probably cannot test it

**Comment by lenisha** [comment]
@TimelordUK I could test, but it needs to expose SQLSetEnvAttr() with Access Token parameter …. if it could be exposed in native library .

**Comment by TimelordUK** [comment]
Closing this sorry looks like no movement since 2018.
