### ISSUE TITLE
Parameters cannot be used in stored procedure in other schema than dbo

### ISSUE THREAD

**Issue by ghost** [TimelordUK/node-sqlserver-v8#86]
Calling a procedure with parameters, where the schema is different than dbo, does not work, since the SQL issued to fetch procedure metadata does not work when schema is not dbo.

Fx call of a stored procedure in schema dbo with one input parameter:
 
      pm.callproc('API.GenerateComplete', [10], function(err, result, output) {
      });

To solve the issue the proc_describe.sql must change the where clause from:

	where
	    object_id = object_id('<escaped_procedure_name>')
to

	where
	    object_id = object_id('<schema_name>'.'<escaped_procedure_name>')

**Comment by TimelordUK** [comment]
Thanks for letting me know. I’ll test the fix and release shortly.

**Comment by HariSankaranarayanan** [comment]
Hi there,

Has this issue been fixed  as I am facing this issue still.

Thanks,
Hari

**Comment by TimelordUK** [comment]
Can you provide an exact example of how this breaks.  I briefly looked at it but need a test case.
