### ISSUE TITLE
Difference in events emitted for queryRaw between v0.2.11 and v0.6.11

### ISSUE THREAD

**Issue by JonPaz** [TimelordUK/node-sqlserver-v8#88]
Hi,

I've been investigating a problem that we found whilst upgrading the version of msnodesqlv8 to support NodeJS v10.  We use the Sequelise ORM layer along with sequelize-msnodesqlv8 to link with msnodesqlv8, which has worked well for a long time on the venerable NodeJS v6.

I've discovered that when using the connection's queryRaw function (and this may affect other functionality) that the sequence of events emitted differs between v0.2.11 and v0.6.11 - the following simple code will demonstrate this:

``` node
const sql = require('msnodesqlv8')
const sqlVersion = require('msnodesqlv8/package.json')
const util = require('util')

const connectionString = 'Driver={SQL Server Native Client 11.0}; Server={localhost\\SQLEXPRESS}; Database={master}; Trusted_Connection=Yes;'
const query = 'SELECT @@version'

console.log(`Using msnodesqlv8 ${sqlVersion.version}`);
sql.open(connectionString, function (err, con) {
  if (err) {
    console.log('failed to open ' + err.message)
  }

  console.log(`SQL query is: ${query}`);
  let request = con.queryRaw(query, (err, results) => {
    console.log("queryRaw callback");
    console.log(`Errors: ${err}`);
    console.log(`Results: ${util.inspect(results,true,12,true)}`);
  });
  request.on('meta', (meta) => {
    console.log("meta event");
  });
  request.on('row', () => {
    console.log("row event");
  });
  request.on('column', (index, data) => {
    console.log("column event");
  });
  request.on('done', () => {
    console.log("done event");
  });
})
```

This give the following console outputs:

Using msnodesqlv8 0.2.11
SQL query is: SELECT @@version
meta event
row event
column event
done event
queryRaw callback
Errors: null
Results: { meta:
   [ { size: 300,
       name: '',
       nullable: true,
       type: 'text',
       sqlType: 'nvarchar' },
     [length]: 1 ],
  rows:
   [ [ 'Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64) \n\tJul 21 2018 07:47:45 \n\tCopyright (C) 2017 Microsoft Corporation\n\tExpress Edition (64-bit) on Windows 10 Pro N 10.0 <X64> (Build 17134: ) (Hypervisor)\n',
       [length]: 1 ],
     [length]: 1 ] }

Using msnodesqlv8 0.6.11
SQL query is: SELECT @@version
meta event
row event
column event
queryRaw callback
Errors: null
Results: { meta:
   [ { size: 300,
       name: '',
       nullable: true,
       type: 'text',
       sqlType: 'nvarchar' },
     [length]: 1 ],
  rows:
   [ [ 'Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64) \n\tJul 21 2018 07:47:45 \n\tCopyright (C) 2017 Microsoft Corporation\n\tExpress Edition (64-bit) on Windows 10 Pro N 10.0 <X64> (Build 17134: ) (Hypervisor)\n',
       [length]: 1 ],
     [length]: 1 ] }
done event

_Notice that with v0.2.11, the done event is emitted before the callback and in v0.6.11 it is emitted after the callback and it is this that is causing issues with the sequelize-msnodesqlv8 shim layer_

I've been through the code but, as I'm still new to JS, I've struggled to identify where the changes occurred etc.

**Comment by TimelordUK** [comment]
it looks like sequelize-msnodesqlv8 is no longer supported by original developer.

I have had so many issues raised regarding sequencing of events I am now very reluctant to make changes, for example the mssql library which abstracts both tedious and msnodesqlv8 behind one clean interface has also raised issues of this kind in past.

looking at sequelize-msnodesqlv8, I am tempted to simply add sequelize support into msnodesqlv8 so tests can be written and it can be kept in sync with any future changes.  I would have thought in actual fact sequelize  could have taken mssql as their entry point in which case both libraries would be interchangeable.

I will check in to trunk a version which works against a simple query using sequelize, the code and output are below.

you can probably get this working by replacing the msnodesqlv8-sequelize Request.js with the following This is pretty much all I have done so far.  The author had worked around legacy issues such as string concatenation but none of this is necessary anymore, this is all done by the driver itself and will therefore be far more efficient.

I am no expert on sequelize, I really need someone to check it and let me know simple examples where the code now fails.  Once it looks OK, I will probably simply lift the sequelize shim into msnodesqlv8.

```javascript
'use strict'

const EventEmitter = require('events').EventEmitter
const uuid = require('uuid')
const debug = require('debug')('msnodesqlv8-sequelize')

class Request extends EventEmitter {
  constructor (sql, callback) {
    super()

    this.uuid = uuid.v4()
    this.sql = sql
    this.callback = callback

    debug(`creating request (${this.uuid}): ${this.sql.length > 80 ? this.sql.slice(0, 80) + '...' : this.sql}`)
  }

  static createColumn (metadata, index, data) {
    let columnMetadata = metadata[index]
    return {
      metadata: {
        colName: columnMetadata.name,
        type: {
          id: columnMetadata.sqlType
        },
        nullable: columnMetadata.nullable,
        size: columnMetadata.size
      },
      value: data
    }
  }

  execute (context) {
    let metadata = null
    let currentRow = null
    let e = null
    let rowCount = 0
    let lastColumn = 0

    debug(`connection (${context.uuid}): executing request (${this.uuid})`)
    context.requests.push(this)
    try {
      let request = context.connection.queryRaw(this.sql)

      request.on('meta', (meta) => {
        metadata = meta
        currentRow = [metadata.length]
        lastColumn = metadata.length - 1
      })

      request.on('column', (index, data) => {
        currentRow[index] = Request.createColumn(metadata, index, data)
        if (index === lastColumn) {
          ++rowCount
          this.emit('row', currentRow)
          currentRow = [metadata.length]
        }
      })

      request.on('error', err => {
        e = err
        context.removeRequest(this, e)
      })

      request.on('done', () => {
        context.removeRequest(this)
        if (typeof this.callback === 'function') {
          this.callback(e, rowCount)
        }
      })
    } catch (ex) {
      context.removeRequest(this, ex)
      context.close()
    }
  }
}

module.exports = Request

```



```javascript
const Sequelize = require('sequelize');
let db = new Sequelize({
  dialect: 'mssql',
  dialectModulePath: 'msnodesqlv8/lib/sequelize',
  dialectOptions: {
    "user": "",
    "password": "",
    "database": "scratch",
    "connectionString": "Driver={SQL Server Native Client 11.0};Server=np:\\\\.\\pipe\\LOCALDB#18F297BD\\tsql\\query;Database=scratch;Trusted_Connection=yes;",
    "options": {
      "driver": "SQL Server Native Client 11.0",
      "trustedConnection": true,
      "instanceName": ""
    }
  },
  pool: {
    min: 0,
    max: 5,
    idle: 10000
  }
});

function run() {
  return new Promise(async (accept, reject) => {
    await db.authenticate().catch(e => reject(e))
    console.log('connected ok')
    let so = await db.query('SELECT top 2 * FROM syscolumns', {
      type: db.QueryTypes.SELECT
    })
      .catch(e => reject(e))
    console.log(JSON.stringify(so, null, 4))
    accept(so)
  })
}

run().then(() => {
  db.close()
  console.log('done')
})
```

```
Executing (default): SELECT 1+1 AS result
connected ok
Executing (default): SELECT top 2 * FROM syscolumns
[
    {
        "name": "rsid",
        "id": 3,
        "xtype": 127,
        "typestat": 1,
        "xusertype": 127,
        "length": 8,
        "xprec": 19,
        "xscale": 0,
        "colid": 1,
        "xoffset": 0,
        "bitpos": 0,
        "reserved": 0,
        "colstat": 0,
        "cdefault": 0,
        "domain": 0,
        "number": 0,
        "colorder": 1,
        "autoval": null,
        "offset": 0,
        "collationid": 0,
        "language": 0,
        "status": 0,
        "type": 63,
        "usertype": 0,
        "printfmt": null,
        "prec": 19,
        "scale": 0,
        "iscomputed": 0,
        "isoutparam": 0,
        "isnullable": 0,
        "collation": null,
        "tdscollation": {
            "type": "Buffer",
            "data": [
                0,
                0,
                0,
                0,
                0
            ]
        }
    },
    {
        "name": "rscolid",
        "id": 3,
        "xtype": 56,
        "typestat": 1,
        "xusertype": 56,
        "length": 4,
        "xprec": 10,
        "xscale": 0,
        "colid": 2,
        "xoffset": 0,
        "bitpos": 0,
        "reserved": 0,
        "colstat": 0,
        "cdefault": 0,
        "domain": 0,
        "number": 0,
        "colorder": 2,
        "autoval": null,
        "offset": 0,
        "collationid": 0,
        "language": 0,
        "status": 0,
        "type": 56,
        "usertype": 7,
        "printfmt": null,
        "prec": 10,
        "scale": 0,
        "iscomputed": 0,
        "isoutparam": 0,
        "isnullable": 0,
        "collation": null,
        "tdscollation": {
            "type": "Buffer",
            "data": [
                0,
                0,
                0,
                0,
                0
            ]
        }
    }
]
done
```

**Comment by TimelordUK** [comment]
to start things off, these following tests seem to work OK with the patched Request file


```javascript
const Sequelize = require('sequelize');

let sequelize = new Sequelize({
  dialect: 'mssql',
  dialectModulePath: 'msnodesqlv8/lib/sequelize',
  dialectOptions: {
    "user": "",
    "password": "",
    "database": "scratch",
    "connectionString": "Driver={SQL Server Native Client 11.0};Server=np:\\\\.\\pipe\\LOCALDB#18F297BD\\tsql\\query;Database=scratch;Trusted_Connection=yes;",
    "options": {
      "driver": "SQL Server Native Client 11.0",
      "trustedConnection": true,
      "instanceName": ""
    }
  },
  pool: {
    min: 0,
    max: 5,
    idle: 10000
  }
});

function createUserModel() {
  return sequelize.define('user', {
    username: {
      type: Sequelize.STRING
    },
    job: {
      type: Sequelize.STRING
    }
  })
}

function userModel() {
  return new Promise(async (accept, reject) => {
    let user = createUserModel()
    // force: true will drop the table if it already exists
    await user.sync({force: true})
    await Promise.all([
      user.create({
        username: 'techno01',
        job: 'Programmer'
      }),
      user.create({
        username: 'techno02',
        job: 'Head Programmer'
      }),
      user.create({
        username: 'techno03',
        job: 'Agile Leader'
      })
    ]).catch((e) => reject(e))

    let id1 = await user.findByPk(3)
    console.log(JSON.stringify(id1, null, 4))

    let agile = await user.findOne({
      where: {job: 'Agile Leader'}
    })
    console.log(JSON.stringify(agile, null, 4))

    let all = await user.findAll()
    console.log(JSON.stringify(all, null, 4))

    let programmers = await user
      .findAndCountAll({
        where: {
          job: {
            [Sequelize.Op.like]: '%Programmer'
          }
        },
        limit: 2
      })
    console.log(programmers.count);
    const dataValues = programmers.rows.reduce((aggregate, latest) => {
      aggregate.push(latest.dataValues)
      return aggregate
    }, [])
    console.log(dataValues);

    accept()
  })
}

userModel().then(() => {
  sequelize.close()
  console.log('done')
})

```

```cmd
Executing (default): IF OBJECT_ID('[users]', 'U') IS NOT NULL DROP TABLE [users];
Executing (default): IF OBJECT_ID('[users]', 'U') IS NULL CREATE TABLE [users] ([id] INTEGER NOT NULL IDENTITY(1,1) , [username] NVARCHAR(255) NULL, [job] NVARCHAR(255) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[users]';
Executing (default): INSERT INTO [users] ([username],[job],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'techno01',N'Programmer',N'2018-12-24 18:04:29.540 +00:00',N'2018-12-24 18:04:29.540 +00:00');
Executing (default): INSERT INTO [users] ([username],[job],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'techno02',N'Head Programmer',N'2018-12-24 18:04:29.541 +00:00',N'2018-12-24 18:04:29.541 +00:00');
Executing (default): INSERT INTO [users] ([username],[job],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'techno03',N'Agile Leader',N'2018-12-24 18:04:29.541 +00:00',N'2018-12-24 18:04:29.541 +00:00');
Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user] WHERE [user].[id] = 3;
{
    "id": 3,
    "username": "techno03",
    "job": "Agile Leader",
    "createdAt": "2018-12-24T18:04:29.541Z",
    "updatedAt": "2018-12-24T18:04:29.541Z"
}
Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user] WHERE [user].[job] = N'Agile Leader' ORDER BY [user].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
{
    "id": 3,
    "username": "techno03",
    "job": "Agile Leader",
    "createdAt": "2018-12-24T18:04:29.541Z",
    "updatedAt": "2018-12-24T18:04:29.541Z"
}
Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user];
[
    {
        "id": 1,
        "username": "techno01",
        "job": "Programmer",
        "createdAt": "2018-12-24T18:04:29.540Z",
        "updatedAt": "2018-12-24T18:04:29.540Z"
    },
    {
        "id": 2,
        "username": "techno02",
        "job": "Head Programmer",
        "createdAt": "2018-12-24T18:04:29.541Z",
        "updatedAt": "2018-12-24T18:04:29.541Z"
    },
    {
        "id": 3,
        "username": "techno03",
        "job": "Agile Leader",
        "createdAt": "2018-12-24T18:04:29.541Z",
        "updatedAt": "2018-12-24T18:04:29.541Z"
    }
]
Executing (default): SELECT count(*) AS [count] FROM [users] AS [user] WHERE [user].[job] LIKE N'%Programmer';
Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user] WHERE [user].[job] LIKE N'%Programmer' ORDER BY [user].[id] OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY;
2
[ { id: 1,
    username: 'techno01',
    job: 'Programmer',
    createdAt: { 2018-12-24T18:04:29.540Z nanosecondsDelta: 0 },
    updatedAt: { 2018-12-24T18:04:29.540Z nanosecondsDelta: 0 } },
  { id: 2,
    username: 'techno02',
    job: 'Head Programmer',
    createdAt: { 2018-12-24T18:04:29.541Z nanosecondsDelta: 0 },
    updatedAt: { 2018-12-24T18:04:29.541Z nanosecondsDelta: 0 } } ]
done

```

**Comment by JonPaz** [comment]
Thanks for your replies TimelordUK, I'm away at the present - I'll dive in
and try to understand them once I'm home over the next few days!

BR

Jon.

**Comment by JonPaz** [comment]
> 
> 
> to start things off, these following tests seem to work OK with the patched Request file
> 
> ```js
> const Sequelize = require('sequelize');
> 
> let sequelize = new Sequelize({
>   dialect: 'mssql',
>   dialectModulePath: 'msnodesqlv8/lib/sequelize',
>   dialectOptions: {
>     "user": "",
>     "password": "",
>     "database": "scratch",
>     "connectionString": "Driver={SQL Server Native Client 11.0};Server=np:\\\\.\\pipe\\LOCALDB#18F297BD\\tsql\\query;Database=scratch;Trusted_Connection=yes;",
>     "options": {
>       "driver": "SQL Server Native Client 11.0",
>       "trustedConnection": true,
>       "instanceName": ""
>     }
>   },
>   pool: {
>     min: 0,
>     max: 5,
>     idle: 10000
>   }
> });
> 
> function createUserModel() {
>   return sequelize.define('user', {
>     username: {
>       type: Sequelize.STRING
>     },
>     job: {
>       type: Sequelize.STRING
>     }
>   })
> }
> 
> function userModel() {
>   return new Promise(async (accept, reject) => {
>     let user = createUserModel()
>     // force: true will drop the table if it already exists
>     await user.sync({force: true})
>     await Promise.all([
>       user.create({
>         username: 'techno01',
>         job: 'Programmer'
>       }),
>       user.create({
>         username: 'techno02',
>         job: 'Head Programmer'
>       }),
>       user.create({
>         username: 'techno03',
>         job: 'Agile Leader'
>       })
>     ]).catch((e) => reject(e))
> 
>     let id1 = await user.findByPk(3)
>     console.log(JSON.stringify(id1, null, 4))
> 
>     let agile = await user.findOne({
>       where: {job: 'Agile Leader'}
>     })
>     console.log(JSON.stringify(agile, null, 4))
> 
>     let all = await user.findAll()
>     console.log(JSON.stringify(all, null, 4))
> 
>     let programmers = await user
>       .findAndCountAll({
>         where: {
>           job: {
>             [Sequelize.Op.like]: '%Programmer'
>           }
>         },
>         limit: 2
>       })
>     console.log(programmers.count);
>     const dataValues = programmers.rows.reduce((aggregate, latest) => {
>       aggregate.push(latest.dataValues)
>       return aggregate
>     }, [])
>     console.log(dataValues);
> 
>     accept()
>   })
> }
> 
> userModel().then(() => {
>   sequelize.close()
>   console.log('done')
> })
> ```
> 
> ```batchfile
> Executing (default): IF OBJECT_ID('[users]', 'U') IS NOT NULL DROP TABLE [users];
> Executing (default): IF OBJECT_ID('[users]', 'U') IS NULL CREATE TABLE [users] ([id] INTEGER NOT NULL IDENTITY(1,1) , [username] NVARCHAR(255) NULL, [job] NVARCHAR(255) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([id]));
> Executing (default): EXEC sys.sp_helpindex @objname = N'[users]';
> Executing (default): INSERT INTO [users] ([username],[job],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'techno01',N'Programmer',N'2018-12-24 18:04:29.540 +00:00',N'2018-12-24 18:04:29.540 +00:00');
> Executing (default): INSERT INTO [users] ([username],[job],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'techno02',N'Head Programmer',N'2018-12-24 18:04:29.541 +00:00',N'2018-12-24 18:04:29.541 +00:00');
> Executing (default): INSERT INTO [users] ([username],[job],[createdAt],[updatedAt]) OUTPUT INSERTED.* VALUES (N'techno03',N'Agile Leader',N'2018-12-24 18:04:29.541 +00:00',N'2018-12-24 18:04:29.541 +00:00');
> Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user] WHERE [user].[id] = 3;
> {
>     "id": 3,
>     "username": "techno03",
>     "job": "Agile Leader",
>     "createdAt": "2018-12-24T18:04:29.541Z",
>     "updatedAt": "2018-12-24T18:04:29.541Z"
> }
> Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user] WHERE [user].[job] = N'Agile Leader' ORDER BY [user].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
> {
>     "id": 3,
>     "username": "techno03",
>     "job": "Agile Leader",
>     "createdAt": "2018-12-24T18:04:29.541Z",
>     "updatedAt": "2018-12-24T18:04:29.541Z"
> }
> Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user];
> [
>     {
>         "id": 1,
>         "username": "techno01",
>         "job": "Programmer",
>         "createdAt": "2018-12-24T18:04:29.540Z",
>         "updatedAt": "2018-12-24T18:04:29.540Z"
>     },
>     {
>         "id": 2,
>         "username": "techno02",
>         "job": "Head Programmer",
>         "createdAt": "2018-12-24T18:04:29.541Z",
>         "updatedAt": "2018-12-24T18:04:29.541Z"
>     },
>     {
>         "id": 3,
>         "username": "techno03",
>         "job": "Agile Leader",
>         "createdAt": "2018-12-24T18:04:29.541Z",
>         "updatedAt": "2018-12-24T18:04:29.541Z"
>     }
> ]
> Executing (default): SELECT count(*) AS [count] FROM [users] AS [user] WHERE [user].[job] LIKE N'%Programmer';
> Executing (default): SELECT [id], [username], [job], [createdAt], [updatedAt] FROM [users] AS [user] WHERE [user].[job] LIKE N'%Programmer' ORDER BY [user].[id] OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY;
> 2
> [ { id: 1,
>     username: 'techno01',
>     job: 'Programmer',
>     createdAt: { 2018-12-24T18:04:29.540Z nanosecondsDelta: 0 },
>     updatedAt: { 2018-12-24T18:04:29.540Z nanosecondsDelta: 0 } },
>   { id: 2,
>     username: 'techno02',
>     job: 'Head Programmer',
>     createdAt: { 2018-12-24T18:04:29.541Z nanosecondsDelta: 0 },
>     updatedAt: { 2018-12-24T18:04:29.541Z nanosecondsDelta: 0 } } ]
> done
> ```

Hi @TimelordUK,

I've tried out your suggested change and it does work as you tested. I'd like to help out with getting the Sequalise <> msnodesqlv8 integration working (and unit tested etc.), but don't want to duplicate any on-going effort on your side!  I'm happy to get going (as much as I can), but please let me know how you'd like to go forward.

Cheers,

Jon.
Jon.

**Comment by TimelordUK** [comment]
try v. 0.6.12

right now this is simply a copy with the patched Request file.

you can add a lot of value by letting me know if you find anything that does not appear to work with sequelize.  It makes things 10 x easier if you provide a sample SQL showing where the problem occurs.  

```js
 dialectModulePath: 'msnodesqlv8/lib/sequelize',
```

```js
let sequelize = new Sequelize({
  dialect: 'mssql',
  dialectModulePath: 'msnodesqlv8/lib/sequelize',
  dialectOptions: {
    'user': '',
    'password': '',
    'database': 'scratch',
    'connectionString': 'Driver={SQL Server Native Client 11.0};Server= np:\\\\.\\pipe\\LOCALDB#2DD5ECA9\\tsql\\query;Database=scratch;Trusted_Connection=yes;',
    'options': {
      'driver': 'SQL Server Native Client 11.0',
      'trustedConnection': true,
      'instanceName': ''
    }
  },
  pool: {
    min: 0,
    max: 5,
    idle: 10000
  }
})

```

**Comment by JonPaz** [comment]
Thanks @TimelordUK,

I'll give it workout over the week and let you know!

**Comment by TimelordUK** [comment]
i am assuming this is now ok, so closing.
