### ISSUE TITLE
Feature Request: Implement pause/resume for request streams

### ISSUE THREAD

**Issue by dhensby** [TimelordUK/node-sqlserver-v8#89]
I'm helping to maintain [node-mssql](https://github.com/tediousjs/node-mssql) and the tedious driver has recently added pause/resume functions to their requests which has allowed us to pass this functionality on.

Pausing and resuming request streams is very useful when dealing with extremely large datasets as it allows the application to back-off when processing of rows can't keep up with the speed they are returned (usually resulting in out of memory errors).

Ideally I'd like to implement true node streams in node-mssql but I can't do this without the `sqlserver-v8` driver providing this back-off functionality.

**Comment by dhensby** [comment]
> So I guess it all depends on what is needed

Sorry for delay on this. From our point of view we just need to be able to reliably apply backpressure to a stream (ie: pause and resume it on demand). I'm not too bothered about concurrency (though that would be nice).

**Comment by TimelordUK** [comment]
this should be available in 0.7.2

```javascript
  test('pause a large query every 100 rows', testDone => {
    let expected = 0
    const q0 = theConnection.query(`select * from syscolumns`)
    q0.on('row', () => {
      ++expected
    })
    let rows = 0
    const q = theConnection.query(`select * from syscolumns`)
    q.on('error', (e) => {
      assert.ifError(e)
    })
    q.on('row', () => {
      ++rows
      if (rows % 100 === 0) {
        q.pauseQuery()
        setTimeout(() => {
          q.resumeQuery()
        }, 200)
      }
    })
    q.on('done', () => {
      assert.strictEqual(expected, rows)
      testDone()
    })
  })
```

**Comment by dhensby** [comment]
Thanks for this @TimelordUK - I've opened a PR to add the pause/resume feature to our v8 adapter. However it seems to be failing in our appveyor builds for node v6 and v8 (v10 is running, at least).

Any ideas what the difference would be?

**Comment by dhensby** [comment]
Ah - I just noticed in [v0.7.1](https://github.com/TimelordUK/node-sqlserver-v8/tree/0.7.1) you dropped node <10 support. The `package.json` for this lib needs updating, then.

**Comment by TimelordUK** [comment]
I have had request to potentially add older node back unfortunately the cpp itself will not compile against old and new post 10 node without basically compiler switches based on version which is why I wanted to drop it.

**Comment by dhensby** [comment]
This is now done 🎉
