### ISSUE TITLE
Connection not closing after pm.callproc(...) resulting in record locking and performance dragging.

### ISSUE THREAD

**Issue by micsel** [TimelordUK/node-sqlserver-v8#90]
There seem to be a problem when calling stored procedure. I believe the conn.close(); is important. After implementing it, all went ok, otherwise SSMS and any other applications freezes and stop responding until the app that called the stored procedure exits. Please validate this and update all manual documentation if this is the case, other wise this might be a bug, as conn is not closing automatically on such as timeout auto close!.
`...()=>{`
`   let pm = conn.procedureMgr();`
`   pm.setTimeout(2);`
`   pm.callproc(StoredProcedureName,query,(err, results, output) => {`
`   conn.close(); //without this, SQL Server Management Studio struggles to open any tables`
`   if(err){...}`
`   else{}`
`}`

**Comment by TimelordUK** [comment]
Thanks I will check and patch this in. You are right we are probably not closing on timeout.

**Comment by micsel** [comment]
Also there is an issue caused by the same problem on *.query(...). Everything hangs. I below approach seems to work. Basically first open the connection and then query and after that make sure to close the connection. Code below.
`const sql = require('msnodesqlv8');`
`var co = {conn_str : connectionString,conn_timeout : 2};`
`let start = new Date().getTime();`
`sql.open(co, (err, conn) => {` //OPEN CONNECTION HERE
 `let end = new Date().getTime(),elapsed = end - start;`
`if(err){ ...}`
`}else{`
`let queryObj = { query_str : /*YOUR QUERY*/,query_timeout : 2};`
`conn.query(queryObj, (err, rows) => {`
`conn.close();//CLOSE CONNECTION HERE`
`if(err){ ...}`
`}else{`
 `  //output`
`   //console.log(rows)`
`}`
`});`
`}`

**Comment by TimelordUK** [comment]
I have never reproduced this issue the stored proc call should not close connection. It is a requirement the application closes connection when it is done. I am closing this issue.
