### ISSUE TITLE
Missing ISOLATION_LEVEL in sequelize

### ISSUE THREAD

**Issue by jssuttles** [TimelordUK/node-sqlserver-v8#91]
Missing ISOLATION_LEVEL in sequelize
https://github.com/tediousjs/tedious/blob/master/src/transaction.js#L18

**Comment by TimelordUK** [comment]
hi,

sorry about late response - it looks like we can set isolation attribute on the connection itself, is this OK?

that is to say, we could add a method to a connection to set isolation level which effects all transactions on that connection using ODBC the c++ driver

**Comment by jssuttles** [comment]
I'll close this issue. I needed this module to handle windows authentication, but there were a lot of differences between this module and tedious, so I didn't want to hack it together.

**Comment by TimelordUK** [comment]
Thanks for letting us know. A lot of the differences are abstracted with the mssql npm library however I appreciate even then they may not behave precisely the same.  I was about to take a look and may well add to help others that may need it.  

Cheers.
