### ISSUE TITLE
MSSQL | Linux | Windows authentication | Keytab

### ISSUE THREAD

**Issue by sathishkumarece** [TimelordUK/node-sqlserver-v8#95]
Hello Team,

I have requirement that I need to use Windows based authentication to connect to Microsoft SQL server from the Nodejs application hosted on Redhat Linux machine.

I couldn't find the proper article which explains about its possible or not.

I found that it is possible in case of JAVA application using Kerberos with setting "integratedSecurity=true;authenticationScheme=JavaKerberos" but nothing for NodeJS application.

Is it possible to configure 'keytab' file (generated using kinit or similar tool) in MSSQL module?

It will be great if I get a direction to proceed.
Thanks in advance for support.

**Comment by TimelordUK** [comment]
this may help - we now support Linux using this library

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver15

sorry I am closing this issue, please raise if any further support required.

**Comment by TBG-FR** [comment]
@sathishkumarece did you manage to use Kerberos Auth with this module ?
