### ISSUE TITLE
'info' event results in 'done' event not firing?

### ISSUE THREAD

**Issue by jeffeld** [TimelordUK/node-sqlserver-v8#97]
Hi,

I'm seeing a weird issue with the info event (being triggered by print statements in a stored proc). Here's a repro:

    const sql = require("msnodesqlv8");
    
    const connectionString = '** your connection string here **';
    const procName = '** a proc that uses a print statement before a SELECT';
    const params = [];
    
    async function test () {
    
      let rows = 0;
    
      return new Promise ((resolve, reject) => {
        sql.open(connectionString, (errOpen, connection) => {
    
          const pm = connection.procedureMgr();
          const q = pm.callproc (procName, params);
    
          q.on('meta', (meta) => {
            console.log ('onMeta');
          });
    
          q.on('column', (colIndex, data) => {
            // console.log ('onColumn');
          });
    
          q.on('row', (row) => {
            rows += 1;
            console.log (`onRow ${rows}`);
          });
    
          q.on('done', async () => {
            console.log ('onDone');
            resolve(rows);
          });
    
          q.on('error', (err) => {
            console.log ('onError');
            reject(err.message);
          });
    
          q.on('info', (err) => {
            console.log (`onInfo: ${err.message}`);
          });
    
          q.on('submitted', (query) => {
            console.log ('onSubmitted');
          });
    
        });
    
      });
    
    }
    
    async function go () {
      const rows = await test();
      console.log (`${rows} returned`);
    }
    
    go();

If the proc called doesn't have a print statement in, the output will be 

    onSubmitted
    onMeta
    onRow 1
    onRow 2
    ...
    onRow n
    onDone

But for a proc with a print statement:

    onSubmitted
    onInfo
    onMeta
    onRow 1
    onRow 2
    ...
    onRow n

Any help would be appreciated.

Node version is 10.0.13 and mssqlnodev8 is 0.7.1

Thanks,
Jeff

**Comment by TimelordUK** [comment]
I’ll have to check the code but unless I’m mistaken this was intentional.  In previous issue they wanted to see the procedure print statements so they could be captured and I think from memory these were showing up as error messages. 

So a change was made to treat them and other warnings as information leaving the error event for genuine errors as this is used for example by mssql to halt processing.

**Comment by jeffeld** [comment]
Hi,

Thanks for the quick reply. 

I admit I don't understand the rationale here; why would an info event prevent done from firing; it makes no sense to me. So I guess the question becomes, how do you know when you're done *if* there is an info event.

In my particular case, I'm batch processing (in batches of 100 rows) multiple queries (that can return 10K's of rows each) in a CI environment, so I'm streaming rather than loading all the data into memory.

For the moment, the SQL dev is removing print statements from the sprocs - but this invites human error and breaking production.

Cheers,
Jeff

**Comment by TimelordUK** [comment]
Ok will get back to you I had misread this as an enquiry into why we sending info messages.  If done is not firing that sounds like an issue when you say a batch do you mean a large sql statement with many inserts for example.   

I’ll have to first reproduce the issue the done event should fire regardless of info messages

**Comment by TimelordUK** [comment]
I was able to reproduce the issue - this must have been around for quite some time, it seems specifically in stored procedures the driver could move too early onto next query before finishing correctly, where one such case is a print as you described.

I have tested and released in 0.7.2, hopefully that sorts it out.


```javascript
  test('stream call proc no callback with print in proc', testDone => {
    const spName = 'test_len_of_sp'

    const def = `alter PROCEDURE <name> @param VARCHAR(50) 
 AS 
 BEGIN 
     raiserror('a print in proc message',0,0) with nowait;
     select LEN(@param) as len; 
 END 
`

    const fns = [
      asyncDone => {
        procedureHelper.createProcedure(spName, def, () => {
          asyncDone()
        })
      },

      asyncDone => {
        const pm = theConnection.procedureMgr()
        const rows = []
        let info = null
        let submitted = false
        pm.get(spName, proc => {
          const qp = proc.call(['javascript'])
          qp.on('column', (c, data) => {
            const l = c.toString()
            const r = {}
            r[l] = data
            rows.push(r)
          })

          qp.on('done', () => {
            // console.log('done ....')
            assert(rows.length === 1)
            assert.strictEqual(true, submitted)
            assert.strictEqual('[Microsoft][SQL Server Native Client 11.0][SQL Server]a print in proc message', info)
            const expected = [
              {
                '0': 10
              }
            ]
            assert.deepStrictEqual(expected, rows)
            asyncDone()
          })

          qp.on('error', (e) => {
            assert.ifError(e)
          })

          qp.on('submitted', (q) => {
            // console.log('submitted')
            submitted = true
          })

          qp.on('info', (i) => {
            // console.log(`info ${i}`)
            info = i.message
          })
        })
      }
    ]

    async.series(fns, () => {
      testDone()
    })
  })
```

**Comment by jeffeld** [comment]
Brilliant - thank you so much! Will test and let you know,

**Comment by jeffeld** [comment]
Confirmed fixed.

Cheers!
